### ISSUE TITLE
IOS decoders will not match

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh-ruleset#101]
Hello, I noticed that the regex for the cisco ios decoders will not match the messages. Even the ones provided as examples in the decoder file.

https://github.com/wazuh/wazuh-ruleset/blob/aa1ab259a818911a51c5114179dde88143ad0e8e/decoders/0065-cisco-ios_decoders.xml#L15-L32

**Comment by frgv** [comment]
Hi rossengeorgiev,

First of all, sorry for the late reply. Thank you very much for noticing that problem. 

Cisco has a variety of different log types, and the decoders aren't working properly with all of them.

We're working on it, and it would be helpful if you could send us some real log samples.

Thank you in advance.

Best regards,

Fran González.

**Comment by rossengeorgiev** [comment]
Hi @frgv, I'm only looking at the examples in the xml file:

Out of all these:

```text
Aug 17 17:41:26 xyz.com 681: Aug 17 17:41:24.776 AEST: %SEC-6-IPACCESSLOGS: list 30 denied 124.254.75.141 1 packet 
Aug 20 11:33:41 RouterName 696: %SYS-5-CONFIG_I: Configured from console by admin on vty0 (210.x.x.12) 
681: Aug 17 17:41:24.776 AEST: %SEC-6-IPACCESSLOGS: 
1348: .Jun 12 18:22:22 UTC: %SYS-5-CONFIG_I: 
1348: *Jun 12 18:22:22 UTC: %SYS-5-CONFIG_I: 
23: May  3 05:15:25.217 UTC: %SEC-6-IPACCESSLOGP:
```
Only this one will works:
```text
Aug 20 11:33:41 RouterName 696: %SYS-5-CONFIG_I: Configured from console by admin on vty0 (210.x.x.12)
```

**Comment by frgv** [comment]
Hi @rossengeorgiev, 

Got it. Thank you very much for the feedback. We've been working on improving the ios decoders and they're almost ready, they will be out very soon. Now they're working for each example, and also some new ones from Cisco documentation.

Thanks for the catch!

Best regards, 

Fran.

**Comment by frgv** [comment]
Hello @rossengeorgiev 

In this pull request, Cisco IOS decoders have been fixed and upgraded:

https://github.com/wazuh/wazuh-ruleset/pull/108

Regards,

Fran G.
