### ISSUE TITLE
Problem with kernel decoder - broken?

### ISSUE THREAD

**Issue by mrmqe** [wazuh/wazuh-ruleset#103]
There is really strange problem with kernel decoder..

With ossec-logtest this following log entry works fine and it is correctly recognized (it is directly from the kernel decoder file example):

_Aug 17 10:03:37 myhostname kernel: SFW2-INext-DROP-DEFLT IN=eth0 OUT= MAC=00:08:02:da:c8:51:00:0f:f7:74:31:8a:08:00 SRC=1.2.3.36 DST=1.2.3.194 LEN=28 TOS=0x00 PREC=0x00 TTL=44 ID=60200 PROTO=ICMP TYPE=8 CODE=0 ID=10466 SEQ=21229_

However, if i echo the same line to /var/log/messages it will not work.
Even if I enable: <logall>yes</logall>, it still wont appear in archives.log.

I noticed the same behaviour when we tried to send syslog messages from VYOS firewall to the syslog listener and they just disapper (yes, even when logall is enabled). However the logtest says the log entry is just fine.

_**Phase 1: Completed pre-decoding.
       full event: 'Aug 17 10:03:37 myhostname kernel: SFW2-INext-DROP-DEFLT IN=eth0 OUT= MAC=00:08:02:da:c8:51:00:0f:f7:74:31:8a:08:00 SRC=1.2.3.36 DST=1.2.3.194 LEN=28 TOS=0x00 PREC=0x00 TTL=44 ID=60200 PROTO=ICMP TYPE=8 CODE=0 ID=10466 SEQ=21229'
       timestamp: 'Aug 17 10:03:37'
       hostname: 'myhostname'
       program_name: 'kernel'
       log: 'SFW2-INext-DROP-DEFLT IN=eth0 OUT= MAC=00:08:02:da:c8:51:00:0f:f7:74:31:8a:08:00 SRC=1.2.3.36 DST=1.2.3.194 LEN=28 TOS=0x00 PREC=0x00 TTL=44 ID=60200 PROTO=ICMP TYPE=8 CODE=0 ID=10466 SEQ=21229'

**Phase 2: Completed decoding.
       decoder: 'kernel'
       action: 'SFW2-INext-DROP-DEFLT'
       srcip: '1.2.3.36'
       dstip: '1.2.3.194'
       proto: 'ICMP'

**Phase 3: Completed filtering (rules).
       Rule id: '4100'
       Level: '0'
       Description: 'Firewall rules grouped.'_

If I remove the "SFW-INext-DROP-DEFLT" after the "kernel:", it appears in the archives.log but ossec-logtest is not able to parse it anymore.

**Comment by jesuslinares** [comment]
Hi @mrmqe ,

> However, if i echo the same line to /var/log/messages it will not work.

If you send exactly the same line, Wazuh will ignore that event (it is duplicated). Try to change the date (seconds) and you should see the event (archives file) and the alert (alerts file).

Thanks,
Jesus.

**Comment by jesuslinares** [comment]
Hi @mrmqe ,

It's been more than a month since your last response to this issue, so I'll proceed to close it.
Don't hesitate to open a new one if you still have questions or problems using Wazuh.

Regards,
Jesus.
