### ISSUE TITLE
Rule 18107 ignore a system user

### ISSUE THREAD

**Issue by arielravi** [wazuh/wazuh-ruleset#110]
If any way that we can  exclude for our audit system login . We have 2 Windows users who belong to a monitor program  which  login constantly to our server
Can we exclude by account_name  ??
example ignore user monitor_app_user

thanks

**Comment by frgv** [comment]
Hello @arielravi 

Yes, you can ignore the certain user's successfully logins. 

For doing that, you can create a custom rule in `/var/ossec/etc/rules/local_rules.xml`. The idea is creating a sub-rule with `<if_sid>18107</if_sid> field and set its level to 0, so you won't receive any alert. Then, add a `match` field for matching any users you want to ignore. By doing that, any different user will trigger match the rule 18107, but the users you defined in the `match` field will trigger your custom alarm, so any alarm will be created.

This is a working example of this, applied to rule 5710 (ssh failed login):
```
<group name="exceptions,">

  <rule id="100003" level="0">
    <if_sid>5710</if_sid>
    <match>user testuser</match>
    <description>sshd: Ignoring attempt to login using a non-existent user</description>
    <group>invalid_login,authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,pci_dss_10.6.1,gpg13_7.1,</group>
  </rule>

</group>
```

Any wrong login to any user will trigger 5710 alarm, but failed logins to testuser will trigger no alarm.

By the way, it's highly recommended to give this new rule an id higher than 100000, because that is the "custom" range beginning, so you won't any problem with any possible future updates.

I hope it helps,

Fran G.

**Comment by arielravi** [comment]
Hi @frgv 

I follow your advise but I still show up user on alerts !!!
I modified  /var/ossec/etc/rules/local_rules.xml with the following  
`


<group name="exceptions,">

  <rule id="100003" level="0">
    <if_sid>18107</if_sid>
    <match>User DEMO</match>
    <description>Ignoring authentication_success login using DEMO user</description>
    <group>authentication_success,pci_dss_10.2.5,gpg13_7.1,gpg13_7.2,</group>
  </rule>

  <rule id="100004" level="0">
    <if_sid>18107</if_sid>
    <match>account_name  DEMO2$</match>
    <description>Ignoring authentication_success to login using  DEMO2$ user</description>
    <group>authentication_success,pci_dss_10.2.5,gpg13_7.1,gpg13_7.2,</group>
  </rule>

</group>`


When I check alerts.log 
User:  DEMO
2018 Mar 20 11:00:35 WinEvtLog: Security: AUDIT_SUCCESS(4624): Microsoft-Windows-Security-Auditing: DEMO: TEST: test.server.int: An account was successfully logged on. Subject:  Security ID:  S-1-0-0  Account Name:  -  Account Domain:  -  Logon ID:  0x0  Logon Type:   3  New Logon:  Security ID:  S-1-5-21-2751356588-657675712-467690633-39931  Account Name:  DEMO  Account Domain:  TEST  Logon ID:  0x92608069  Logon GUID:  {05F77F58-C559-B959-ACF9-7A7E58316F83}  Process Information:  Process ID:  0x0  Process Name:  -  Network Information:  Workstation Name:   Source Network Address: 172.X.X.X  Source Port:  65034  Detailed Authentication Information:  Logon Process:  Kerberos  Authentication Package: Kerberos  Transited Services: -  Package Name (NTLM only): -  Key Length:  0  This event is generated when a logon session is created. It is generated on the computer that was accessed.
type: Security
security_id: S-1-0-0
account_name:  DEMO
account_domain: TEST
logon_type: 3


If anything that I missed  I try with User , user and account_name and the same result

**Comment by frgv** [comment]
Hello @arielravi 

Your rules aren't working because you're not matching any text in the log received by wazuh: 

```
2016 Sep 27 10:48:30 WinEvtLog: Security: AUDIT_SUCCESS(4624): Microsoft-Windows-Security-Auditing: AAAABCC: KKKKK: 01.KKKKK.com: An account was successfully logged on. Subject:  Security ID:  S-1-0-0  Account Name:  -  Account Domain:  -  Logon ID:  0x0  Logon Type:   3  New Logon:  Security ID:  S-1-5-21-1119803419-263072742-1537874043-22758  Account Name:  AAAABCC  Account Domain:  KKKKK  Logon ID:  0x2b111bcc  Logon GUID:  {C609F1DB-667E-654F-AC26-48E1A2C6FA5F}  Process Information:  Process ID:  0x0  Process Name:  -  Network Information:  Workstation Name:   Source Network Address: 192.168.12.123  Source Port:  54200  Detailed Authentication Information:  Logon Process:  Kerberos  Authentication Package: Kerberos  Transited Services: -  Package Name (NTLM only): -  Key Length:  0
```

If you're trying to match `Account Name:  AAAABCC`, please note that `<match>account_name AAAABCC</match>` won't work. Instead you need anything like, for example: `<match>Account Name:  AAAABCC</match>`:

```
<group name="exceptions,">

    <rule id="100004" level="0">
    <if_sid>18107</if_sid>
    <match>Account Name:  AAAABCC</match>
    <description>Ignoring authentication_success to login using  AAAABCC user</description>
    <group>authentication_success,pci_dss_10.2.5,gpg13_7.1,gpg13_7.2,</group>
  </rule>

</group>
```

This rule will work correctly: 

```
**Phase 1: Completed pre-decoding.
       full event: '2016 Sep 27 10:48:30 WinEvtLog: Security: AUDIT_SUCCESS(4624): Microsoft-Windows-Security-Auditing: AAAABCC: KKKKK: 01.KKKKK.com: An account was successfully logged on. Subject:  Security ID:  S-1-0-0  Account Name:  -  Account Domain:  -  Logon ID:  0x0  Logon Type:   3  New Logon:  Security ID:  S-1-5-21-1119803419-263072742-1537874043-22758  Account Name:  AAAABCC  Account Domain:  KKKKK  Logon ID:  0x2b111bcc  Logon GUID:  {C609F1DB-667E-654F-AC26-48E1A2C6FA5F}  Process Information:  Process ID:  0x0  Process Name:  -  Network Information:  Workstation Name:   Source Network Address: 192.168.12.123  Source Port:  54200  Detailed Authentication Information:  Logon Process:  Kerberos  Authentication Package: Kerberos  Transited Services: -  Package Name (NTLM only): -  Key Length:  0'
       timestamp: '2016 Sep 27 10:48:30'
       hostname: 'manager1'
       program_name: 'WinEvtLog'
       log: 'Security: AUDIT_SUCCESS(4624): Microsoft-Windows-Security-Auditing: AAAABCC: KKKKK: 01.KKKKK.com: An account was successfully logged on. Subject:  Security ID:  S-1-0-0  Account Name:  -  Account Domain:  -  Logon ID:  0x0  Logon Type:   3  New Logon:  Security ID:  S-1-5-21-1119803419-263072742-1537874043-22758  Account Name:  AAAABCC  Account Domain:  KKKKK  Logon ID:  0x2b111bcc  Logon GUID:  {C609F1DB-667E-654F-AC26-48E1A2C6FA5F}  Process Information:  Process ID:  0x0  Process Name:  -  Network Information:  Workstation Name:   Source Network Address: 192.168.12.123  Source Port:  54200  Detailed Authentication Information:  Logon Process:  Kerberos  Authentication Package: Kerberos  Transited Services: -  Package Name (NTLM only): -  Key Length:  0'

**Phase 2: Completed decoding.
       decoder: 'windows'
       type: 'Security'
       status: 'AUDIT_SUCCESS'
       id: '4624'
       extra_data: 'Microsoft-Windows-Security-Auditing'
       dstuser: 'AAAABCC'
       system_name: '01.KKKKK.com'
       security_id: 'S-1-0-0'
       account_name: 'AAAABCC'
       account_domain: 'KKKKK'
       logon_type: '3'
       srcip: '192.168.12.123'

**Phase 3: Completed filtering (rules).
       Rule id: '100004'
       Level: '0'
       Description: 'Ignoring authentication_success to login using  AAAABCC user'
```

Another possibility is using those dynamic fields created by the decoder (as you can see at Phase 2 of the previous snippet), in this case `account_name` field:

```
<group name="exceptions,">

    <rule id="100005" level="0">
    <if_sid>18107</if_sid>
    <field name="account_name">AAAABCC</field>
    <description>Ignoring authentication_success to login using AAAABCC user</description>
    <group>authentication_success,pci_dss_10.2.5,gpg13_7.1,gpg13_7.2,</group>
  </rule>

</group>
```

Which is also working:

```
**Phase 1: Completed pre-decoding.
       full event: '2016 Sep 27 10:48:30 WinEvtLog: Security: AUDIT_SUCCESS(4624): Microsoft-Windows-Security-Auditing: AAAABCC: KKKKK: 01.KKKKK.com: An account was successfully logged on. Subject:  Security ID:  S-1-0-0  Account Name:  -  Account Domain:  -  Logon ID:  0x0  Logon Type:   3  New Logon:  Security ID:  S-1-5-21-1119803419-263072742-1537874043-22758  Account Name:  AAAABCC  Account Domain:  KKKKK  Logon ID:  0x2b111bcc  Logon GUID:  {C609F1DB-667E-654F-AC26-48E1A2C6FA5F}  Process Information:  Process ID:  0x0  Process Name:  -  Network Information:  Workstation Name:   Source Network Address: 192.168.12.123  Source Port:  54200  Detailed Authentication Information:  Logon Process:  Kerberos  Authentication Package: Kerberos  Transited Services: -  Package Name (NTLM only): -  Key Length:  0'
       timestamp: '2016 Sep 27 10:48:30'
       hostname: 'manager1'
       program_name: 'WinEvtLog'
       log: 'Security: AUDIT_SUCCESS(4624): Microsoft-Windows-Security-Auditing: AAAABCC: KKKKK: 01.KKKKK.com: An account was successfully logged on. Subject:  Security ID:  S-1-0-0  Account Name:  -  Account Domain:  -  Logon ID:  0x0  Logon Type:   3  New Logon:  Security ID:  S-1-5-21-1119803419-263072742-1537874043-22758  Account Name:  AAAABCC  Account Domain:  KKKKK  Logon ID:  0x2b111bcc  Logon GUID:  {C609F1DB-667E-654F-AC26-48E1A2C6FA5F}  Process Information:  Process ID:  0x0  Process Name:  -  Network Information:  Workstation Name:   Source Network Address: 192.168.12.123  Source Port:  54200  Detailed Authentication Information:  Logon Process:  Kerberos  Authentication Package: Kerberos  Transited Services: -  Package Name (NTLM only): -  Key Length:  0'

**Phase 2: Completed decoding.
       decoder: 'windows'
       type: 'Security'
       status: 'AUDIT_SUCCESS'
       id: '4624'
       extra_data: 'Microsoft-Windows-Security-Auditing'
       dstuser: 'AAAABCC'
       system_name: '01.KKKKK.com'
       security_id: 'S-1-0-0'
       account_name: 'AAAABCC'
       account_domain: 'KKKKK'
       logon_type: '3'
       srcip: '192.168.12.123'

**Phase 3: Completed filtering (rules).
       Rule id: '100005'
       Level: '0'
       Description: 'Ignoring authentication_success to login using AAAABCC user'
```

I hope it helps, and please don't hesitate to write us for any further question.

Regards, 

Fran G.

**Comment by frgv** [comment]
Hello!

Has been more than a month since the last response, so I will conclude this thread.

If you have any further doubt or problem, please don't hesitate to open a new thread.

Best regards,

Fran G.

**Comment by green0tree22** [comment]
Hi,
Are this applicable to wazuh client. im using wazuh cleint in windows server. it also showing the system in event logs. how can i exclude the group
Thanks
