### ISSUE TITLE
What could OSSEC do when some anomaly where already spreading ( a.k.a virus ) on the system ?

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh-ruleset#117]
Is there any rules, or some active-response command that would stop some virus or anomaly from spreading, infect and crushing our system. Is there ever any demostration regarding those condition ? where could i find it ?

what i have tried is like blocking an ip for brute force attack (FTP, SSH), but what about if the hacker are in some condition could prevent the ossec rules blocking ip, and he started to spread some unwanted files.document as known as virus ? Is there any footage or demonstration about that ?

**Comment by PSanchezR** [comment]
Hello gagantous,

Currently, the active responses implemented are not aimed at blocking specific software or processes, but a script that kills a particular process associated with a file that has been detected as malware could be implemented.

 The integration with virustotal included in Wazuh version 3.0.0 can help you with malware detection, you can see the configuration [here](https://documentation.wazuh.com/current/user-manual/capabilities/active-response/index.html?highlight=custom%20active%20response). By means of the alerts generated by virustotal, the name of the infected file can be extracted and with an active response that blocks the process associated with the file, this malware can be stopped.

You can develop your own active response by following the [documentation](https://documentation.wazuh.com/current/user-manual/capabilities/active-response/remediation-faq.html#can-i-use-a-custom-script-for-active-responses).

If you have any other question I'll be happy to help you.

Best regards,

Pablo.
