### ISSUE TITLE
Rule 31533 exception

### ISSUE THREAD

**Issue by deajan** [wazuh/wazuh-ruleset#124]
Hello,

I have a server where rule 31533 is frequently triggered by myself when using my webmail (Kopano) which does lots of POST requests.
As for now, I increased frequency and reduced timeframe in order to avoid this behavoir.
Is there a way to "fork" that rule into another one that could be applied to a virtualhost specifically ?

I already encountered this with OSSEC some years ago about the same rule, had an open ticket and PR that lead to a long discussion about whether changing the base rule or not, regarding the ecosystem of more and more ajax apps (https://github.com/ossec/ossec-hids/issues/461).

What do you guys think ? This rule renders Drupal / IMCE / Kopano WebApp / probably lots of other AJAX driven web apps unusable since they probably do more than 12 POST requests in 20 seconds.

**Comment by frgv** [comment]
Hello deajan,

if you posted a sanitized log/alert, we could have a better vision on how to tackle the problem.

Meanwhile, you can take a look at which fields are extracted, and create a new rule similar to 31531:

  ```
 <rule id="31531" level="0">
       <if_sid>31530</if_sid>
       <url>/wp-admin/|/administrator/|/admin/</url>
       <description>Ignoring often post requests inside /wp-admin and /admin.</description>
   </rule>

```

This rule looks for `/wp-admin/` , `/administrator/` or `/admin/` and assigns a level 0 rule if found, and will trigger no alarm.

Maybe you could find some field you could use for this, like `srcip `or `id `(although I'd recommend making this as fine as possible, for avoiding false negatives).

You could save this new rule in `/var/ossec/etc/rules/local_rules.xml` or in a new .xml in `/var/ossec/etc/rules`, if you want to keep rules as organized as possible. 

I hope it helps,

Fran G.

**Comment by deajan** [comment]
Thank you alot, but as an example the webmail I'm using URL is http://my.example.com so there's no URL suffix I can use as rule. I'll check the `id` parameter.

I'll post a log alert along.

**Comment by jesuslinares** [comment]
Hi @deajan ,

It's been almost a month since the last response to this issue, so I'll proceed to close it.

Don't hesitate to open a new one if you still have questions or you want to share the event that you want to ignore.

Thanks,
Jesus.
