### ISSUE TITLE
Checkpoint decoders not working properly

### ISSUE THREAD

**Issue by frgv** [wazuh/wazuh-ruleset#126]
Checkpoint decoders are not working properly. The ones included doesn't fit most part of the logs found on real systems: 

https://groups.google.com/forum/?hl=en#!searchin/ossec-list/checkpoint%7Csort:date/ossec-list/U7_kTZKRDCc/U3DiEXiXCwAJ

https://groups.google.com/forum/#!topic/wazuh/r6p_pl9hgSo

https://ossec-docs.readthedocs.io/en/latest/log_samples/firewalls/checkpoint.html

These decoders need to be more flexible, and maybe not always can be possible to get the program name pre-decoded.

**Comment by SitoRBJ** [comment]
Hello team,

This issue is solved in PR #156.

Thank you for your contribution

Regards, 

Alfonso Ruiz-Bravo
