### ISSUE TITLE
dpkg log not triggering rules 290x rules

### ISSUE THREAD

**Issue by gibanitza** [wazuh/wazuh-ruleset#134]
Hi,

I have noticed that events from dpkg log aren't triggering rules (version 3.2.1).  

Seems that the issue is in 0020-syslog_rules.xml for rule 2900:

```
  <rule id="2900" level="0">
    <decoded_as>windows-date-format</decoded_as>
    <regex offet="after_parent">^startup |^status |^remove |^configure |^install |^purge |^trigproc </regex>
    <description>Dpkg (Debian Package) log.</description>
  </rule>
```

Several thing are wrong here which may be the reason why events from dpkg are not triggering alerts as they should:

- typo (regex offset)
- caret before status
- _installed_ status missing

Corrected rule helped me solve this issue:
```<group name="syslog,dpkg,">
  <rule id="2900" level="0">
    <decoded_as>windows-date-format</decoded_as>
    <regex offset="after_parent">startup |status |remove |configure |install |purge |trigproc |installed</regex>
    <description>Dpkg (Debian Package) log.</description>
  </rule>```

**Comment by iasdeoupxe** [comment]
Seems this got broken in https://github.com/ossec/ossec-hids/pull/1037 and pulled in to wazuh-ruleset via https://github.com/wazuh/wazuh-ruleset/pull/94

**Comment by iasdeoupxe** [comment]
Trying to fix this with https://github.com/wazuh/wazuh-ruleset/pull/146

Some remarks:

> typo (regex offset)

Seems this is something decoder specific and not supported for rules at all

> caret before status

This seems to be required as not using the caret would also catch a message like:

``2018-06-23 10:11:35 this is a status message``

and would lead to an wrong event:

```
**Phase 1: Completed pre-decoding.
       full event: '2018-06-23 10:11:35 this is a status message'
       timestamp: '(null)'
       hostname: 'example'
       program_name: '(null)'
       log: '2018-06-23 10:11:35 this is a status message'

**Phase 2: Completed decoding.
       decoder: 'windows-date-format'

**Phase 3: Completed filtering (rules).
       Rule id: '2900'
       Level: '0'
       Description: 'Dpkg (Debian Package) log.'
```

> installed status missing

Seems this is only a "sub" message of "status" so that should be fine as is.

**Comment by SitoRBJ** [comment]
Hello, 

We have made some slight improvements to the regular expressions of the rules and we have based ourselves on the solution given by iasdeoupxe. #148 

Thank you so much for your solution, great job.

Kind regards,

Alfonso Ruiz-Bravo

**Comment by iasdeoupxe** [comment]
Reason for closing: Fixed with https://github.com/wazuh/wazuh-ruleset/pull/172
