### ISSUE TITLE
CIS Policy for Amazon Linux

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-ruleset#150]
Create a rootcheck file to meet the CIS policy for Amazon Linux: https://www.cisecurity.org/benchmark/amazon_linux/.

**Comment by chemamartinez** [comment]
Hi team,

Let me close this issue. The CIS policy for Amazon Linux should be created for SCA instead of rootcheck. It is contemplated at https://github.com/wazuh/wazuh-ruleset/issues/485.

Regards.
