### ISSUE TITLE
Review too generic composite rules

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-ruleset#160]
Some composite rules with too generic conditions can overwrite others rules.

Example:

The rule 40111 will fire whenever any combination of 12 hits on any rules in the authentication_failed group takes place in the same 160 second period. That could prevent the rule 5710 or similar to be fired.

```
  <rule id="40111" level="10" frequency="12" timeframe="160">
    <if_matched_group>authentication_failed</if_matched_group>
    <description>Multiple authentication failures.</description>
    <group>authentication_failures,pci_dss_10.2.4,pci_dss_10.2.5,gpg13_7.1,gpg13_7.8,gdpr_IV_35.7.d,gdpr_IV_32.2,</group>
  </rule>
```

```
<rule id="5712" level="10" frequency="8" timeframe="120" ignore="60">
    <if_matched_sid>5710</if_matched_sid>
    <description>sshd: brute force trying to get access to </description>
    <description>the system.</description>
    <same_source_ip />
    <group>authentication_failures,pci_dss_11.4,pci_dss_10.2.4,pci_dss_10.2.5,gdpr_IV_35.7.d,gdpr_IV_32.2,</group>
</rule>
```

Every composite rule should include the "<same-*>" tag to avoid this situation.

Thanks @branchnetconsulting for reporting it.

**Comment by SitoRBJ** [comment]
Hello,

In the PR #161 we have added the `<same>` field to all the compound rules where possible. 

Kind regards,

Alfonso Ruiz-Bravo
