### ISSUE TITLE
0295-sonicwall_decoders does not work.

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-ruleset#162]
Hi team,

I have been doing a test in order to generate logs coming from SonicWall and does not work properly. I have been testing the logs samples that appear in **0295-sonicwall_decoders.xml**.

The decoder does not extract the fields and does not generate the proper alert with the rules:

```
 full event: 'Jan  3 13:45:36 192.168.5.1 id=firewall sn=000SERIAL time="2007-01-03 14:48:07" 
       fw=1.1.1.1 pri=1 c=32 m=30 msg="Administrator login denied due to bad credentials" n=7 
       src=2.2.2.2:36701:WAN dst=1.1.1.1:50000:WAN'
       timestamp: 'Jan  3 13:45:36'
       hostname: '192.168.5.1'
       program_name: '(null)'
       log: 'id=firewall sn=000SERIAL time="2007-01-03 14:48:07" fw=1.1.1.1 pri=1 c=32 m=30 
       msg="Administrator login denied due to bad credentials" n=7 src=2.2.2.2:36701:WAN 
       dst=1.1.1.1:50000:WAN'

     **Phase 2: Completed decoding.
       decoder: 'sonicwall'


     **Phase 3: Completed filtering (rules).
       Rule id: '20101'
       Level: '6'
       Description: 'IDS event.'
     **Alert to be generated.
```
Regards,

Miguel Casares

**Comment by MaxVerro** [comment]
What "log format" do you use in your sonicwall?

**Comment by MaxVerro** [comment]
Any ETA on this issue? @MiguelCasaresRobles

**Comment by MiguelCasaresRobles** [comment]
Hello @MaxVerro, we are working on update several decoders/rules in wazuh-ruleset at the same time that we are working on the integration of new. This process may take us a time because we have to test it all properly, that is why I can't tell you an estimated date. We hope all will be ready as soon as possible.

Thank you for your interest and support to our Wazuh community. We really appreciated it.

Regards,

Miguel Casares

**Comment by elwali10** [comment]
Hello @MiguelCasaresRobles  @MaxVerro 

I have created a PR https://github.com/wazuh/wazuh-ruleset/pull/274 , Fixing and enhancing this decoder.

I'm closing it, feel free to re-open if you have any suggestions or questions .

Regards,
Wali.k

**Comment by jctello** [comment]
From this conversation: https://groups.google.com/d/topic/wazuh/mR-FIh44DYE/discussion 
I see that sonicwall messages may contain an extra space in the time information for Timezone information. 
I've made an additional commit to PR #274 to also decode these messages
