### ISSUE TITLE
request to add rule to monitor outbound connections

### ISSUE THREAD

**Issue by sonofagl1tch** [wazuh/wazuh-ruleset#176]
Hi team,

I was monitoring one of my hosts while i was attacking it and noticed that I could not find any traces of the data exfiltration that was occuring because there was no rule to monitor outbound connections. 

to do so I have added the below to my ossec.conf file
```xml
<localfile>
    <log_format>full_command</log_format>
    <command>netstat -nputw</command>
    <alias>netstat outbound connections</alias>
    <frequency>30</frequency>
</localfile>
```

and i have created the following custom rule on the wazuh server to generate an alert

```xml
<rule id="100002" level="7">
    <if_sid>530</if_sid>
    <match>ossec: output: 'netstat outbound connections</match>
    <check_diff />
    <description>Listened ports status (netstat nputw) changed (new port opened or closed).</description>
    <group>pci_dss_10.2.7,pci_dss_10.6.1,gpg13_10.1,gdpr_IV_35.7.d,</group>
</rule>
```

I think this configuration and rule should be added to the ruleset by default because without it there is not a current rule to monitor for outbound traffic/connections.

Thank you for your time,
me

**Comment by elwali10** [comment]
Hello @sonofagl1tch 

Thanks for sharing it with us, I've made a PR for this to be included in newer version.

We appreciate your contribution.

Regards,
Wali.k
