### ISSUE TITLE
rule huawei

### ISSUE THREAD

**Issue by nurhambali** [wazuh/wazuh-ruleset#182]
hi, 
how to add rule huawei send to wazuh?
how to create rule huawei in wazuh?

**Comment by elwali10** [comment]
Hello @nurhambali 

I believe this issue is related to this thread https://groups.google.com/forum/#!searchin/wazuh/huawei$20%7Csort:date/wazuh/8l5siGpXrBs/cNEiwZTsEgAJ 

I'm closing it unless you have further request.

regards,
