### ISSUE TITLE
Improve AWS rules

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-ruleset#194]
AWS rules need to be redesigned:

- Generic rule: ```<field name="integration">aws</field>```
- Generic rule for Cloudtrail: ```<field name="aws.source">cloudtrail</field>```
- Specific rules for Cloudtrail: ```<list field="aws.eventName" lookup="match_key">etc/lists/amazon/aws-eventnames</list>```
- Generic rule for GuardDuty: ```<field name="aws.source">guardduty</field>```
- Specific rules for GuardDuty
- Generic rule for Macie: ```<field name="aws.source">macie</field>```
- Specific rules for Macie
- ...
- Generic rule for any service
- Specific rules for any service

**Comment by Lopuiz** [comment]
This issue is solved in this [PR](https://github.com/wazuh/wazuh-ruleset/pull/174)
