### ISSUE TITLE
rule 2833 "Root's crontab entry changed." seems reversed

### ISSUE THREAD

**Issue by parena1979** [wazuh/wazuh-ruleset#202]
A log entry like this:
`Sep 26 14:38:32 hostname crontab[4287]: (root) REPLACE (user)`
results in rule 2833 to be triggered, which is "Root's crontab entry changed."

However, this is a case where root replaced a user's crontab entry. The match should not be "^(root)" but 
"(root)$" in my opinion.

This would also give necessity to an extra rule perhaps, for any other user's crontab that was changed.

**Comment by elwali10** [comment]
Hello @parena1979 

If i understand well, you are looking for another rule to be triggered when another user (Not root) has been replaced, if it is the case we already have one, as you can see below : 

```
Sep 26 14:38:32 hostname crontab[4287]: (foo1) REPLACE (foo2)


**Phase 1: Completed pre-decoding.
       full event: 'Sep 26 14:38:32 hostname crontab[4287]: (foo1) REPLACE (foo2)'
       timestamp: 'Sep 26 14:38:32'
       hostname: 'hostname'
       program_name: 'crontab'
       log: '(foo1) REPLACE (foo2)'

**Phase 2: Completed decoding.
       No decoder matched.

**Phase 3: Completed filtering (rules).
       Rule id: '2832'
       Level: '5'
       Description: 'Crontab entry changed.'
**Alert to be generated.
```
in that case we are giving the level 5, as we are deeming that Only Root user changes would need a higher level alert which is 8 and a specific description for it, all other users (foo1 to foo2 in my example )replaced operations would has **Crontab entry changed** as description .

Hope this answer your question,

Regards,
Wali.k

**Comment by parena1979** [comment]
Hiya,

Actually, what I mean is this: "(root) REPLACE (user)" -> this **means** root replaced a user's crontab entry. But wazuh triggers rule 2833, which is "Root's crontab entry changed." which is wrong.

**Comment by elwali10** [comment]
Hello @parena1979 

Sorry i didn't get it in the first hand.

Indeed this is a false positive, I've just modified the rule in my local Environment and the result as you can see : 


```
Sep 26 14:38:32 hostname crontab[4287]: (root) REPLACE (user)


**Phase 1: Completed pre-decoding.
       full event: 'Sep 26 14:38:32 hostname crontab[4287]: (root) REPLACE (user)'
       timestamp: 'Sep 26 14:38:32'
       hostname: 'hostname'
       program_name: 'crontab'
       log: '(root) REPLACE (user)'

**Phase 2: Completed decoding.
       No decoder matched.

**Phase 3: Completed filtering (rules).
       Rule id: '2832'
       Level: '5'
       Description: 'Crontab entry changed.'
**Alert to be generated.


Sep 26 14:38:32 hostname crontab[4287]: (user) REPLACE (root)


**Phase 1: Completed pre-decoding.
       full event: 'Sep 26 14:38:32 hostname crontab[4287]: (user) REPLACE (root)'
       timestamp: 'Sep 26 14:38:32'
       hostname: 'hostname'
       program_name: 'crontab'
       log: '(user) REPLACE (root)'

**Phase 2: Completed decoding.
       No decoder matched.

**Phase 3: Completed filtering (rules).
       Rule id: '2833'
       Level: '8'
       Description: 'Root's crontab entry changed.'
**Alert to be generated.

```

I will include this change  in a PR to our ruleset.
Thanks for reporting it.
Wali.k
