### ISSUE TITLE
Custom rules for Suricata

### ISSUE THREAD

**Issue by camaro23** [wazuh/wazuh-ruleset#203]
Hello,

I am running a docker image of Suricata and I am having trouble having Wazuh manager interpret the rules. The eve.json log for Suricata is being forwarded to the Wazuh manger successfully via a wazuh agent running on the Suricata box. However, when I generate a alert in for Suricata, the local ELK stack displays the rules but the Wazuh manager does not interpret them. Can anyone offer guidance? 

Thanks

**Comment by LFBernardo** [comment]
have a read through this group post

https://groups.google.com/forum/#!topic/wazuh/YpV-JEP4_F0

It may help you with the ingestion of Suricata logs

**Comment by elwali10** [comment]
Hello @camaro23 

As the logs  that being forwarded by suritcata are Json like, so Wazuh Manager will luckily interpreted them as Json.

You may want to take a look at this configuration for Suricata Logs in our documentation here : https://documentation.wazuh.com/3.x/user-manual/ruleset/json-decoder.html?highlight=plugin_decoder

Also in this Thread in our mailing list : https://groups.google.com/forum/#!searchin/wazuh/suricata$20logs%7Csort:date/wazuh/sTYe6zndT64/ajKDlVX6EAAJ   , It is well described how to deal with them.

Hope this helps.
regards,
