### ISSUE TITLE
AWS VPC Flowlog Issues

### ISSUE THREAD

**Issue by harbinc** [wazuh/wazuh-ruleset#204]
When I run ./getawslog.py -b bucketname -d -j -D -l /var/log/amazon.log I get the following? And I am not seeing ANY alerts for AWS in Wazuh. Looks like maybe the flowlogs are in the wrong format. Is this the real issue? Because I am not seeing how to make the flowlogs in JSON format?

+++ Found new log:  869065819144_vpcflowlogs_us-east-1_fl-0aa1a90b428bc0321_20181004T2115Z_b522ac4a.log.gz
Traceback (most recent call last):
  File "./getawslog.py", line 140, in <module>
    main(sys.argv[1:])
  File "./getawslog.py", line 112, in main
    j = json.load(data)
  File "/usr/lib64/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by Lopuiz** [comment]
Hi! @harbinc

Sorry to answer so late. I don't know if it'll help now but I'll tell you what I think might be going on. 
First, i believe that the script you are using is deprecated and has now been replaced by this [one](https://documentation.wazuh.com/current/amazon/index.html).

Also, VPC Flow events are saved in csv so using a JSON parser won't work. This is the guide to [VPC monitoring](https://documentation.wazuh.com/current/amazon/services/vpc.html)

If you have any other questions let us know.

Best regards, Eva.

**Comment by Lopuiz** [comment]
Hi @harbinc,
I'll close this issue. If you have any other questions let us know we promised you to answer at the time.
Kind regards, Eva
