### ISSUE TITLE
Cisco Accesslog and firewall rules doesn't match

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-ruleset#208]
Hi team,
while testing some rules, I noticed the decoder cisco-ios-acl can't trigger the firewall drop alerts.

This is a sample of cisco-acl log:
```
3924923: *Oct  6 03:32:04.114 gmt: %SEC-6-IPACCESSLOGP: list bcv_out denied tcp 10.0.3.100(50150) -> 192.168.216.1(443), 1 packet 
```

Actually is matching rule 4100
https://github.com/wazuh/wazuh-ruleset/blob/09b105a9db2436634b2723383202804b5ae732bd/rules/0060-firewall_rules.xml#L9-L13

And I think this should trigger the drop alert, because Cisco devices don't have the ACCEPT, REJECT, DROP actions.
Instead, they have "deny" and "permit"
So the equivalent to DROP would be "deny", and it doesn't match the rule. 

https://github.com/wazuh/wazuh-ruleset/blob/09b105a9db2436634b2723383202804b5ae732bd/rules/0060-firewall_rules.xml#L15-L24

Best regards,
Miguel

**Comment by migruiz4** [comment]
Actually, I'm not sure if the idea is to match the Cisco IOS rule or the firewall DROP rule.
But there is a problem with the second option and current rules because access control policy for Cisco IOS can only "permit" or "deny". 

So ``<action>DROP</action>`` won't work here.

https://github.com/wazuh/wazuh-ruleset/blob/09b105a9db2436634b2723383202804b5ae732bd/rules/0060-firewall_rules.xml#L18-L24

**Comment by fabamatic** [comment]
Sample log currently matches to rule 4716 - Cisco IOS informational message - IPACCESSLOGP.  A rule looking for "denied" string may be added

**Comment by JavierBejMen** [comment]
This will be handle on the outgoing cisco rework in https://github.com/wazuh/feed
