### ISSUE TITLE
Cisco IOS rules level

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-ruleset#210]
Hi team,
I've seen the level for the Cisco rules doesn't fit properly the level of the log.

The Cisco logs include in their name the [severity level](https://www.cisco.com/c/en/us/td/docs/routers/access/wireless/software/guide/SysMsgLogging.html#wp1054858) of the alerts, as you can see [here](https://www.cisco.com/c/en/us/td/docs/routers/access/wireless/software/guide/SysMsgLogging.html#wp1054485)

The severity level goes from 0 (emergency) to 7 (debug).

https://github.com/wazuh/wazuh-ruleset/blob/398d02dd079157c8599d4892c6c81ec797647d76/rules/0075-cisco-ios_rules.xml#L15-L66

When looking at the rules, I found the current severity / alert level looks like this.

| Level keyword  | Severity | Alert Level |
|---------------------|------------|--------------|
| emergencies     | 0            | 9            |
| alerts                 | 1            | 5              |
| critical                | 2            | 5              |
| errors                 | 3            | 4             |
| warnings            | 4            | 4              |
| ...                       |  5-7       |  0               |

I suggest modifying those levels to fit better the severity.
For example:

| Level keyword  | Severity | Alert Level |
|---------------------|------------|--------------|
| emergencies     | 0            | 10            |
| alerts                 | 1            | 7              |
| critical                | 2            | 5              |
| errors                 | 3            | 4             |
| warnings            | 4            | 3              |

Best regards,
Miguel R.

**Comment by 72nomada** [comment]
Closing this, Cisco decoders and rules rework will be done
