### ISSUE TITLE
Update the openldap-bind decoder

### ISSUE THREAD

**Issue by fjavierc** [wazuh/wazuh-ruleset#214]
Hello;

I was having problems with the "openldap-bind" decoder because I could not extract the username with which the BIND was made since in my organization, the user names of the openldap include the "." ( a dot ). After several tests I have seen that the decoder extracts this value using the regular expression "(\w+)" which, apparently, does not include this punctuation mark (https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/regex.html):

Example:
````
2018/10/12 13:38:00 ossec-testrule: INFO: Started (pid: 10318).
ossec-testrule: Type one log per line.

Oct 12 08:09:43 ldapserver01 slapd[28658]: conn=47393 op=0 BIND dn="uid=NOMBRE.APELLIDO,o=usuarios,o=organizacion,c=es" method=128

**Phase 1: Completed pre-decoding.
       full event: 'Oct 12 08:09:43 ldapserver01 slapd[28658]: conn=47393 op=0 BIND dn="uid=NOMBRE.APELLIDO,o=usuarios,o=organizacion,c=es" method=128'
       timestamp: 'Oct 12 08:09:43'
       hostname: 'ldapserver01'
       program_name: 'slapd'
       log: 'conn=47393 op=0 BIND dn="uid=NOMBRE.APELLIDO,o=usuarios,o=organizacion,c=es" method=128'

**Phase 2: Completed decoding.
       decoder: 'openldap'

**ACCUMULATOR: LEVEL UP!!**

**Phase 3: Completed filtering (rules).
       Rule id: '2507'
       Level: '0'
       Description: 'OpenLDAP group.'
````

The solution has been to modify the "openldap-bind" decoder so that the expression "(\w+)" is replaced by "(\S+)", leaving as follows:

**0185-openldap_decoders.xml**
````
<!--
  -  OpenLDAP decoders
  -  Author: Daniel Cid.
  -  Copyright (C) 2009 Trend Micro Inc.
  -  Updated by Wazuh, Inc. <support@wazuh.com>.
  -  This program is a free software; you can redistribute it and/or modify it under the terms of GPLv2.
-->

[ ...]

<decoder name="openldap-bind">
    <parent>openldap</parent>
    <prematch>BIND </prematch>
    <!-- <regex>^conn=(\d+) op=\d+ BIND dn="\w+=(\w+),</regex>	// OLD -->
     
          <regex>^conn=(\d+) op=\d+ BIND dn="\w+=(\S+),</regex>

    <order>id, dstuser</order>
    <accumulate/>
</decoder>

[ ... ]
````

Now, I can get the 'id' and 'dstuser':
````
2018/10/12 13:38:50 ossec-testrule: INFO: Started (pid: 10329).
ossec-testrule: Type one log per line.

Oct 12 08:09:43 ldapserver01 slapd[28658]: conn=47393 op=0 BIND dn="uid=NOMBRE.APELLIDO,o=usuarios,o=organizacion,c=es" method=128

**Phase 1: Completed pre-decoding.
       full event: 'Oct 12 08:09:43 ldapserver01 slapd[28658]: conn=47393 op=0 BIND dn="uid=NOMBRE.APELLIDO,o=usuarios,o=organizacion,c=es" method=128'
       timestamp: 'Oct 12 08:09:43'
       hostname: 'ldapserver01'
       program_name: 'slapd'
       log: 'conn=47393 op=0 BIND dn="uid=NOMBRE.APELLIDO,o=usuarios,o=organizacion,c=es" method=128'

**Phase 2: Completed decoding.
       decoder: 'openldap'
       id: '47393'
       dstuser: 'NOMBRE.APELLIDO'

**ACCUMULATOR: LEVEL UP!!**

**Phase 3: Completed filtering (rules).
       Rule id: '2507'
       Level: '0'
       Description: 'OpenLDAP group.'
````

I think I'm not the only one who uses this nomenclature when defining user names (firstname.lastname, firstname.lastname1.lastname2) in OpenLDAP and I do not know if there are more users who do the same thing and that the "openldap-bind" decoder is not working properly for them so they do not get the _id_ of the connection or the _dstuser_.

What do you think about updating this decoder (openldap-bind) in your code so that those who use usernames containing a dot "."  do not have to be creating new local decoders?

 Well, it's just a suggestion.

Thank you !!

**Comment by elwali10** [comment]
Hello @fjavierc,

Thanks for your suggestion, I'm including this change to this PR : https://github.com/wazuh/wazuh-ruleset/pull/271, in order to have it in newer ruleset.

Thanks again for your contributions.

Regards,
Wali.k
