### ISSUE TITLE
Is it possible to use variables or data like account_name for Same_{insert rule syntax} alert rules?

### ISSUE THREAD

**Issue by lyoeril** [wazuh/wazuh-ruleset#233]
Hi,

I hope this is the right place to ask a question!

I'm trying to implement a feature which is supposed to trigger as soon as a single machine or account failed authenticating 10 ten times before succeeding. It is working... but it takes all authentications. (not just Administrator for example)
`
<rule id="100620" level="8">
    <if_sid>18107</if_sid>
    <field name="logon_type">^2$|^10$|^11$</field>
    <field name="account_name">^Administrator|^Service</field>
    <description>Windows Logon Success with Administrator Account!</description>
    <group>authentication_success,pci_dss_10.2.5,gpg13_7.1,gpg13_7.2,gdpr_IV_32.2,</group>
  </rule>
`

`
  <rule id="100630" frequency="10" timeframe="3600" level="15">
    <if_matched_sid>18130</if_matched_sid>
    <if_sid>18107, 100620</if_sid>
    <field name="account_name">^Administrator|^Service</field>
    <description>Windows (Administrator/Service) Logon Success after 10 failed attempts!</description>
    <group>authentication_success,pci_dss_10.2.5,gpg13_7.1,gpg13_7.2,gdpr_IV_32.2,</group>
  </rule>
`
  

i've tried using rule syntax like <same_user> and <same_source_ip>.
I can't get this working, because data.dstuser == (no user) and data.srcip == "127.0.0.1"

Is it possible to use other field names like"account_name" or "agent.name" the same way "<same_user>" or "<same_location>" does this?

**Comment by elwali10** [comment]
Hello @lyoeril 

I'm guessing that you can use the <match> property and Try in to match with The Administrator : https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#match

Here is our mailing list group : https://groups.google.com/forum/#!forum/wazuh, in that way you will get prompt answers.

Hope this helps,
Regards
