### ISSUE TITLE
Log snippet for authentication failures of ZNC IRC bouncer

### ISSUE THREAD

**Issue by iasdeoupxe** [wazuh/wazuh-ruleset#234]
Running a ZNC IRC bouncer (https://wiki.znc.in) with the adminlog module (https://wiki.znc.in/Adminlog) enabled logs the following entries for failed logins into a file (/znc_path/moddata/adminlog/znc.log):

```
[2018-11-11 00:30:29] [] failed to login from 192.168.0.10
```

As this is not a wide spread software its probably not worth to write separate decoders and rules for this and i would like to just catch it with the rule 2501 of 0020-syslog_rules.xml:

```
    <match>Failed to authenticate user</match>
```

replace with:

```
    <match>Failed to authenticate user|failed to login from</match>
```

But running ossec-logtest is just ending up with the following rule:

```
**Phase 1: Completed pre-decoding.
       full event: '[2018-11-11 00:30:29] [] failed to login from 192.168.0.10'
       timestamp: '(null)'
       hostname: 'myhost'
       program_name: '(null)'
       log: '[2018-11-11 00:30:29] [] failed to login from 192.168.0.10'

**Phase 2: Completed decoding.
       No decoder matched.

**Phase 3: Completed filtering (rules).
       Rule id: '1002'
       Level: '2'
       Description: 'Unknown problem somewhere in the system.'
```

Why is only rule 1002 applied here and not the better matching 2501?

I would like to submit a new PR for this log pattern and it would be great if some one more familiar with the rules could give an explanation for this.

**Comment by elwali10** [comment]
Hello @iasdeoupxe 

The explanation for having the rule `1002` triggered is  the word `**failed** has been matched and no decoder has been detected, as you can see below i'm writing simply the word **failed** in our logtest  : 


```
failed


**Phase 1: Completed pre-decoding.
       full event: 'failed'
       timestamp: '(null)'
       hostname: 'localhost'
       program_name: '(null)'
       log: 'failed'

**Phase 2: Completed decoding.
       No decoder matched.

**Phase 3: Completed filtering (rules).
       Rule id: '1002'
       Level: '2'
       Description: 'Unknown problem somewhere in the system.'
```
So this log that you have from ZNC IRC bouncer would need its own decoder as for the moment no decoder in our ruleset is detecting this pattern.

I hope that explains the case.

Regards,
Wali.k
