### ISSUE TITLE
Make system_audit_ssh.txt use "sshd -T" command output

### ISSUE THREAD

**Issue by rectalogic** [wazuh/wazuh-ruleset#251]
wazuh sshd rules in https://github.com/wazuh/wazuh-ruleset/blob/master/rootchecks/system_audit_ssh.txt are grepping /etc/ssh/sshd_config, but this ignores default values.

e.g. the default value for PermitEmptyPasswords is no, and my stock sshd_config (Ubuntu 18.04) has
```
#PermitEmptyPasswords no
```
This causes wazuh to generate a false alert because it greps for an uncommented `PermitEmptyPasswords no`.

Instead of grepping the config file, can wazuh grep the output of `sshd -T` and examine the actual runtime configuration?

```
$ sudo sshd -T | grep -i permitemptypasswords
permitemptypasswords no
```

**Comment by TJOSERAFAEL** [comment]
asd
