### ISSUE TITLE
Map Rules to MITRE ATT&CK framework

### ISSUE THREAD

**Issue by Hestat** [wazuh/wazuh-ruleset#258]
Wonder if its in any phase of planning to review the OSSEC ruleset and map them to the T codes in the MITRE ATT&CK framework.

https://attack.mitre.org/

**Comment by elwali10** [comment]
Hello @Hestat 

About the reviewing part we continually keep updating and enriching our ruleset. 
Would it be possible to give more hints about what you mean by mapping them to the T code ?

**Comment by Hestat** [comment]
Thanks I certainly can. In the MITRE ATT&CK frame work each technique is given a specific code so that you can quickly tag events based on the techniques used. Here's an example from my logs.

![mitre1](https://user-images.githubusercontent.com/22892300/53772848-00ce4980-3eb6-11e9-861f-d9b9e67493bb.PNG)
This shows a common web attack which may fall into a few categories. For example the following code T1100 and T1064:
![mitre2](https://user-images.githubusercontent.com/22892300/53772994-7d612800-3eb6-11e9-93d1-3b1b9cb3384f.PNG)

![mitre3](https://user-images.githubusercontent.com/22892300/53772999-82be7280-3eb6-11e9-8e5a-8e3440706b41.PNG)

**Comment by elwali10** [comment]
Hello @Hestat 

I apologize for the late reply and Thanks for the suggestion.

We have started working on that direction and this can be tracked in this issue https://github.com/wazuh/wazuh/issues/3711#issuecomment-514690265 .

I'm closing this issue for now, Please feel free re-opening it if any further information should be provided.

Regards.
Wali
