### ISSUE TITLE
PIX/ASA decoder disabled by Cisco IOS decoder

### ISSUE THREAD

**Issue by candlerb** [wazuh/wazuh-ruleset#269]
`0210-pix_decoders.xml` are not functioning. They match messages starting `%PIX-`, `%ASA-` or `%FWSM-` but they are neutered by `0065-cisco-ios_decoders.xml` which matches anything starting `%`

Options are:

1. Move 0210-pix_decoders.xml to 0062-cisco-pix_decoders.xml; or
2. Make the IOS matches more specific. They would need to match at least %IOS, %IOSXE, %SYS, %SEC, %IPS, there may be other patterns required.

So I think option 1 is the safer.

I will make a PR for this, as I need ASA decoding to work.

**Comment by sergiospa** [comment]
Hi candlerb,

You could solve your problem by following the next steps:

1) Move `0210-pix_decoders.xml` to your local decoders directory and rename it, in order for the custom decoder to match before `0065-cisco-ios_decoders.xml`. 

`cp /var/ossec/ruleset/decoders/0210-pix_decoders.xml /var/ossec/etc/decoders/0064-pix_decoders.xml`

2)  Exclude the original decoder file `var/ossec/ruleset/decoders/0210-pix_decoders.xml` from the OSSEC loading list. In `/var/ossec/etc/ossec.conf`, add the `decoder_exclude` line, as follows:

`  <ruleset>
    
    <decoder_dir>ruleset/decoders</decoder_dir>
    <rule_dir>ruleset/rules</rule_dir>
    <rule_exclude>0215-policy_rules.xml</rule_exclude>
    <list>etc/lists/audit-keys</list>
    <list>etc/lists/amazon/aws-eventnames</list>
    <list>etc/lists/security-eventchannel</list>

    <list>etc/lists/ssh-watch-list</list>

    
    <decoder_dir>etc/decoders</decoder_dir>
    <rule_dir>etc/rules</rule_dir>
    <decoder_exclude>ruleset/decoders/0210-pix_decoders.xml</decoder_exclude>
  </ruleset>
`
Then, restart your manager and your problem should be fixed. Do not hesitate to ask if you have any more trouble.

Best regards,
Sergio.

**Comment by candlerb** [comment]
Of course: but what I am trying to say is that `0210-pix_decoders` is completely broken at the moment.  It never matches anything, because everything it wants to match is already captured by `0065-cisco-ios_decoders`.

That's why I made PR #270, to try and fix this problem.  Ideally, all rules would come with test cases, so the PR includes some for it.

Alternatively, you could just delete `0210-pix_decoders` since it's not doing anything useful at the moment.  I think it's confusing for users to see rules which look like they *should* work, then have to work out why they don't.

**Comment by MiguelCasaresRobles** [comment]
Hello team, 

I can confirm this behavior. this is an example given in the decoder file: `%ASA-2-106001: Inbound TCP connection denied from 1.2.3.4/1234 to 213.207.99.248/445 flags SYN on interface outside (Message repeated 2 times)`

```

**Phase 1: Completed pre-decoding.
       full event: '%ASA-2-106001: Inbound TCP connection denied from 1.2.3.4/1234 to 213.207.99.248/445 flags SYN on interface outside (Message repeated 2 times)'
       timestamp: '(null)'
       hostname: 'ip-10-160-16-14'
       program_name: '(null)'
       log: '%ASA-2-106001: Inbound TCP connection denied from 1.2.3.4/1234 to 213.207.99.248/445 flags SYN on interface outside (Message repeated 2 times)'

**Phase 2: Completed decoding.
       decoder: 'cisco-ios'
       id: '%ASA-2-106001'

**Phase 3: Completed filtering (rules).
       Rule id: '4712'
       Level: '5'
       Description: 'Cisco IOS critical message.'
**Alert to be generated.
```

As you can see is not decoding all the fields and the rule is captured by Cisco instead of PIX.

**Comment by 72nomada** [comment]
Closing this, it is manage by "wazuh-ruleset: Cisco rules and decoders improvements"  #7278

**Comment by candlerb** [comment]
For reference: that's actually https://github.com/wazuh/wazuh/issues/7278 - and #402 in this repo. Thanks.
