### ISSUE TITLE
Unable to alert on windows logon brute force attack(<same_user /> rule not working)

### ISSUE THREAD

**Issue by shahmilan34** [wazuh/wazuh-ruleset#281]
## Rule to detect brute force attack:
```xml
<group name="windows,">
        <rule id="100010" level="10" frequency="8" timeframe="240" >
                <if_matched_sid>20030</if_matched_sid>
                 <same_user />
                <description>Brute Force Attack ,Windows Multiple Failed login attemps</description>
                <group>win_authentication_failed,</group>
        </rule>
</group>
```
## Windows Agent config:
wazuh-agent v3.8.2
windows 8

## Wazuh-Manager config:
centos 7
wazuh-manager v3.8.2

Rule works if <same_user /> tag removed.

**Comment by cristgl** [comment]
Hello @shahmilan34,

As this is a duplicated issue with https://github.com/wazuh/wazuh/issues/2524, I have answered your question in the mencioned one. Let me close this issue.

Best regards,
Cristina
