### ISSUE TITLE
Add Decoder support for Windows sysmon event ID 9 - 15

### ISSUE THREAD

**Issue by xkilian** [wazuh/wazuh-ruleset#29]
New event types are now available in Sysmon 5.

**Comment by jesuslinares** [comment]
Thanks for letting us know. I will try to create them soon.

Regards.

**Comment by jesuslinares** [comment]
We are using dynamic fields for Sysmon events and there are decoders for 2 new events: 11 and 15: https://github.com/wazuh/wazuh-ruleset/commit/4e3439b68623e7097c1daf80ef05a6f9445e7133 https://github.com/wazuh/wazuh-ruleset/commit/d09238b3a072f048720b9a402cb85e5c5e8117e7.
