### ISSUE TITLE
Rework for Docker rules

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-ruleset#294]
Some of the events from the Docker listener are no generating the correct rule. For example, the `docker exec` command is triggering the rule [87903](https://github.com/wazuh/wazuh-ruleset/blob/3.9/rules/0560-docker_integration_rules.xml#L32).

It is necessary to review what events and rules are generated in each case to fix and enrich the Docker ruleset.

**Comment by cristgl** [comment]
| Docker command | Rule ID | Event | Alert |
| - | - | - | - |
| docker create | 87901 | status: create | Container created |
| docker start | 87903 | status: start | Container started |
| docker run | 87901, 87903 | status: create, start | Container started, Container created |
| docker exec | 87901, 87903 | status: create, start | Container started, Container created |
| docker stop | 87902, 87904 | status: kill, die, stop, destroy | Container stopped, Container destroyed |
| docker restart | 87903, 87904 | status: kill, die, stop, start, restart | Container stopped, Container started |
| docker volume create | x | action: create | x |
| docker volume rm | x | action: destroy | x |
| docker pause | 87905 | status: pause | Container paused |
| docker unpause | 87906 | status: unpause | Container unpaused |
| docker attach | x | status: attach | x |
| docker commit | 87905, 87906 | status: pause, tag, commit, unpause | Container paused, Container unpaused |
| docker cp | x | status: extract-to-dir, status: archive-path | x |
| docker rmi | x | status: untag, delete | x |
| docker rm | 87902 | status: kill, die, destroy | Container destroyed |
| docker update | x | status: update | x |
| docker top | x | status: top | x |
