### ISSUE TITLE
cis rules for debian 9

### ISSUE THREAD

**Issue by tmanninger** [wazuh/wazuh-ruleset#297]
Hi,

there are cis rules for debian 9 available:
https://www.cisecurity.org/benchmark/debian_linux/

Can you implement these rules?

**Comment by Zenidd** [comment]
Hello @tmanninger,

First of all, sorry for the late reply.

We are going to review these rules and study if we are including in our Wazuh-ruleset. Thanks for letting us know and helping us to improve our project.

<br></br>
Best regards,

Juan Pablo Sáez.

**Comment by Lopuiz** [comment]
Hi @tmanninger,

First, sorry for the late response.

we are improving our CIS policy for SCA.
You can follow these issues:
* [373](https://github.com/wazuh/wazuh-ruleset/issues/373)
* [411](https://github.com/wazuh/wazuh-ruleset/issues/411)
* [404](https://github.com/wazuh/wazuh-ruleset/issues/404)

A CIS policy already exists for Debian 9:
https://github.com/wazuh/wazuh-ruleset/blob/master/sca/debian/cis_debian_linux_rcl.yml

We will continue to improve and expand our rules constantly

Kind regards, Eva

**Comment by chemamartinez** [comment]
Hi @tmanninger,

It has been included two particular policies for Debian 9 ([cis_debian9_L1.yml](https://github.com/wazuh/wazuh-ruleset/blob/3.10/sca/debian/cis_debian9_L1.yml) and [cis_debian9_L2.yml](https://github.com/wazuh/wazuh-ruleset/blob/3.10/sca/debian/cis_debian9_L2.yml)) and will be available in the next released version, v3.10.

In addition, we are working on SCA policies continuously. One of our goals is to extend the supported policies ASAP.

Regards.
