### ISSUE TITLE
Rule 18107 may be triggering more times than necessary

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh-ruleset#298]
This alert is triggered by event 4624, which appears each time a login is requested. This includes the multiple user changes requests that Windows processes perform.

In other words, we can have this alert without having logged in or executed something with permissions from another computer user.

We can make a new rule that derives from this and refers exclusively to login in physical users. 

A way to differentiate these events may be the fact that the TargetDomainName field coincides with the WorkstationName.

**Comment by crolopez** [comment]
Related to https://github.com/wazuh/wazuh-ruleset/issues/295.

**Comment by cristgl** [comment]
We will keep working on #295
