### ISSUE TITLE
Ignored URLs for the web attacks

### ISSUE THREAD

**Issue by jcesarstef** [wazuh/wazuh-ruleset#30]
https://github.com/wazuh/wazuh-ruleset/blob/master/rules/0245-web_rules.xml#L91-L95

I dont understand why this would be ignored.

Example of real world use:
https://packetstormsecurity.com/files/141082/joomlamusiccollection303-sql.txt

**Comment by snaow** [comment]
Hi @jcesarstef,

I think that rules is mainly created to avoid false positives, we don't want OSSEC to alert and label as "attack" something is not.
Still, I think you are right, rule 31107 will only trigger if 31103, 31104 or 31105 match, those rules are strictly related to MySQL Injections or XSS attacks, so I can't see a reason to ignore 31107 matches.
Maybe we should more strict on the URL matches for 31103, then remove 31107.

Please let us review the rules and we will let you know in case we modified them, also feel free to send us a PR so we can study your solution/approach.

Best regards,
Pedro.

**Comment by jcesarstef** [comment]
Hello snaow.
Thanks for answering.
It's the first time i do this. Please check if is correct.

Regards,
Julio Cesar Stefanutto.

**Comment by jesuslinares** [comment]
Hi @jcesarstef ,

that rule was added in https://github.com/ossec/ossec-hids/commit/26cdaa68ba6c79e3e8a4e2f176e49bb6d6f692ae#diff-84cf3f9c656436eec9fb9bdb11993cb9.

The comment says:

> If your site have a search engine, you may need to ignore it in here

So, it seems it were some false postives with search engines.

If we review the rules:

```
<rule id="31103" level="6">
    <if_sid>31100,31108</if_sid>
    <url>=select%20|select+|insert%20|%20from%20|%20where%20|union%20|</url>
    <url>union+|where+|null,null|xp_cmdshell</url>
    <description>SQL injection attempt.</description>
    <group>attack,sql_injection,pci_dss_6.5,pci_dss_11.4,pci_dss_6.5.1,</group>
</rule>

<rule id="31104" level="6">
    <if_sid>31100</if_sid>
    <!-- Attempt to do directory transversal, simple sql injections,
    -  or access to the etc or bin directory (unix). -->
    <url>%027|%00|%01|%7f|%2E%2E|%0A|%0D|../..|..\..|echo;|</url>
    <url>cmd.exe|root.exe|_mem_bin|msadc|/winnt/|/boot.ini|</url>
    <url>/x90/|default.ida|/sumthin|nsiislog.dll|chmod%|wget%|cd%20|</url>
    <url>exec%20|../..//|%5C../%5C|././././|2e%2e%5c%2e|\x5C\x5C</url>
    <description>Common web attack.</description>
    <group>attack,pci_dss_6.5,pci_dss_11.4,pci_dss_6.5.1,</group>
</rule>

<rule id="31105" level="6">
    <if_sid>31100</if_sid>
    <url>%3Cscript|%3C%2Fscript|script>|script%3E|SRC=javascript|IMG%20|</url>
    <url>%20ONLOAD=|INPUT%20|iframe%20</url>
    <description>XSS (Cross Site Scripting) attempt.</description>
    <group>attack,pci_dss_6.5,pci_dss_11.4,pci_dss_6.5.7,</group>
</rule>

<!-- If your site have a search engine, you may need to ignore
- it in here.
-->
<rule id="31107" level="0">
    <if_sid>31103, 31104, 31105</if_sid>
    <url>^/search.php?search=|^/index.php?searchword=</url>
    <description>Ignored URLs for the web attacks</description>
</rule>
```
A search of " from " (/search.php?search=%20from%20) will trigger the rule 31103 if the rule 31107 doesn't exist but it seems a valid query.

On the other hand, a search of _xp_cmdshell_ must trigger an alert.

We need to improve this, but I don't know yet how to do it without generating  false positives.

Thanks.
Regards.
