### ISSUE TITLE
Create rules for the Windows Application channel

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-ruleset#310]
As the same way as the System and Security channels, the events read by the Eventchannel log collector and coming from the Application channel should be provided of a ruleset. This is necessary to be able to set the Eventchannel source by default in Windows agents for that channel.

**Comment by cristgl** [comment]
Working at branch `3.9-add-winapp-rules`.

The rules added have been obtained from events generated at a Windows 8 system. A lot of systems remain to be checked as the channel needs a whole ruleset (at least Windows 10, Windows Server 2019, Windows XP and Windows Vista).

**Comment by cristgl** [comment]
Keep working on the branch mentioned in the comment below.
Added rules for events of the next provider names:

- .NET Runtime
- Microsoft-Windows-Defrag
- Windows Error Reporting
- MsiInstaller
- LocationNotifications
- Microsoft-Windows-Security-SPP
- Application Hang
- Microsoft-Windows-Search
- VSS
- System Restore
- Application Error
- Microsoft-Windows-WMI
- Microsoft-Windows-EventSystem
- Desktop Window Manager
- Microsoft-Windows-Winlogon
- Microsoft-Windows-User Profiles Service
- User Profile
- ESENT
- Microsoft-Windows-CEIP
- Microsoft-Windows-CAPI2
- Microsoft-Windows-MSDTC

Some events of initializing services yet remain.

**Comment by cristgl** [comment]
I have added several new rules for the provider names written above and for these new ones:
- Browser
- DNSCache
- Disk
- EventCreate
- Microsoft-Windows-EventCollector
- Application Management
- Microsoft-Windows-UserModePowerService
- Microsoft-Windows-LocationProvider

I have also been testing the new rules on a Windows 8 system. It is important to test if any rule floods in a concrete system and check out the rules' description. The updated rules have been uploaded to the branch `3.9-add-winapp-rules`.
