### ISSUE TITLE
The event 'docker pull unauthorized' is not generating any alert

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-ruleset#315]
When performing an unauthorized action on Docker, there is logged some events in `/var/log/message` or `/var/log/syslog` as the following ones:

```
Mar  8 14:47:42 localhost dockerd: time="2019-03-08T14:47:42.761865519Z" level=warning msg="failed to upload schema2 manifest: errors:\ndenied: requested
access to the resource is denied\nunauthorized: authentication required\n - falling back to schema1"
Mar  8 14:47:43 localhost dockerd: time="2019-03-08T14:47:43.938569429Z" level=error msg="Not continuing with push after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
```

They should fire the rule 86005:

```
<rule id="86005" level="4">
        <if_sid>86003</if_sid>
        <match>unauthorized</match>
        <description>Docker: Error - unauthorized action</description>
        <group>docker-error,gdpr_IV_35.7.d,</group>
</rule>
```

Located here: 
https://github.com/wazuh/wazuh-ruleset/blob/master/rules/0455-docker_rules.xml#L61-L66

However, no alert appears when those events are logged.

**Comment by DaveVG1** [comment]
Summary
---
- I've managed to reproduce the error.
- Executing `ossec-logtest` with the log `time="2019-03-08T14:47:43.938569429Z" level=error msg="Not continuing with push after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"` works well. There must be something wrong decoding the first part: `Mar  8 14:47:42 localhost dockerd:`. I'm looking for a solution
