### ISSUE TITLE
Create macOS policies for SCA

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-ruleset#331]
Currently, there are not available security policies for macOS. This is necessary to be able to perform SCA scans in that OS.

This issue attempts to develop SCA policies based on the CIS benchmarks for the multiple macOS versions available. It also depends on the possibility to create checks that read commands output, which is already developed [here](https://github.com/wazuh/wazuh/issues/2681).

This is the list of available CIS benchmarks for macOS:

- [x] macOS 10.13 _(High Sierra)_

- [x] macOS 10.12 _(Sierra)_

- [x] macOS 10.11 _(El Capitan)_

- [ ] macOS 10.10 _(Yosemite)_

- [ ] macOS 10.9 _(Mavericks)_

- [ ] macOS 10.8 _(Mountain Lion)_

This work has been already started at: [3.9-macos-yaml-policies](https://github.com/wazuh/wazuh-ruleset/tree/3.9-macos-yaml-policies)

**Comment by juan70** [comment]
2019-03-29
----------
- New policies for MacOS 10.13. From the file `CIS_Apple_macOS_10.13_Benchmark_v1.0.0.pdf`, around 31 out of 74 *Scored* checks have been taken into account for the time being.
- TODO: maybe include more *Scored* checks, and include some *Not Scored* ones.

**Comment by juan70** [comment]
According https://en.wikipedia.org/wiki/MacOS: 

| Version | Codename | Release date | Most recent version |
| ------- | -------- | ------------ | ------------------- |
OS X 10.8   | Mountain Lion | July 25, 2012      | 10.8.5 (12F45) (October 3, 2013)
OS X 10.9   | Mavericks     | October 22, 2013   | 10.9.5 (13F1112) (September 18, 2014)
OS X 10.10  | Yosemite      | October 16, 2014   | 10.10.5 (14F27) (August 13, 2015)
OS X 10.11  | El Capitan    | September 30, 2015 | 10.11.6 (15G31) (July 18, 2016)
macOS 10.12 | Sierra        | September 20, 2016 | 10.12.6 (16G29) (July 19, 2017)
macOS 10.13 | High Sierra   | September 25, 2017 | 10.13.6 (17G65) (July 9, 2018)
macOS 10.14 | Mojave        | September 24, 2018 | 10.14.4 (18E226) (March 25, 2019) 

So maybe not all the policy files are going to be implemented. Maybe only 10.13, 10.12 and 10.11.

**Comment by juan70** [comment]
The generic policy files are used for all the UNIX-like operating systems.
For MacOS:
- `generic/system_audit_ssh.yml`
  - OK. `/etc/ssh/sshd_config` exists on MacOS.
- `generic/system_audit_rcl.yml`
  - `/etc`, `/var` are symbolic links to `/private/etc`, `/private/var`
  - `php.ini` seems to be located at `/etc/php.ini`, which is included in the variable `$php.ini`.
  - But `www` directory seems to be:
    - `/Library/WebServer/Documents` by default
    - or `/usr/htdocs` if web sharing is not enabled (https://superuser.com/questions/358944/why-is-mac-os-x-lion-apache-documentroot-usr-htdocs)
    - or `/usr/local/var/htdocs` (https://gist.github.com/DragonBe/0faebe58deced34744953e3bf6afbec7)
    - or `/usr/local/var/www` (https://getgrav.org/blog/macos-mojave-apache-multiple-php-versions)
    The variable `$web_dirs` contains none of these paths.

**Comment by chemamartinez** [comment]
Merged: #345. Thanks @juan70 !!
