### ISSUE TITLE
SCA change default  system_audit_rcl policy

### ISSUE THREAD

**Issue by TJOSERAFAEL** [wazuh/wazuh-ruleset#368]
### Change policy file

The policy file `system_audit_rcl.yml` stands for web vulnerabilities assessment. It comes by default for all systems although is not needed.

#### Tasks

- [ ]  Change its name from `system_audit_rcl.yml` to `web_vulnerabilities.yml`
- [ ]  Do not make it default to all platforms

**Comment by chemamartinez** [comment]
It would be necessary to replace it by a generic policy for Linux systems (which includes configuration assessment for the common configuration of the most number of Linux systems as possible).

**Comment by Skeptor** [comment]
Hi.
The commit https://github.com/wazuh/wazuh-ruleset/commit/40ca279c86c645f44929ae701a61140c8fe1adaa removes the old generic policies and it merges them in a Unix based-systems generic policy.
It is going to be implemented in the solution of the issue: https://github.com/wazuh/wazuh-ruleset/issues/404

Regards.
