### ISSUE TITLE
Remove full_log field in AWS alerts

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh-ruleset#369]
The `full_log` field in the AWS alerts is unnecessary and can be deleted.

<img width="1200" alt="Screen_Shot_2019-05-02_at_11_40_50_AM" src="https://user-images.githubusercontent.com/14975138/57067910-8b71d000-6cd0-11e9-8a5b-5f2292158259.png">

**Comment by Lopuiz** [comment]
Hi!

I's added in this [PR](https://github.com/wazuh/wazuh-ruleset/pull/433)
