### ISSUE TITLE
SCA module skips system_audit_ssh.yml file in HP-UX

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-ruleset#370]
Hi team,

I noticed that SCA module skips the file `system_audit_ssh.yml` in HP-UX hosts, so, SCA doesn't check the security status of SSHD in those hosts. 
```
2019/05/02 05:11:37 sca: INFO: Skipping policy 'system_audit_ssh.yml': 'Check that the SSH service is installed on the system'.
```
This warning appears because of these lines: https://github.com/wazuh/wazuh-ruleset/blob/dff26f04b5e9d9c1992f30c3704c4af483e3dc39/sca/generic/system_audit_ssh.yml#L18-L26
SCA search the `sshd_config` file in the standard path (`/etc/ssh/sshd_config`) but in HP-UX hosts, this file is located in `/opt/ssh/etc/sshd_config`.

Here you can see the entry from `man sshd_config`:

```
SSHD_CONFIG(5)                                               SSHD_CONFIG(5)

NAME
     sshd_config - OpenSSH SSH daemon configuration file

SYNOPSIS
     /opt/ssh/etc/sshd_config
```

Regards.

**Comment by Skeptor** [comment]
Hi.
With the changes implemented in the development of the issue: https://github.com/wazuh/wazuh-ruleset/issues/404, the generic ssh policy is going to disappear.
The generic policies have been merged in a UNIX based systems generic policy: `sca_unix_audit`
In this policy that ssh config path is included in the checks as you can see in the commit: 86981ba82d65ef833dd346b0d884f276a9301495

Regards.
