### ISSUE TITLE
CVE files for RedHat and SUSE as xccdf with an profile

### ISSUE THREAD

**Issue by Joeri-MS** [wazuh/wazuh-ruleset#38]
I build an script wich gets the latest cve-patch files from RedHat and SUSE.
Then these files are convertet to an xccdf with an profile where all cechks are activated.
I like the html output from oscap when using xccdf and an profile.

These script is an bash script wich uses oscap and xsltproc.
It would be fine to add an CVE panel in the wazuh-kibana-app.

In the agent.conf insert:
```
<agent_config profile="sles11">
 <wodle name="open-scap">
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>
    <content type="xccdf" path="cve-sles-11-ds.xml">
      <profile>xccdf_org.opensuse_profile_cve-sles-11</profile>
    </content>
  </wodle>
</agent_config>
<agent_config profile="sles12">
 <wodle name="open-scap">
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>
    <content type="xccdf" path="cve-sles-12-ds.xml">
      <profile>xccdf_org.opensuse_profile_cve-sles-12</profile>
    </content>
  </wodle>
</agent_config>
<agent_config profile="rhel6">
 <wodle name="open-scap">
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>
    <content type="xccdf" path="cve-redhat-6-ds.xml">
      <profile>xccdf_com.redhat.rhsa_profile_cve-rhel-6</profile>
    </content>
  </wodle>
</agent_config>
<agent_config profile="rhel7">
 <wodle name="open-scap">
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>
    <content type="xccdf" path="cve-redhat-7-ds.xml">
      <profile>xccdf_com.redhat.rhsa_profile_cve-rhel-7</profile>
    </content>
  </wodle>
</agent_config>
```
Should i upload my files under wazuh-ruleset/tools/cve-xccdf

**Comment by snaow** [comment]
Hi @Joeri-MS,

We currently don't have a way to send back to the manager the OSCAP HTML report, still, it is something we would like to consider in the future.

I am happy you have been improving and using the OpenSCAP integration + agent.conf centralization, it looks great.
Please upload the script and files to the folder sending a PR and we will review it.

Thanks!

**Comment by Joeri-MS** [comment]
The HTML output can only used when running oscap directly. But I think these CVE xccdf Files with an profile could be better integrated in the Kibana App as a own Panel.

**Comment by jesuslinares** [comment]
Hi @Joeri-MS,
I accepted the PR.

I would like to remember that you can use directly the files from https://www.redhat.com/security/data/oval/ using the syntax:
`<content type="xccdf" path="filename.xml"/>`.

If it is an oval file (ftp://ftp.suse.com/pub/projects/security/oval/) you can use:
`<content type="oval" path="filename.xml"/>`.

Documentation:

- https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-openscap.html#wodle-name-open-scap
- https://documentation.wazuh.com/current/user-manual/capabilities/policy-monitoring/openscap/index.html

Thanks for your contribution.
Regards.
