### ISSUE TITLE
Rules 83002 and 62104 have a wrong description

### ISSUE THREAD

**Issue by cristgl** [wazuh/wazuh-ruleset#384]
Rules 83002 and 62104 from Windows Defender filter by event ID 1117, which, following the [Windows Defender documentation](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/troubleshoot-windows-defender-antivirus) are due to an action taken to protect the system.

At the ruleset both of them have the next description: `error when taking action on potentially unwanted software`. Maybe this description should apply to event ID 1119.

**Comment by Lopuiz** [comment]
Hi @cristgl,
Thank you for your feedback. I'll close this issue because the problem has been solved.
Kind regards, Eva
