### ISSUE TITLE
[Windows Eventchannel] Improve Windows Defender rules

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-ruleset#389]
Related to issue https://github.com/wazuh/wazuh-ruleset/issues/384.

The Windows Defender rules (located at [0600-win-wdefender_rules.xml](https://github.com/wazuh/wazuh-ruleset/blob/3.9/rules/0600-win-wdefender_rules.xml)) can be extended. Currently we only alert for events 1116 and 1117.

Classifying Windows Defender events by the Event ID, the [Windows Defender documentation](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/troubleshoot-windows-defender-antivirus) provide us the translation of these event IDs.

For example, the event ID 1119 means _The antimalware platform encountered a critical error when trying to take action on malware or other potentially unwanted software_.

**Comment by paroma96** [comment]
Hi, Team.
This issue can be solved with PR #472 .

Regards,
Pablo

**Comment by havidarou** [comment]
Changes have been merged.
