### ISSUE TITLE
SCA Windows policy problem with "Windows NT" vs "WindowsNT" registry paths

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh-ruleset#391]
Compare the output of these two sets of "Windows NT" vs "WindowsNT" SCA registry checks

```
grep -iF "Software\Microsoft\Windows NT" /var/ossec/ruleset/sca/*
grep -iF "Software\Microsoft\WindowsNT" /var/ossec/ruleset/sca/*
```

We have a bunch of each kind and they do not appear to be variations of the same check depending on Windows version.  I see "Unable to read registry..." complaints from SCA about the "WindowsNT" checks and indeed there is no such path in my Windows 10 registry.  In fact after doing some research dating back to articles from 2009, I am under the impression all of the "WindowsNT" registry path checks are just typos and should use "Windows NT" instead.  

For example, the only SCA rules looking at the ScRemoveOption registry value are looking for this registry path:

```
HKEY_LOCAL_MACHINE\Software\Microsoft\WindowsNT\CurrentVersion\Winlogon -> ScRemoveOption
```

which does not exist in my registry at all, though the following path is in my registry and is not inspected by SCA

```
HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon -> ScRemoveOption
```

At first I though maybe this was just checks that apply to older versions of Windows but now I am thinking it is just a set of typos in the rules.  When I looked at the registry on a Windows 2012 server it also uses "HKLM\Software\Microsoft\Windows NT" and has no such path "HKLM\Software\Microsoft\WindowsNT"

Please check into this and fix the relevant SCA rules if my observations are accurate.

And thanks so much for the work you all have put into upgrading the super-legacy rootcheck policy auditing feature with SCA.  I think we are really going to like it!

Thanks!
Kevin Branch

**Comment by TJOSERAFAEL** [comment]
Hi @branchnetconsulting ,

that's a good catch! You are right indeed, the path for those registers is wrong.

This PR https://github.com/wazuh/wazuh-ruleset/pull/393 solves the issue.

Again thank you for your feedback and collaboration!

Best regards.

**Comment by chemamartinez** [comment]
Hi @branchnetconsulting,

The issue has been solved and already merged. It will be available in the next version patch.

Thank you so much for reporting this bug.

Best regards,
Chema.
