### ISSUE TITLE
OpenVPN decoder parsing openvpnas.log

### ISSUE THREAD

**Issue by nodesocket** [wazuh/wazuh-ruleset#395]
Does the included OpenVPN decoder `openvpn_decoders.xml` work if OpenVPN is logging to a file in `/var/log/openvpnas.log` or does it require logging to syslog? Is there a way to configure it to work with a custom log file path?

**Comment by Lopuiz** [comment]
Hello @nodesocket, 
Yes, it's possible to collect the OpenVPN logs using [Log Collector](https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/index.html).
You can follow this [link](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html) to configure it.
Regards, Eva.
