### ISSUE TITLE
[Windows Eventchannel] ID 1102 is not being parsed correctly 

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-ruleset#396]
Hello Team,

I have realized that when I get the following event `1102`  in the Manager, it is not generating an alert despite we have a rule for that:

https://github.com/wazuh/wazuh-ruleset/blob/3.9/rules/0435-ms_logs_rules.xml

As I can see in the above rule, the provider name is `Microsoft-Windows-Eventlog`

However, the following rule: https://github.com/wazuh/wazuh-ruleset/blob/ed8396ecfb55d25b1cfb5f005171ddb99e05971e/rules/0575-win-base_rules.xml set the channel as `Microsoft-Windows-Eventlog`

```

  <rule id="60007" level="0">
    <if_sid>60000</if_sid>
    <field name="win.system.channel">^Microsoft-Windows-Eventlog</field>
    <options>no_full_log</options>
    <description>Group of rules for Windows Eventlog</description>
  </rule>
```
It should be as follow:

`<field name="win.system.providerName">^Microsoft-Windows-Eventlog</field>`

**Comment by chemamartinez** [comment]
Hi @MiguelCasaresRobles,

This issue has been already merged #397.

Thanks for reporting it.
