### ISSUE TITLE
Adapt SCA rules to the new designed syntax

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-ruleset#404]
As developed at https://github.com/wazuh/wazuh/issues/3249, SCA rules for versions from 3.10 will change in the following points:

- The logic will be inverted. That it is, now checks are considered as _passed_ when the rule is satisfied, and _failed_ when not.
- Rules have not to be finished with a semicolon `;`.
- The operators _IN/NIN_ are deprecated in favor of _not_. This operator should be located at the start of the rule, not in the middle.
- The conditions _all required_ and _any required_ are deprecated. The requirements section is enough to determine if evaluate a policy or not.

These changes imply a rework of every SCA policy.

**Comment by JuantAldea** [comment]
[ ] Generic
[ ] Debian
[ ] SLES
[ ] RHEL
[ ] Solaris
[ ] Darwin
[ ] Windows

**Comment by chemamartinez** [comment]
We have decided to reorganize the Debian policies, it hasn't sense to have the same policy file for all Debian versions (7, 8 and 9) due to the conflicts found between them.

So, finally, the SCA policies available for Debian (and all debian-based Operating Systems) in Wazuh 3.10 will be:

- [ ] CIS Debian 7 L1 _In progress_ -> 9d3331abb3beeeee642fc2823cb11d500bfa5898

- [ ] CIS Debian 7 L2 _In progress_ -> 9d3331abb3beeeee642fc2823cb11d500bfa5898

- [x] CIS Debian 8 L1 _Done_

- [x] CIS Debian 8 L2 _Done_

Related commits:

- a2daa3436e261b14c65a9ecb4be5f8f9c6719609
- e1f49248db8ba26355add857bd40230908a37c49
- 4cc9ab7d99ed9de65859ab20b8ddcfd4fb8035c5
- 8d7741eab22260ac7b79e82cd142ef29f126f74d

- [ ] CIS Debian 9 L1

- [ ] CIS Debian 9 L2

Including these new policies was a request from the community as well (https://github.com/wazuh/wazuh-ruleset/issues/297).

**Comment by chemamartinez** [comment]
Merged https://github.com/wazuh/wazuh-ruleset/pull/406
