### ISSUE TITLE
Add HIPAA and NIST 800 53 to compliance in SCA policies

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh-ruleset#411]
SCA policies must be updated to map NIST 800-53 and HIPAA standards, in a similar way the rules were updated.

Taking advantage of the current PCI DSS compliance mapping, a Python script should be done to edit all SCA policies automatically, similar to this one: https://github.com/wazuh/wazuh-ruleset/blob/3.10/tools/map-security-standard/map_standard.py

The mapping to be used will be the explained in #394 and #392.

The final mapping should be performed after https://github.com/wazuh/wazuh-ruleset/issues/404 is closed.

**Comment by AdriiiPRodri** [comment]
## Status update

A script has been added to be able to add HIPAA and NIST 800 53 to compliance in SCA policies, the script can be used as much as to **include** the new standards initially to the SCA policies as to **update** the existing ones, which means that the script can be executed as many times as desired because it will **always give the same result** thus maintaining consistency and updating or creating the new standards in the file.

## Script parameters

```bash
adriiiprodri@Wazuh:~/Desktop/git/wazuh-ruleset/tools/map-security-standard$ python map_standard_yaml.py -h
usage: map_standard_yaml.py [-h] [-p PATH] [-m MAPPING]

optional arguments:
  -h, --help            show this help message and exit
  -p PATH, --path PATH  Sca path
  -m MAPPING, --mapping MAPPING
                        Mapping path
```

**Comment by AdriiiPRodri** [comment]
## Status update

We have added the functionality to remove standards in sca files, to do this we will use the parameter (-d/--delete):

```bash
adriiiprodri@Wazuh:~/Desktop/git/wazuh-ruleset/tools/map-security-standard$ python map_standard_yaml.py -h
usage: map_standard_yaml.py [-h] [-p PATH] [-m MAPPING] [-d DELETE]

optional arguments:
  -h, --help            show this help message and exit
  -p PATH, --path PATH  Sca path
  -m MAPPING, --mapping MAPPING
                        Mapping path
  -d DELETE, --delete DELETE
                        Standard to be delete
```

```bash
adriiiprodri@Wazuh:~/Desktop/git/wazuh-ruleset/tools/map-security-standard$ python map_standard_yaml.py -d pci_dss
[DELETE] Deleted pci_dss in file system_audit_rcl_mac.yml
[DELETE] Deleted pci_dss in file generic/system_audit_rcl.yml
[DELETE] Deleted pci_dss in file generic/system_audit_ssh.yml
[DELETE] Deleted pci_dss in file rhel/7/cis_rhel7_linux_rcl.yml
[DELETE] Deleted pci_dss in file rhel/6/cis_rhel6_linux_rcl.yml
[DELETE] Deleted pci_dss in file rhel/5/cis_rhel5_linux_rcl.yml
[DELETE] Deleted pci_dss in file debian/cis_debian_linux_rcl.yml
[DELETE] Deleted pci_dss in file sles/11/cis_sles11_linux_rcl.yml
[DELETE] Deleted pci_dss in file sles/12/cis_sles12_linux_rcl.yml
[DELETE] Deleted pci_dss in file windows/win_audit_rcl.yml
[DELETE] Deleted pci_dss in file darwin/system_audit_rcl_mac.yml
```
