### ISSUE TITLE
Update rules

### ISSUE THREAD

**Issue by marciofoz** [wazuh/wazuh-ruleset#42]
The checks 1.4.2 and 1.4.3 in cis_rhel7_linux_rcl.txt must be updated to correctly identify Selinux:

1.4.2 Set selinux state
[CIS - RHEL7 - 1.4.2 - SELinux not set to enforcing {CIS: 1.4.2 RHEL7} {PCI_DSS: 2.2.4}] [any] [https://benchmarks.cisecurity.org/tools2/linux/CIS_Red_Hat_Enterprise_Linux_7_Benchmark_v1.1.0.pdf]

from
f:/etc/selinux/config -> r:SELINUX=enforcing;
to
f:/etc/selinux/config -> **!r**:SELINUX=enforcing;

1.4.3 Set seliux policy
[CIS - RHEL7 - 1.4.3 - SELinux policy not set to targeted {CIS: 1.4.3 RHEL7} {PCI_DSS: 2.2.4}] [any] [https://benchmarks.cisecurity.org/tools2/linux/CIS_Red_Hat_Enterprise_Linux_7_Benchmark_v1.1.0.pdf]

from
f:/etc/selinux/config -> r:SELINUXTYPE=targeted;
to
f:/etc/selinux/config -> **!r**:SELINUXTYPE=targeted;

BR

**Comment by jesuslinares** [comment]
I fixed the rootcheck: https://github.com/wazuh/wazuh-ruleset/commit/10c51212dea912309dce94edbc354f4a6cf4c467

Thanks for your contribution!.
