### ISSUE TITLE
A question about two rules

### ISSUE THREAD

**Issue by John33000** [wazuh/wazuh-ruleset#438]
Hi,
I would like know if there are difference between rule : Brute force trying ti get access to  and multiple login failed ? It's the same rule for me .

Bests regards

**Comment by Lopuiz** [comment]
Hi @John33000, 

I don't know what rules you refer to. Could it be rules 5712 and 5720?

The rule 5710 must match 8 times in 120 seconds before firing 5712.  Them, it will be ignored 60 seconds. 
https://github.com/wazuh/wazuh-ruleset/blob/b5521e6a75cc42257414cc5b1d53561b1ea85bfd/rules/0095-sshd_rules.xml#L91

Maybe, while the previous rule is ignored this other rule triggers:
https://github.com/wazuh/wazuh-ruleset/blob/b5521e6a75cc42257414cc5b1d53561b1ea85bfd/rules/0095-sshd_rules.xml#L147

If this is not the case, send us more information and we will reproduce your case. It will help us find the problem in case the rules are not working.

Regards, Eva

**Comment by John33000** [comment]
Hi,
Yes I talk about these two rules, thanks

Regards, John33000
