### ISSUE TITLE
Doubts Wizuh logs and alert

### ISSUE THREAD

**Issue by pijolysss** [wazuh/wazuh-ruleset#446]
Hello,

I would like to get logs from my own app which it gives some folders with logs inside. I would like to monitor in real time and create alerts based in that logs. For example, if there are some ERROR logs lines, just send an email to notify.

¿Is it possible to do with Wazuh? 

Additionally, I would like to test the alerts using Wizuh IDS/IPS system. Im speaking about Security Events. Im totally new in that, so... ¿any idea about how to test it? :) 

Thank you very much!

**Comment by Lopuiz** [comment]
Hello @pijolysss 

Yes, you can create your own rules and decoders for your application.

First of all, to monitor log files I recommend you to use [Logcollector](https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/index.html).  The following configuration in `/var/ossec/etc/ossec.conf` instructs Logcollector to send the logs to Analysisd:
```xml
<localfile>
    <location>path/your/logs/file.log</location>
    <log_format>syslog</log_format>
</localfile>
```

You can read more about Logcollector configuration in our [documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html).

Analysisd has three phases to process the logs.

1. Preprocessing: divide the log into timestamp, hostname, program_name, and log
2. Decoding: allows you to extract fields that you consider important to show in Kibana.
3. Matching rules: this phase is in charge of generating the alert.

The decoders and rules correspond to the second and third phases. They are implemented in XML.

Decoder examples could be the following:

```xml
<decoder name="wazuh">
  <prematch>^wazuh: </prematch>
</decoder>

<decoder name="agent-buffer">
  <parent>wazuh</parent>
  <prematch offset="after_parent">^Agent buffer:</prematch>
  <regex offset="after_prematch">^ '(\S+)'.</regex>
  <order>level</order>
</decoder>
```

And rules:
```xml
<group name="wazuh,">
  <rule id="200" level="0">
    <decoded_as>wazuh</decoded_as>
    <description>Grouping of wazuh rules.</description>
  </rule>

  <!-- Agent buffer rules -->
  <rule id="201" level="0">
    <if_sid>200</if_sid>
    <match>^wazuh: Agent buffer: </match>
    <description>Agent event queue rule</description>
    <group>agent_flooding,</group>
  </rule>

  <rule id="202" level="7">
    <if_sid>201</if_sid>
    <field name="level">%</field>
    <description>Agent event queue is $(level) full.</description>
    <group>agent_flooding,gdpr_IV_35.7.d,</group>
  </rule>
```

To create your own rules and decoders you can follow our [documentation](https://documentation.wazuh.com/current/user-manual/ruleset/custom.html).
To know more about the syntax you can follow this [link](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/index.html).

To verify that your rules works you can use [ossec-logtest](https://documentation.wazuh.com/current/user-manual/reference/tools/ossec-logtest.html).

And finally, configure Wazuh to send email alerts. To do this you can follow this [link](https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html).

I hope this helps you. If you have further questions lets us know.
Also, you can pass us some logs of your application. We will create some rules and decoders for them. This way, it will be easier for you to create the rest of the rules and decoders.

We have some rules and decoders. You can find them in our [Ruleset](https://github.com/wazuh/wazuh-ruleset) repository.

Some of our features are log data collection (logcollector), file integrity monitoring and vulnerability detection. You can consult all our functionalities in the following [link](https://documentation.wazuh.com/current/user-manual/capabilities/index.html).

You can read and test our functionalities and consult all questions you have.

Best regards,
Eva.

**Comment by pijolysss** [comment]
@Lopuiz thank you very much for your fast answer. I would like to show you an example about one of my own logs that i would like to extract. This could be an example, lets say it´s located in C:\ProgramFiles\Logs\Log1.txt:
[04/07/2019 16:11:53.110][DEBUG][0]:     Error inserting data in group: 1 - rows: 3
[04/07/2019 16:11:53.110][DEBUG][0]:     Cant be possible to insert data, executing alternativeFlush()
[04/07/2019 16:11:53.110][ERROR][0]:     Executing: Group[1].alternativeFlush
[04/07/2019 16:11:53.110][ERROR][0]:     Exception

¿How will be the rules and decoders for that log? ¿Could you prepare an example to me? In that way, I will check how to do it and I will try for another logs.
After that, I will check how to send email alerts. The goal of that log is to alert about there´s a problem inserting data in the databases and receive and email informing about it. 

Another question, could we get more than one log file simultaneously? Or it´s better to get one by one? The issue is that the logs are differents between them.
Thank you very much!

Best regards

**Comment by Lopuiz** [comment]
Hello @pijolysss 

You're welcome. The community comes first.

Using Logcollector you can send to the manager as many log files as you want.
If logs have different formatting you will have to make rules for both formats.

As I mentioned in the previous commentary, Analisisd has three phases for log processing.
This is the output when I enter the second log in ossec-logtest:

![logtest_output](https://user-images.githubusercontent.com/17710550/60651708-0da08100-9e47-11e9-8847-4507c85ebd6a.png)

As you can see the preprocessing does not divide the log into timestamp, hostname, program_name, and log. This is because we don't have this format added to our preprocessing function:

[int OS_CleanMSG(char *msg, Eventinfo *lf)](https://github.com/wazuh/wazuh/blob/38893cd7ac5255f52dc06d755ffff31bb59df798/src/analysisd/cleanevent.c#L26)

The rules and decoders must match the log field (which in this case is full log).

The second phase is decoding. An example of a decoder can be the following:

```xml
<decoder name="your-program-name">
  <match>[\d+/\d+/\d+ \d+:\d+:\d+.\d+][\w+][\d]:</match>
  <regex>][(\w+)][\d+]: (\.+)</regex>
  <order>type_message, message</order>
</decoder>
```
And logtest output is:
![Screenshot_20190704_110420](https://user-images.githubusercontent.com/17710550/60654047-8275ba00-9e4b-11e9-97e3-6ac46e8819ad.png)

And finally the rules:
```xml
  <rule id="777777" level="0">
    <decoded_as>your-program-name</decoded_as>
    <description>Group of your program rules</description>
  </rule>

  <rule id="777778" level="3">
    <if_sid>777777</if_sid>
    <field name="type_message">ERROR</field>
    <description>Error in the program</description>
  </rule>
```

And logtest output is:
![Screenshot_20190704_111504](https://user-images.githubusercontent.com/17710550/60654848-0a0ff880-9e4d-11e9-857c-e82fd9a4a489.png)

Note:
1. To generate an alert the level of the rule must be higher than 2.
2. There can be no rules with duplicate id.

Best regards,
Eva.

**Comment by pijolysss** [comment]
Hello again @Lopuiz ! :) 

I did as the following:
Configure in the agent the logcollector as follows (/etc/ossec.conf):
`<localfile>
    <location>path/your/logs/file.log</location>
    <log_format>syslog</log_format>
</localfile>`

Then, i just included your decoder in the manager (/etc/decoders/local_decoder.xml) and the rules (/rules/local_rules.xml). I got this error:
[root@localhost rules]# /var/ossec/bin/ossec-logtest 
2019/07/04 12:39:52 ossec-testrule: ERROR: Invalid element 'match' for decoder 'decoder'
2019/07/04 12:39:52 ossec-testrule: CRITICAL: (1202): Configuration error at 'etc/decoders/local_decoder.xml'.


I don´t know why... 
Anyway, how can I check if logcollector is sending data properly to manager? I mean, its collecting data from the logfile and sendint it to the manager. 

Best Regards,

**Comment by Lopuiz** [comment]
Sorry for the misunderstanding. The label is 'prematch', not 'match'.

Regarding logcollector, you can activate the [logall](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#logall) option in `ossec.conf`.

When you activate this option and restart the manager, a file `/var/ossec/logs/archives/archives.log` will be created. This file contains all events that are received by the manager. All these events are processed by analysisd.

**Comment by pijolysss** [comment]
No problem :) 
Now it´s working. 

So, now to put it in production, I would like it to work automatically. I mean, agent should check the log and manager should generate alert and email. I configured the email, but I didn´t receive it (I chose lvl 3 to send email, just to try it). 
<global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>no</logall>
    <logall_json>no</logall_json>
    <email_notification>yes</email_notification>
    <smtp_server>smtp.example.wazuh.com</smtp_server>
    <email_from>ossecm@example.wazuh.com</email_from>
    <email_to>myemail@gmail.com</email_to>
    <email_maxperhour>12</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
  </global>

<ossec_config>
  <alerts>
      <email_alert_level>3</email_alert_level>
  </alerts>
  ...
</ossec_config>
I just try the ossec-logtest, but is it working automatically or have I to enable something? How can I check it? 

Thanks for all support, I´ve never worked with it before. 

Best regards,

**Comment by pijolysss** [comment]
Hello again! Sorry, I made an error in configuration file. Now I´m receiving emails:
Wazuh Notification.
2019 Jul 05 11:04:46
Received From: localhost->ossec-monitord
Rule: 502 fired (level 3) -> "Ossec server started."
Portion of the log(s):
ossec: Ossec started.
 --END OF NOTIFICATION

The problem is I´m not receiving emails about the Agent log that we are checking. ¿What I should do?

**Comment by Lopuiz** [comment]
Hello @pijolysss 

Could you explain to me how you want to configure the sending of alerts by email? And what is the level of your rules?
The alert level refers to the rule level. Alerts generated by rules with a level higher than 3 or 10 will be sent to email.

Regards, Eva

**Comment by pijolysss** [comment]
Finally I got it :) Thank you very much

**Comment by Lopuiz** [comment]
okay, you're welcome

**Comment by Lopuiz** [comment]
Hello

I'm closing this issue. I hope I was helpful. If you have further questions don't hesitate to open new issues.

Regards, Eva
