### ISSUE TITLE
18119

### ISSUE THREAD

**Issue by ecsc-georgew** [wazuh/wazuh-ruleset#454]

**Comment by Zenidd** [comment]
Hi @ecsc-georgew,

Could you paste here an example log to recreate that behavior? This way we can give a better solution to your problem.

Greetings, Juan Pablo Sáez

**Comment by ecsc-georgew** [comment]
Hi @Zenidd 

Thanks for looking at this, here you go:
2019 Jul 22 13:09:29 WinEvtLog: Security: AUDIT_SUCCESS(4769): Microsoft-Windows-Security-Auditing: (no user): no domain: ACOMPUTERACCOUNT.contoso.local: A Kerberos service ticket was requested.    Account Information:   Account Name:  username@contoso.local   Account Domain:  contoso.local   Logon GUID:  {0AECE614-F279-ECD9-12C4-C8A2C036A419}    Service Information:   Service Name:  ACOMPUTERACCOUNT$   Service ID:  S-1-5-21-515962299-920033366-844442115-30008    Network Information:   Client Address:  ::1   Client Port:  0    Additional Information:   Ticket Options:  0x40810000   Ticket Encryption Type: 0x12   Failure Code:  0x0   Transited Services: -    This event is generated every time access is requested to a resource such as a computer or a Windows service.  The service name indicates the resource to which access was requested.    This event can be correlated with Windows logon events by comparing the Logon GUID fields in each event.  The logon event occurs on the machine that was accessed, which is often a different machine than the domain controller which issued the service ticket.    Ticket options, encryption types, and failure codes are defined in RFC 4120.+

**Comment by Zenidd** [comment]
Hi @ecsc-georgew,

Using [/var/ossec/bin/ossec-logtest](https://documentation.wazuh.com/3.x/user-manual/reference/tools/ossec-logtest.html) I have checked the rule that is triggered when the event you pasted above occurs.

The first time the event occurs, this is the output:
```
**Phase 3: Completed filtering (rules).
       Rule id: '18119'
       Level: '3'
       Description: 'Windows: First time this user logged in this system.'
**Alert to be generated.
```

From the second time the event occurs, we can see the following output:
```
**Phase 3: Completed filtering (rules).
       Rule id: '18107'
       Level: '3'
       Description: 'Windows Logon Success.'
**Alert to be generated.
```

As you mentioned, these alerts are far from well representing the event that fires them. 

The Wazuh-Ruleset does not contain specific Kerberos rules, however you can create your own custom rules and we will help you with whatever you need. 

I have created a rule with a more precise description for the event with ID 4769. You can place it on `/var/ossec/etc/rules/local_rules.xml`

```XML
<rule id="100013" level="5">
  <if_sid>18107</if_sid>
 <id>^4769$</id>
 <description>Kerberos ticket request</description>
  <options>no_full_log</options>
 </rule>
```
This is the output for your event:

```
**Phase 3: Completed filtering (rules).
       Rule id: '100013'
       Level: '5'
       Description: 'Kerberos ticket request'
**Alert to be generated.
```

It is also possible to extend the rule to show the account name:

```XML
<rule id="100013" level="5">
  <if_sid>18107</if_sid>
 <id>^4769$</id>
 <description>Kerberos ticket request from account $(account_name)</description>
  <options>no_full_log</options>
 </rule>

```


```
**Phase 3: Completed filtering (rules).
       Rule id: '100013'
       Level: '5'
       Description: 'Kerberos ticket request from account username@contoso.local'
**Alert to be generated.
```


Please, let me know if it helps. Greetings, 

Juan Pablo Sáez

**Comment by ecsc-georgew** [comment]
Thanks Juan,

I'll try applying that and let you know but it definitely looks like it will work to me. 

If we come across things like this in future is it worth making forks and pull requests for you to merge into the ruleset?

**Comment by Zenidd** [comment]
Hi again @ecsc-georgew,

You're welcome! Let me know if you need any more help with this thing.

We are always open to community contributions, each use case is different and gives us perspective. 
We will be happy to review(when our workflow allows it) and if possible add your contributions to the Wazuh project. 

Greetings, Juan Pablo Sáez

**Comment by ecsc-georgew** [comment]
Thanks Juan,

It works but I had to set the if_sid to match 18119 as well:
    <if_sid>18107,18119</if_sid>
Appreciate the help on this one. 

Cheers, George.
