### ISSUE TITLE
Detect Software Restriction Policy notifications on Windows

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-ruleset#455]
Hi team,

The Windows ruleset for Application events contains rules about the Software Restriction Policy when new software is attempted to be installed on agents (see rules ID [60617](https://github.com/wazuh/wazuh-ruleset/blob/66af32cbbe3be1a9d8589c86080ee5a8cc69877f/rules/0585-win-application_rules.xml#L147) and [60618](https://github.com/wazuh/wazuh-ruleset/blob/66af32cbbe3be1a9d8589c86080ee5a8cc69877f/rules/0585-win-application_rules.xml#L154)). 

However, we have to extend these rules in order to detect other actions blocked by that policy, for example, the event ID [865](http://intelligentsystemsmonitoring.com/knowledgebase/windows-operating-system/event-id-software-restriction-policy-notification-13844/) related to try to run a program restringed by the policy. The same for other events related to the Software Restriction Policy such as 866, 867 and 882.

**Comment by rafamunoz98** [comment]
These rules are triggered when those events from Windows Server 2008 R2 (865-868 and 882) happen
```
<rule id="61063" level="0">
    <if_sid>60600</if_sid>
    <field name="win.system.providerName">^Microsoft-Windows-SoftwareRestrictionPolicies$</field>
    <description>Group of Microsoft-Windows-SoftwareRestrictionPolicies events</description>
    <options>no_full_log</options>
  </rule>
<rule id="61064" level="5">
  <if_sid>61063</if_sid>
  <field name="win.system.eventID">^865$</field>
  <description>Access restricted by your Administrator by the default software restriction policy level</description>
  <options>no_full_log</options>
 </rule>
 <rule id="61065" level="5">
  <if_sid>61063</if_sid>
  <field name="win.system.eventID">^866$</field>
  <description>Access restricted by your Administrator by location with policy rule </description>
  <options>no_full_log</options>
 </rule>
 <rule id="61066" level="5">
  <if_sid>61063</if_sid>
  <field name="win.system.eventID">^867$</field>
  <description>Access restricted by your Administrator by software publisher policy</description>
  <options>no_full_log</options>
 </rule>
 <rule id="61067" level="5">
  <if_sid>61063</if_sid>
  <field name="win.system.eventID">^868$</field>
  <description>Access restricted by your Administrator by policy rule</description>
  <options>no_full_log</options>
 </rule>
 <rule id="61068" level="5">
  <if_sid>61063</if_sid>
  <field name="win.system.eventID">^882$</field>
  <description>Access restricted by your Administrator by policy rule</description>
  <options>no_full_log</options>
 </rule>
```
