### ISSUE TITLE
How to ignore Rule id: 203 "Agent event queue is full. Events may be lost."

### ISSUE THREAD

**Issue by oz17il** [wazuh/wazuh-ruleset#456]
Hey,

What is the correct way to ignore a specific Rule ID? 
I know that I have to edit the below file, but not sure what is the correct syntax?  var/ossec/etc/rules/local_rules.xml

Thanks,

**Comment by Lopuiz** [comment]
Hello @oz17il,
 
To silence rule 203 you must modify its level. You can overwrite it by adding the following to `local_rules.xml`: 
```XML
  <rule id="203" level="1" overwrite="yes">
    <if_sid>201</if_sid>
    <field name="level">full</field>
    <description>Agent event queue is full. Events may be lost.</description>
    <group>agent_flooding,gdpr_IV_35.7.d,</group>
  </rule>
```

Best regards, Eva

**Comment by Lopuiz** [comment]
Hello!

I hope it helped you. I will close this issue for inactivity.
If you have further questions, let us know and we will help you.

Regards,
Eva
