### ISSUE TITLE
SCA -  Drive Mount Options - File System Types

### ISSUE THREAD

**Issue by rhysxevans** [wazuh/wazuh-ruleset#462]
Hi

Are we able to add more fs types to the mount rules ?

eg id: 5001  is currently  (there are others)

`'f:/etc/fstab -> NIN !r:^# && r:ext2|ext3 && r:/tmp && r:nodev;'`

can we make it something like (there may be better options)

`'f:/etc/fstab -> NIN !r:^# && r:ext2|ext3|ext4|xfs && r:/tmp && r:nodev;'`

The following is an extract from my current fstab

`
UUID=ef9ffee4-90ad-444b-9efd-ce50ce4f913b /tmp ext4 defaults,nodev 0 0
UUID=3713da16-6c5d-47d5-83b4-5fcb2afc6c61 /boot ext4 defaults 0 0
/dev/mapper/ubuntu--vg-home /home ext4 nodev 0 0
UUID=b7794b13-0a83-4044-a97b-c60f9033d837 /var/log ext4 defaults 0 0
UUID=c145bd10-ac78-4163-b835-185404765cb4 /var/tmp ext4 defaults,nodev 0 0
`

Any help is appreciated

Thanks

**Comment by JuantAldea** [comment]
Hi @rhysxevans,
you can indeed add more filesystems as you suggest.

Best regards.

**Comment by rhysxevans** [comment]
Sorry does this mean they will be added (by default) in future updates of
your ruleset ?

**Comment by JuantAldea** [comment]
No, we will stick to the CIS documents.  But you can manually edit the rules as you see fit.

On the other hand, in future updates we will overwrite the contents of the ruleset folder so you will lose your changes unless you move your custom policies to another folder. 
Moreover, we will be changing the syntax and the logic of SCA rules in 3.10 so please take note of the rules you modify or add and adapt them to the new syntax after you update Wazuh.

Best regards

**Comment by rhysxevans** [comment]
Hi

But the CIS doc doesn't specify a fs type (other than those to remove) and
all the examples include ext4

Eg 1.1.13

# mount | grep /home
/dev/xvdf1 on /home type ext4 (rw,nodev,relatime,data=ordered)

from
CIS Ubuntu Linux 18.04 LTS Benchmark v1.0.0 - 08-13-2018

Thanks

**Comment by rhysxevans** [comment]
looks like it may be fixed in
https://github.com/wazuh/wazuh-ruleset/blob/8e7c685c8a5e3182ee9efabdf4d00e1ab6c23eb2/sca/debian/cis_debian9_L1.yml#L258
 ?

**Comment by JuantAldea** [comment]
Yes, the upcoming version has the FS type enforcement removed.
