### ISSUE TITLE
cis debian rules

### ISSUE THREAD

**Issue by dmitrijn** [wazuh/wazuh-ruleset#47]
latest revision for debian cis - https://benchmarks.cisecurity.org/tools2/linux/CIS_Debian_Linux_8_Benchmark_v1.0.0.pdf

**Comment by jesuslinares** [comment]
Hi @dmitrijn,

thanks for letting us know about the latest revision for CIS Debian 8. Right now, we are focus on other features of Wazuh, but we will implement it as soon as possible.

I encourage you to implement the rootchecks by yourself. It would be a great contribution to the community.

Thanks.
Regards.
