### ISSUE TITLE
Troubles collecting events from SysMon part 2

### ISSUE THREAD

**Issue by jmora2** [wazuh/wazuh-ruleset#475]
Hello Team,

I am trying to do exactly as indicated in issue #282, but I dont know what the problem is:

I am using the following rule:

<group name="sysmon,">
<rule id="255000" level="12">
     <if_group>sysmon_event1</if_group>
     <field name="EventChannel.EventData.Image">\powershell.exe||\.ps1||\.ps2</field>
     <description>Sysmon - Event 1: Bad exe: $(EventChannel.EventData.Image)</description>
     <group>sysmon_event1,powershell_execution,</group>
</rule>

with the following config in the agent:

</ossec_config>
<client>
 <server>
  <address>1.2.3.4</address>
  </server>
</client>
 <localfile>
  <location>Microsoft-Windows-Sysmon/Operational</location>
  <log_format>eventchannel</log_format>
 </localfile>
</ossec_config>

agent installed in windows 10
v3.9.5

One more thing, I do not see the logs coming to the alerts json/log and I do not know how to turn the logs on to view if they are coming.

Any help will be highly appreciate it, I have been working on this for about two weeks and I just saw the threat #282 and I was hoping that it could work, but it didnt. Please help!!!

Gruss,

Jeffry L. Mora

**Comment by jmora2** [comment]
It is very weird that the whole description is not showing, attached are some screenshots of the config
![1](https://user-images.githubusercontent.com/36069428/63359907-d0983b80-c36d-11e9-9910-537eeecbbd19.JPG)
![2](https://user-images.githubusercontent.com/36069428/63359915-d3932c00-c36d-11e9-9db2-c0d51a2aca49.JPG)

**Comment by Lopuiz** [comment]
Hello @jmora2 

In Wazuh 3.8 a new Eventchannel was implemented. As a consequence, the alerts have different name fields. An alert of the new Eventchannel is the following:
```json
{

    "win":{
        "system":{
            "providerName":"Microsoft-Windows-Sysmon",
            "providerGuid":"{5770385F-C22A-43E0-BF4C-06F5698FFBD9}",
            "eventID":"1",
            "version":"5",
            "level":"4",
            "task":"1",
            "opcode":"0",
            "keywords":"0x8000000000000000",
            "systemTime":"2019-06-13T09:36:52.805306700Z",
            "eventRecordID":"23",
            "processID":"4896",
            "threadID":"2596",
            "channel":"Microsoft-Windows-Sysmon/Operational",
            "computer":"WIN-S0GE7HFOP5K",
            "severityValue":"INFORMATION",
            "message":"Process Create:"
        },
        "eventdata":{
            "utcTime":"2019-06-13 09:36:52.796",
            "processGuid":"{E6A6834E-1934-5D02-0000-0010EDA21B00}",
            "processId":"4240",
            "image":"C:\\Windows\\SysWOW64\\notepad.exe",
            "fileVersion":"10.0.14393.0 (rs1_release.160715-1616)",
            "description":"Notepad",
            "product":"Microsoft® Windows® Operating System",
            "company":"Microsoft Corporation",
            "originalFileName":"NOTEPAD.EXE",
            "commandLine":"notepad ossec.log",
            "currentDirectory":"C:\\Program Files (x86)\\ossec-agent\\",
            "user":"WIN-S0GE7HFOP5K\\Administrator",
            "logonGuid":"{E6A6834E-F48D-5D01-0000-002042E30200}",
            "logonId":"0x2e342",
            "terminalSessionId":"1",
            "integrityLevel":"High",
            "hashes":"MD5=AF79F5A331C50CC87F0A5F921AD93B0F,SHA256=9CD1C3D00AE15068DDB5F9103C517768FDC9C2ED8D7F6A729CDE9314C591874A",
            "parentProcessGuid":"{E6A6834E-1884-5D02-0000-00100E5C1B00}",
            "parentProcessId":"4680",
            "parentImage":"C:\\Program Files (x86)\\ossec-agent\\win32ui.exe",
            "parentCommandLine":"\"C:\\Program Files (x86)\\ossec-agent\\win32ui.exe\""
        }
    }

}
```
And rule to match it could be following:
```xml
<group name="sysmon,">

  <rule id="255000" level="12">
     <if_group>sysmon_event1</if_group>
     <field name="win.eventdata.image">notepad.exe</field>
     <description>Sysmon - Event 1: notepad executed</description>
     <group>sysmon_event1, notepad_execution</group>
  </rule>

</group>
```
To match powershell events your rule could be following:
```xml
<group name="sysmon,">

  <rule id="255000" level="12">
     <if_group>sysmon_event1</if_group>
     <field name="win.eventdata.image">powershell.exe$|.ps1$|.ps2$</field>
     <description>Sysmon - Event 1: Bad exe: $(win.eventdata.image)</description>
     <group>sysmon_event1, powershell_execution</group>
  </rule>

</group>
```


The agent configuration is correct, you can still check that the manager receives the events by activating the option [logall](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#logall). In the manager's `ossec.conf` file, modify the `logall` option from `no` to `yes` and restart `wazuh-manager`. It will create `/var/ossec/log/archive/archive.log`. All events that are processed by [Analysisd](https://documentation.wazuh.com/current/user-manual/reference/daemons/ossec-analysisd.html) will be saved in this file. You can filter events by agent name and search for Sysmon event.

I hope it helps you. If you have further questions lets us know.

Best regards,
Eva

**Comment by jmora2** [comment]
Hi @Lopuiz,

Thank you for your assistance, I just happened to implement the new config changes and I do see some logs coming in the archive.log, but I do no see the alert being processed by the manager. I am using the sysmonconfig-export.xml file from the people at SwiftOnSecurity and I also tried the config for the notepad.exe and the powershell.exe, but the alert is still not triggering, would you mind having a look at the attached files.

Gruss,

Jeffry L. Mora

[wineventPS.txt](https://github.com/wazuh/wazuh-ruleset/files/3524223/wineventPS.txt)
[sysmonconfig-export.txt](https://github.com/wazuh/wazuh-ruleset/files/3524226/sysmonconfig-export.txt)
[archives.log](https://github.com/wazuh/wazuh-ruleset/files/3524227/archives.log)

**Comment by Lopuiz** [comment]
Hello!

In your rule the following line appears:
`<field name="win.eventdata.image">\powershell.exe||\.ps1||\.ps2</field>`
This regex does not work. Could you change it to this one?
`<field name="win.eventdata.image">powershell.exe$|.ps1$|.ps2$</field>`

If you've already modified it and it still doesn't work, I'd like to know how you test the rule. Using Wazuh App or using `ossec-logtest`.

Regards, 
Eva

**Comment by jmora2** [comment]
Hi,

I did as you requested, but I think that I am missing something still, I tried the following:

<field name="win.eventdata.image">powershell.exe$|.ps1$|.ps2$</field>
<field name="win.eventdata.image">powershell.exe</field>
<field name="win.eventdata.image">powershell.exe$</field>
<field name="win.eventdata.image">\\powershell.exe</field>

For the testing I do not use anything, but now that you mentioned the ossec-logtest I see the following:

**Phase 1: Completed pre-decoding.
...
**Phase 2: Completed decoding.
       No decoder matched.

That is even more interesting, because I would think that all the rules are in place.

Gruss,

Jeffry L. Mora

**Comment by Lopuiz** [comment]
Hello @jmora2 

`Ossec-logtest` only test rules and decoders in XML. Eventchannel has a decoder implemented in C, so Eventchannel events do not work in `ossec-logtest`.

I test the rule works and the alert generated is following:
```json
{

    "timestamp":"2019-08-22T08:15:57.307+0200",
    "rule":{
        "level":12,
        "description":"Sysmon - Event 1: Bad exe: C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
        "id":"255001",
        "firedtimes":1,
        "mail":true,
        "groups":[
            "testing",
            "sysmon_event1",
            " powershell_execution"
        ]
    },
    "agent":{
        "id":"001",
        "name":"WIN-6UJQ4IGFLK2",
        "ip":"10.0.2.15"
    },
    "manager":{
        "name":"lopezziur"
    },
    "id":"1566454557.62752",
    "full_log":"{\"win\":{\"system\":{\"providerName\":\"Microsoft-Windows-Sysmon\",\"providerGuid\":\"{5770385f-c22a-43e0-bf4c-06f5698ffbd9}\",\"eventID\":\"1\",\"version\":\"5\",\"level\":\"4\",\"task\":\"1\",\"opcode\":\"0\",\"keywords\":\"0x8000000000000000\",\"systemTime\":\"2019-08-22T06:15:55.960636900Z\",\"eventRecordID\":\"326\",\"processID\":\"2000\",\"threadID\":\"2540\",\"channel\":\"Microsoft-Windows-Sysmon/Operational\",\"computer\":\"WIN-6UJQ4IGFLK2\",\"severityValue\":\"INFORMATION\",\"message\":\"Process Create:\"},\"eventdata\":{\"utcTime\":\"2019-08-22 06:15:55.865\",\"processGuid\":\"{c9c7f4ca-331b-5d5e-0000-00101cb02100}\",\"processId\":\"96\",\"image\":\"C:\\\\Windows\\\\System32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe\",\"fileVersion\":\"10.0.17763.1 (WinBuild.160101.0800)\",\"description\":\"Windows PowerShell\",\"product\":\"Microsoft® Windows® Operating System\",\"company\":\"Microsoft Corporation\",\"originalFileName\":\"PowerShell.EXE\",\"commandLine\":\"\\\"C:\\\\Windows\\\\System32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe\\\"\",\"currentDirectory\":\"C:\\\\Users\\\\Administrator\\\\\",\"user\":\"WIN-6UJQ4IGFLK2\\\\Administrator\",\"logonGuid\":\"{c9c7f4ca-2e41-5d5e-0000-002072770300}\",\"logonId\":\"0x37772\",\"terminalSessionId\":\"1\",\"integrityLevel\":\"High\",\"hashes\":\"MD5=7353F60B1739074EB17C5F4DDDEFE239,SHA256=DE96A6E69944335375DC1AC238336066889D9FFC7D73628EF4FE1B1B160AB32C\",\"parentProcessGuid\":\"{c9c7f4ca-2e49-5d5e-0000-0010ca450400}\",\"parentProcessId\":\"2240\",\"parentImage\":\"C:\\\\Windows\\\\explorer.exe\",\"parentCommandLine\":\"C:\\\\Windows\\\\Explorer.EXE\"}}}",
    "decoder":{
        "name":"windows_eventchannel"
    },
    "data":{
        "win":{
            "system":{
                "providerName":"Microsoft-Windows-Sysmon",
                "providerGuid":"{5770385f-c22a-43e0-bf4c-06f5698ffbd9}",
                "eventID":"1",
                "version":"5",
                "level":"4",
                "task":"1",
                "opcode":"0",
                "keywords":"0x8000000000000000",
                "systemTime":"2019-08-22T06:15:55.960636900Z",
                "eventRecordID":"326",
                "processID":"2000",
                "threadID":"2540",
                "channel":"Microsoft-Windows-Sysmon/Operational",
                "computer":"WIN-6UJQ4IGFLK2",
                "severityValue":"INFORMATION",
                "message":"Process Create:"
            },
            "eventdata":{
                "utcTime":"2019-08-22 06:15:55.865",
                "processGuid":"{c9c7f4ca-331b-5d5e-0000-00101cb02100}",
                "processId":"96",
                "image":"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
                "fileVersion":"10.0.17763.1 (WinBuild.160101.0800)",
                "description":"Windows PowerShell",
                "product":"Microsoft® Windows® Operating System",
                "company":"Microsoft Corporation",
                "originalFileName":"PowerShell.EXE",
                "commandLine":"\"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\"",
                "currentDirectory":"C:\\Users\\Administrator\\",
                "user":"WIN-6UJQ4IGFLK2\\Administrator",
                "logonGuid":"{c9c7f4ca-2e41-5d5e-0000-002072770300}",
                "logonId":"0x37772",
                "terminalSessionId":"1",
                "integrityLevel":"High",
                "hashes":"MD5=7353F60B1739074EB17C5F4DDDEFE239,SHA256=DE96A6E69944335375DC1AC238336066889D9FFC7D73628EF4FE1B1B160AB32C",
                "parentProcessGuid":"{c9c7f4ca-2e49-5d5e-0000-0010ca450400}",
                "parentProcessId":"2240",
                "parentImage":"C:\\Windows\\explorer.exe",
                "parentCommandLine":"C:\\Windows\\Explorer.EXE"
            }
        }
    },
    "location":"EventChannel"

}
```
Could you check the following?

1. The following rule is in manager file `/var/ossec/etc/rules/local_rules.xml`:
```xml
<group name="testing,">

  <rule id="255000" level="12">
     <if_group>sysmon_event1</if_group>
     <field name="win.eventdata.image">powershell.exe$|.ps1$|.ps2$</field>
     <description>Sysmon - Event 1: Bad exe: $(win.eventdata.image)</description>
     <group>sysmon_event1, powershell_execution</group>
  </rule>

</group>
```
2. The following agent's configuration is on agent's `ossec.conf` or manager's `agent.conf`
```xml
<localfile>
   <location>Microsoft-Windows-Sysmon/Operational</location>
   <log_format>eventchannel</log_format>
</localfile>
```
3. Check the manager and agent was restartd after this configuration was added.

Then you can open `PowerShell` to generate the event and search the alerts in `/var/ossec/logs/alerts/alerts.json` . Note that old events may not be reported, the best thing to do is to generate new events.

Check it and let us know if it worked for you.

Best regards,
Eva

**Comment by jmora2** [comment]
Hi @Lopuiz,

That is very strange, I used the same rule in a file that I got, which is named 0332-credential_access_rules.xml, but it doesnt work, as soon as I have the same rule in the file local_rules.xml, it looks like it is working now, I see the alert coming into alert.log/json, which is even  more interesting now, it is that I do not see the rule in the agent. I do see other alerts under the client but not 255000. I also go to the tab Discover, but I do not see any logs with the keyword "powershell". Would it need another piece of configuration?

Btw, attached are the files log/json = alert

[alert.log.txt](https://github.com/wazuh/wazuh-ruleset/files/3529062/alert.log.txt)
[alert.json.txt](https://github.com/wazuh/wazuh-ruleset/files/3529063/alert.json.txt)

Regards,

Jeffry L. Mora

**Comment by Lopuiz** [comment]
Hi!

The issue was that the 255000 rule matches if any of the rules belonging to the `sysmon_event1` group (written in `0595-win-sysmon_rules.xml`) do. So, to works correctly this rule must be read by Wazuh after `sysmon_event1` rules.

If the alert is written in the file `alert.json` should also appear in Wazuh App.
Have you tried filtering by the rule id or agent id in tab Discover?

Regards,
Eva

**Comment by jmora2** [comment]
Hi,

This is my status so far, I am using the OVA-Wazuh, which it comes in CentOS and there I installed a rsyslog daemon to send the logs to another appliance, the other appliance is a SIEM and I use a json normalizer for the logs, because they come in json format, there I receive the logs in my SIEM and I can create alerts, etc.

At this point I can see the alert being generated in alerts.log and alerts.json and this is basically what i needed for my SIEM to properly work, but I do not see the alert in the Wazuh App, neither in the status of the agent, nor in the Discovery tab of Wazuh, as I mentioned for my SIEM solution is perfect what i have right now, but the alert in the wazuh app will be a "good to have" feature for me.

![456](https://user-images.githubusercontent.com/36069428/63509911-9cdc2380-c4dd-11e9-9d0b-40ffa567159b.JPG)

![789](https://user-images.githubusercontent.com/36069428/63510106-04926e80-c4de-11e9-9a04-c7d9e80af1d0.JPG)

Regards,

Jeffry L. Mora

**Comment by Lopuiz** [comment]
Hi!

Could you filter by rule id using `rule.id:255000`?
If it doesn't works. Could you filter by agent id in the Discover tab and lets us know if you see other recent alerts from the agent?

Best regards,
Eva

**Comment by Lopuiz** [comment]
Hi!

I hope you were able to visualize the alert in Kibana. I will close this issue for inactivity.
If you have further questions, let us know and we will help you.

Regards, Eva
