### ISSUE TITLE
Missing changes in CHANGELOG.md for 3.10 ruleset

### ISSUE THREAD

**Issue by iasdeoupxe** [wazuh/wazuh-ruleset#482]
The https://github.com/wazuh/wazuh-ruleset/blob/3.10/CHANGELOG.md currently contains the following entry:

> Add recon group to SSH rule (by @kravietz). (#323)

But when checking this PR there where quite a lot more changed in that besides adding the recon grup to the SSH rule:

94c979c29689fe1395f1c42ec5a46001c3b91409 (rules to detect untrusted kernel modules being loaded)
398f2a915590deac9f5051e5574455cd378e545d (rndg failure)
0ed79b3a25b9bef88fdffcfd684036a7ffc427f3 (add RAID and disk failure patterns)
1c4456742e36c27f4b680283f5bc7488fb9807bd (Fix conflict with mdadm decoder)
bc1ff617367b3b6b26c243abc0a79e7091dbf199 (Add systemd status=1/FAILURE rule)
a307b291f76943a1cac9b2b57c042fbcf02aad67 (Add ZFS error message)

**Comment by Lopuiz** [comment]
Hello @iasdeoupxe 

Thanks for your feedback.
We are going to add new entries to `changelog.md`.

Regards,
Eva

**Comment by Lopuiz** [comment]
Hi!

I close this issue as it has been fixed.

Regards,
Eva
