### ISSUE TITLE
Cylance Integration

### ISSUE THREAD

**Issue by joselopezrio** [wazuh/wazuh-ruleset#489]
### Integration

Hello team,  
it would be nice to have Cylance decoders/rules in order to add them to our ruleset. 

Cylance is a security feature useful to block emerging threats: https://www.cylance.com/en-us/why-cylance.html. 

Regards,
Jose Manuel Lopez.

**Comment by jcruzlp** [comment]
These changes were added here: https://github.com/wazuh/wazuh/pull/9047
