### ISSUE TITLE
README Modification

### ISSUE THREAD

**Issue by joselopezrio** [wazuh/wazuh-ruleset#491]
### Issue
Hello team,

It would be helpful introducing in the ruleset `README` a block to specify how to create a Pull Request to add `decoders/rules` for new integrations. This could include all the archives needed to pass the ruleset automatic tests, so as the title format of the `XML` files needed.

Regards,
Jose Manuel Lopez

**Comment by MiguelCasaresRobles** [comment]
Solved: https://github.com/wazuh/wazuh-ruleset/pull/494
