### ISSUE TITLE
Network vulnerability assesment

### ISSUE THREAD

**Issue by WazuhUser** [wazuh/wazuh-ruleset#497]
Hi, 

Our company is trying to cover network vulnerability area with opensource tools. 
We are using Openvas as scanner, and Vulnwhisperer (https://github.com/HASecuritySolutions/VulnWhisperer) project to be drawed in Kibana scan results. 
We think, it would be delightful if Wazuh could integrate network vulnerability tools in order to have almost all enviroment motnitorized.

The integration, besides could have the functionality to see alerts in kibana, could implemente other like scans machines with some alerts from the interface and so. 

Thanks in advance for your time and kind regards,

**Comment by Lopuiz** [comment]
Hello Donetz8,

We note your feedback.

At the moment, there is no integration to OpenVas neither VulnWhisperer but you can configure Wazuh to receive logs via Syslog or read a log file from these tools. Also, you can create custom rules and decoders or use the exists rules to generate alerts.

I hope it helps you.

Best regards,
Eva

**Comment by Lopuiz** [comment]
Hello,

I am going to close this issue for inactivity.

Regards,
Eva

**Comment by Cyphercoda** [comment]
and @WazuhUser can you please tell me how to do that?

**Comment by luislopezsanchez** [comment]
> Hello Donetz8,
> 
> We take note of your feedback.
> 
> At the moment, there is no integration to OpenVas neither VulnWhisperer but you can configure Wazuh to receive logs via Syslog or read a log file from these tools. Also, you can create custom rules and decoders or use the exists rules to generate alerts.
> 
> I hope it helps you.
> 
> Best regards, Eva

Hola, podría compartir los pasos de como hacer esta integración? he buscado por toda la web algun material y algunas personas como usted mencionan que se puede hacer pero nadie dice como. Podría ayudar?
