### ISSUE TITLE
Fortinet Decoders doesn't work properly if log comes from FortiAnalyzer.

### ISSUE THREAD

**Issue by phpsystems** [wazuh/wazuh-ruleset#50]
Looking at 0390-fortigate_rules.xml: 
Bottom of the file: 

    
    <rule id="81628" level="11">
        <if_sid>81603</if_sid>
        <match>attack</match>
        <action>detected</action>
        <description>Fortigate Attack Detected</description>
        <group>attack,</group>
    </rule>

    <rule id="81629" level="3">
        <if_sid>81603</if_sid>
        <match>attack</match>
        <action>dropped</action>
        <description>Fortigate Attack Dropped</description>
        <group>attack,</group>
    </rule>

These work for the samples provided. However, when tested with an example from a fortiAnalyzer, action becomes alert (appears to match the level, rather than action):

> Test Message :
> 
> Jun 20 10:13:47 10.0.0.21 severity=critical from=FORTAN.TEST(FAZ-VM00000XXXXX) trigger=IPS - Critical Severity log="date=2017-06-20 time=10:16:52 clusterid=FGHA001893200000_CID logver=52 itime=1497950025 devname=FWD001 devid=FG800C3914800000 logid=16384 type=utm subtype=ips eventtype=signature level=alert vd=EXT_SVCS severity=critical srcip=10.1.10.104 dstip=10.0.0.80 srcintf="EXTRNL" dstintf="PUBDMZ" sessionid=3691241729 action=dropped proto=6 service=HTTP attack="Apache.Struts.Jakarta.Multipart.Parser.Code.Execution" srcport=48196 dstport=80 direction=outgoing attackid=43745 profile="IPS_DEFAULT" ref="http://www.fortinet.com/ids/VID43745" user="" incidentserialno=755485169 msg="applications3: Apache.Struts.Jakarta.Multipart.Parser.Code.Execution," crscore=50 crlevel=critical"
> 
> 

**Phase 1: Completed pre-decoding.
       full event: 'Jun 20 10:13:47 10.0.0.21 severity=critical from=FORTAN.TEST(FAZ-VM00000XXXXX) trigger=IPS - Critical Severity log="date=2017-06-20 time=10:16:52 clusterid=FGHA001893200000_CID logver=52 itime=1497950025 devname=FWD001 devid=FG800C3914800000 logid=16384 type=utm subtype=ips eventtype=signature level=alert vd=EXT_SVCS severity=critical srcip=10.1.10.104 dstip=10.0.0.80 srcintf="EXTRNL" dstintf="PUBDMZ" sessionid=3691241729 action=dropped proto=6 service=HTTP attack="Apache.Struts.Jakarta.Multipart.Parser.Code.Execution" srcport=48196 dstport=80 direction=outgoing attackid=43745 profile="IPS_DEFAULT" ref="http://www.fortinet.com/ids/VID43745" user="" incidentserialno=755485169 msg="applications3: Apache.Struts.Jakarta.Multipart.Parser.Code.Execution," crscore=50 crlevel=critical"'
       hostname: '10.0.0.21'
       program_name: '(null)'
       log: 'severity=critical from=FORTAN.TEST(FAZ-VM00000XXXXX) trigger=IPS - Critical Severity log="date=2017-06-20 time=10:16:52 clusterid=FGHA001893200000_CID logver=52 itime=1497950025 devname=FWD001 devid=FG800C3914800000 logid=16384 type=utm subtype=ips eventtype=signature level=alert vd=EXT_SVCS severity=critical srcip=10.1.10.104 dstip=10.0.0.80 srcintf="EXTRNL" dstintf="PUBDMZ" sessionid=3691241729 action=dropped proto=6 service=HTTP attack="Apache.Struts.Jakarta.Multipart.Parser.Code.Execution" srcport=48196 dstport=80 direction=outgoing attackid=43745 profile="IPS_DEFAULT" ref="http://www.fortinet.com/ids/VID43745" user="" incidentserialno=755485169 msg="applications3: Apache.Struts.Jakarta.Multipart.Parser.Code.Execution," crscore=50 crlevel=critical"'

**Phase 2: Completed decoding.
       decoder: 'fortigate-firewall-v5'
       action: 'alert'
       srcip: '10.1.10.104'
       dstip: '10.0.0.80'
       srcport: '48196'
       dstport: '80'
       extra_data: '"applications3: Apache.Struts.Jakarta.Multipart.Parser.Code.Execution," crscore=50 crlevel=critical"'

**Phase 3: Completed filtering (rules).
       Rule id: '81603'
       Level: '0'
       Description: 'Fortigate messages grouped.'

The Action being set to alert seems to be the issue, probably in the decoder.

**Comment by jesuslinares** [comment]
Hi @phpsystems ,

I fixed the decoder: https://github.com/wazuh/wazuh-ruleset/commit/ffb19b382de334402befc40884db0bb082997042

_ossec-logtest_
```
Jun 20 10:13:47 10.0.0.21 severity=critical from=FORTAN.TEST(FAZ-VM00000XXXXX) trigger=IPS - Critical Severity log="date=2017-06-20 time=10:16:52 clusterid=FGHA001893200000_CID logver=52 itime=1497950025 devname=FWD001 devid=FG800C3914800000 logid=16384 type=utm subtype=ips eventtype=signature level=alert vd=EXT_SVCS severity=critical srcip=10.1.10.104 dstip=10.0.0.80 srcintf="EXTRNL" dstintf="PUBDMZ" sessionid=3691241729 action=dropped proto=6 service=HTTP attack="Apache.Struts.Jakarta.Multipart.Parser.Code.Execution" srcport=48196 dstport=80 direction=outgoing attackid=43745 profile="IPS_DEFAULT" ref="http://www.fortinet.com/ids/VID43745" user="" incidentserialno=755485169 msg="applications3: Apache.Struts.Jakarta.Multipart.Parser.Code.Execution," crscore=50 crlevel=critical"'

**Phase 2: Completed decoding.
       decoder: 'fortigate-firewall-v5'
       status: 'critical'
       srcip: '10.1.10.104'
       dstip: '10.0.0.80'
       action: 'dropped'
       srcport: '48196'
       dstport: '80'
       extra_data: '"applications3: Apache.Struts.Jakarta.Multipart.Parser.Code.Execution," crscore=50 crlevel=critical"''

**Phase 3: Completed filtering (rules).
       Rule id: '81629'
       Level: '3'
       Description: 'Fortigate Attack Dropped'
**Alert to be generated.
```

is that what you expected?.

Thanks for the feedback!

**Comment by phpsystems** [comment]
Hi,

Looks good to me.

Thanks.

**Comment by jesuslinares** [comment]
Great!.

Thank you.
