### ISSUE TITLE
Windows Authentication Failures don't trigger brute force rules

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-ruleset#504]
Since authentication failure rules for windows have a group mapping of `win_authentication_failure` instead of `authentication_failure` they will not trigger general rules like rule `40112`

There are two windows specific rule for brute force attacks, however these don't provide much value.

I propose changing all references to `win_authentication_failed` to `authentication_failed` and removing rule `18152` as it is already covered by rule 40111, and changing rule `60204` so it matches the group `authentication_failed`.

**Comment by 72nomada** [comment]
Close as Windows rules and detection behavior is being rework
