### ISSUE TITLE
rookit_files outdated

### ISSUE THREAD

**Issue by aderumier** [wazuh/wazuh-ruleset#515]
Hi,
rookit_files don't seem to have been updated since 2016.

I have begin to work to update it, from rkunter git and other sources.

https://github.com/aderumier/wazuh-ruleset/tree/rootkit-update

I'll try to make a pull request soon when I'll finished to update all.

**Comment by Zenidd** [comment]
Hello @aderumier,

> rookit_files don't seem to have been updated since 2016.

That is really nice work. We really appreciate your contribution. When you have finished extending the rootkit files and our workflow allows it, we will be happy to review and if possible add them to the Wazuh project.

Let us know if you need some guidance and thank you again for your contribution!

Regards, JP Sáez
