### ISSUE TITLE
Missing IP data.srcip

### ISSUE THREAD

**Issue by Koploseus** [wazuh/wazuh-ruleset#524]
Hello,

I have installed Wazuh yesterday to get the log of my machine.
Its working well, the only problem is : 

-For an RDP Bruteforce Attack i don't get the IP of the attackers.

I use the default ruleset

**Comment by Zenidd** [comment]
Hello, 

I'm closing this issue as we are already discussing the same topic in https://github.com/wazuh/wazuh/issues/4234

Regards, JP Sáez
