### ISSUE TITLE
Windows Event 4662 alert

### ISSUE THREAD

**Issue by perfecthoogie** [wazuh/wazuh-ruleset#538]
Morning All, 

we are currently seeing a very large amount of alerts for object access failures for windows alert 4662 for the following object types. 
is there a way of suppressing these type of alerts within Wazuh based on the object type, we don't want to disable all 4662 alerts as some of these object audits are important for us to track/monitor. 

computer | bf967a86-0de6-11d0-a285-00aa003049e2
User | bf967aba-0de6-11d0-a285-00aa003049e2 
Dns-Node | e0fa1e8c-9b45-11d0-afdd-00c04fd930c9
Domain-DNS | 19195a5b-6da0-11d0-afd3-00c04fd930c9
Container  | bf967a8b-0de6-11d0-a285-00aa003049e2
Groups | bf967a9c-0de6-11d0-a285-00aa003049e2

Many thanks 

Rob

**Comment by Lopuiz** [comment]
Hello Rob,

You can use a CDB list to filters these events. To know more about it follow the link:
[Using CDB list](https://documentation.wazuh.com/3.10/user-manual/ruleset/cdb-list.html)

To show you an example of how to modify the rule I would like to know [the format in which events are collected](https://documentation.wazuh.com/3.10/user-manual/capabilities/log-data-collection/how-to-collect-wlogs.html) (Eventlog or Eventchannel) and the Wazuh rule's ID which matches it.

Also, I would like to know the field to filters the events. The event 4662 doesn't mention the fields you put previously.
[4662(S, F): An operation was performed on an object.](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4662)

Best regards,
Eva

**Comment by perfecthoogie** [comment]
Many thanks for your reply Eva, 

in answer to your questions we are currently using the event channel  format
  <location>Security</location>
    <log_format>eventchannel</log_format>

in terns if the field that this is using is data.win.eventdata.objectType 
ive uploaded a copy of the json that i created by the system for the alert. 

[Audit FAilure Event Json.txt](https://github.com/wazuh/wazuh-ruleset/files/3945463/Audit.FAilure.Event.Json.txt)

**Comment by Lopuiz** [comment]
Hello @perfecthoogie 


The rule which fires is the rule number 60104:

https://github.com/wazuh/wazuh-ruleset/blob/de407b8c0038b95641029346bf86a7de4049c270/rules/0580-win-security_rules.xml#L43-L49


You can find it in `/var/ossec/ruleset/rules/0580-win-security_rules.xml`

This rule can be overwritten to filter some events. You can do as follow:

```xml
<!-- Local rules -->

<!-- Modify it at your will. -->
<!-- Copyright (C) 2015-2019, Wazuh Inc. -->

<!-- Example -->

<group name="windows, windows_security,">

  <rule id="60104" level="5" overwrite="yes">
    <if_sid>60001</if_sid>
    <field name="win.system.severityValue">^AUDIT_FAILURE$|^failure$</field>
    <list field="win.eventdata.objectType" lookup="not_match_key">etc/lists/objectType</list>
    <description>Windows audit failure event</description>
    <group>pci_dss_10.6.1,gdpr_IV_35.7.d,hipaa_164.312.b,nist_800_53_AU.6,</group>
    <options>no_full_log</options>
  </rule>

</group>

```

The rule overwritten must be added in `/var/ossec/etc/rules/local_rules.xml`.

Then, create file `/var/ossec/etc/lists/objectType` and add all objectType values you don't want to be notified.

For example:
```
%{bf967a86-0de6-11d0-a285-00aa003049e2}:
%{bf967a86-0de6-12d0-a285-00aa003049a3}:
%{bf967a86-0de6-13d0-a285-00aa003049c7}:
```

Please, note values must have double points at the end.

Search ruleset block configuration in `ossec.conf` and add the list:

```xml
  ....

  <ruleset>
    <!-- Default ruleset -->
    <decoder_dir>ruleset/decoders</decoder_dir>
    <rule_dir>ruleset/rules</rule_dir>
    <rule_exclude>0215-policy_rules.xml</rule_exclude>
    <list>etc/lists/audit-keys</list>
    <list>etc/lists/amazon/aws-eventnames</list>
    <list>etc/lists/security-eventchannel</list>
    <list>etc/lists/objectType</list>

    <!-- User-defined ruleset -->
    <decoder_dir>etc/decoders</decoder_dir>
    <rule_dir>etc/rules</rule_dir>
  </ruleset>

  ....
```

Finally, restart Wazuh.

I enclose some links to our documentation which can be useful for you:
+ [Using CDB list](https://documentation.wazuh.com/3.10/user-manual/ruleset/cdb-list.html)
+ [Rules syntax](https://documentation.wazuh.com/3.10/user-manual/ruleset/ruleset-xml-syntax/rules.html)
+ [Custom rules and decoders](https://documentation.wazuh.com/3.10/user-manual/ruleset/custom.html)

I hope it helps you. If you have further questions lets us know.
Please, for the next questions, subscribe to our mailing list or join on slack.
[Wazuh community](https://wazuh.com/community/)

Best regards,
Eva

**Comment by Lopuiz** [comment]
Hello,

I am going to close this issue for inactivity.

Regards,
Eva
