### ISSUE TITLE
GPG13

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh-ruleset#54]
Hello Wazuh Team,
I have recently gone through the entire rules set and applied GPG13 PMC to all applicable rules.
Would you guys be interested in PR for them. I've essentially added gpg13 related groups, similar to the PCI ones.

GPG13 is similiar to PCI and it is actively used in the UK. A reference is available at https://www.ncsc.gov.uk/guidance/protective-monitoring-hmg-ict-systems-gpg-13

**Comment by jesuslinares** [comment]
It is awesome!. 

Please, send us the PR, I'm sure that it will be very useful for a lot users.

 Thanks for your valuable collaboration!

**Comment by rossengeorgiev** [comment]
Hi @jesuslinares, its awesome this got merge, but are there any plans to support it going forward? I noticed there are rules in v3.0 branch that are new for example.

**Comment by jesuslinares** [comment]
It was included in Wazuh v3.0.

Thanks for this great contribution!
