### ISSUE TITLE
The default ruleset is too noisy ( email alerts ) 

### ISSUE THREAD

**Issue by DanielMorLoz** [wazuh/wazuh-ruleset#546]
Hello team,

The rule's option `alert_by_email` makes a rule send an email regardless of its level, by default, there are 35 rules with this option enabled:
```
501, 502, 503, 504, 505, 5305, 5403, 10100, 7201, 14203, 18119, 18146, 18147, 7514, 7718, 19122, 19123, 31122, 31123, 31412, 31413, 31421, 31430, 81607, 81608, 81611, 81615, 81619, 81802, 81804, 60119, 60611, 60612, 62616, 63616
```
I think it doesn't make sense to enable this option in our ruleset by default. It should be mentioned in our documentation to allow the users to enable this option whenever they want to use it.

**Comment by MiguelCasaresRobles** [comment]
Hello team,

This PR solves it: https://github.com/wazuh/wazuh-ruleset/pull/559
