### ISSUE TITLE
HELP WITH CUSTOM RULES

### ISSUE THREAD

**Issue by Aldugama** [wazuh/wazuh-ruleset#561]
Hello, I would really need a hand formulating custom fortigate rules. The following files are the logs to help in the definition of the rules.

[IPS.txt](https://github.com/wazuh/wazuh-kibana-app/files/4185572/IPS.txt)
[TRAFFIC.txt](https://github.com/wazuh/wazuh-kibana-app/files/4185574/TRAFFIC.txt)
[VIRUS.txt](https://github.com/wazuh/wazuh-kibana-app/files/4185575/VIRUS.txt)
[WEB FILTER.txt](https://github.com/wazuh/wazuh-kibana-app/files/4185576/WEB.FILTER.txt)
[ANOMAlY.txt](https://github.com/wazuh/wazuh-kibana-app/files/4185577/ANOMAlY.txt)
[EVENT.txt](https://github.com/wazuh/wazuh-kibana-app/files/4185578/EVENT.txt)

**Comment by Lopuiz** [comment]
Hello @Aldugama, 

I hope that PR is useful for you. I am going to close this issue for inactivity.
If you have further questions, join our mailing list or Slack channel.
[Wazuh Community](https://wazuh.com/community/)

Best regards,
Eva
