### ISSUE TITLE
How to set the customized rule ??

### ISSUE THREAD

**Issue by SoldierProgrammer** [wazuh/wazuh-ruleset#564]
Hi team,
Is there any guide to interpret the labels in the ruleset, for example:
<rule id="501" level="3">
    <if_sid>500</if_sid>
    <if_fts />
    <options>alert_by_email</options>
    <match>Agent started</match>
    <description>New ossec agent connected.</description>
    <group>pci_dss_10.6.1,gpg13_10.1,gdpr_IV_35.7.d,hipaa_164.312.b,nist_800_53_AU.6,</group>
  </rule>

  <rule id="202" level="7">
    <if_sid>201</if_sid>
    <field name="level">%</field>
    <description>Agent event queue is $(level) full.</description>
    <group>agent_flooding,gdpr_IV_35.7.d,</group>
  </rule>

  <rule id="200" level="0">
    <decoded_as>wazuh</decoded_as>
    <description>Grouping of wazuh rules.</description>
  </rule>

**Comment by Lopuiz** [comment]
Hello @SoldierProgrammer,

Here you will find our Ruleset documentation: [User manual > Ruleset](https://documentation.wazuh.com/3.11/user-manual/ruleset/index.html).
The section you need is [Rules syntax](https://documentation.wazuh.com/3.11/user-manual/ruleset/ruleset-xml-syntax/rules.html).

I hope it helps you. If you have further questions, join our mailing list or Slack channel. To subscribe to our community follow the link: [Wazuh Community](https://wazuh.com/community/).

Best regards,
Eva

**Comment by SoldierProgrammer** [comment]
Hello @Lopuiz 
Thank you very much. That's what I wanted.
Best regards,
Daik
