### ISSUE TITLE
custom_fortigate decoder has no match help me 

### ISSUE THREAD

**Issue by coopjab** [wazuh/wazuh-ruleset#566]
I’m writing set of decoders for firewall logs ...
Iam able to achieve it ...
phrase 1 decoding successful  and coming to phrase two ..it states that “no decoder matched” the log and my decoding cli is attached below ...
can u pls help me with this decoder where I did wrong 
![Screenshot (77)](https://user-images.githubusercontent.com/36020960/75649255-94c52380-5c78-11ea-9fa8-bba106c2365f.png)
![Screenshot (78)](https://user-images.githubusercontent.com/36020960/75649265-98f14100-5c78-11ea-98a6-c03be5cc1904.png)
![Screenshot (80)](https://user-images.githubusercontent.com/36020960/75649300-b6260f80-5c78-11ea-8c25-d7cdaf1ee3a0.png)

**Comment by Lopuiz** [comment]
Hello @coopjab 
 
There are some mistakes in your custom decoders. Maybe following decoders match with your log:
```xml
<decoder name="fortigate-firewall-v6">
        <prematch>date=\S+ time=\S+ devname="\S+" devid="FG\w+" logid="\S+"</prematch>
</decoder>

<decoder name="fortigate-firewall-v6-logs">
        <parent>fortigate-firewall-v6</parent>
        <regex>type=(\S+) subtype=(\S+) level=(\S+) vd=(\S+) eventtime=(\d+) tz="(\d+)"</regex>
        <order>type, subtype, level, vd, eventtime, tz</order>
</decoder>
```

![imagen](https://user-images.githubusercontent.com/17710550/75668313-714ea880-5c79-11ea-8b3e-f304b6c5ab91.png)

This PR can useful for you [PR 516](https://github.com/wazuh/wazuh-ruleset/pull/516). It's an update of Fortigate rules and decoders

I hope it helps you.

Best regards,
Eva

**Comment by coopjab** [comment]
> 
> 
> Hello @coopjab
> 
> There are some mistakes in your custom decoders. Maybe following decoders match with your log:
> 
> ```
> <decoder name="fortigate-firewall-v6">
>         <prematch>date=\S+ time=\S+ devname="\S+" devid="FG\w+" logid="\S+"</prematch>
> </decoder>
> 
> <decoder name="fortigate-firewall-v6-logs">
>         <parent>fortigate-firewall-v6</parent>
>         <regex>type=(\S+) subtype=(\S+) level=(\S+) vd=(\S+) eventtime=(\d+) tz="(\d+)"</regex>
>         <order>type, subtype, level, vd, eventtime, tz</order>
> </decoder>
> ```
> 
> ![imagen](https://user-images.githubusercontent.com/17710550/75668313-714ea880-5c79-11ea-8b3e-f304b6c5ab91.png)
> 
> This PR can useful for you [PR 516](https://github.com/wazuh/wazuh-ruleset/pull/516). It's an update of Fortigate rules and decoders
> 
> I hope it helps you.
> 
> Best regards,
> Eva

i will test whether its working or not and let u know man thanks a lot for open this again

**Comment by coopjab** [comment]
now i can see the firewall logs ... but i cant see the logs from the agents connected to firewall?

**Comment by coopjab** [comment]
is this correct rule to trigger a alert in wazuh....from other agents connected to firewall
![Screenshot (81)](https://user-images.githubusercontent.com/36020960/75672054-eb952200-5ca5-11ea-9ce8-91c73ca4b9cf.png)

**Comment by Lopuiz** [comment]
Hello again,

The second rule only match if rule 81602 match. Following rules can be useful for you:

```xml
<group name="fortigate-firewall-v6">
        <rule id="100011" level="0">
                <decoded_as>fortigate-firewall-v6</decoded_as>
                <description>Fortigate firewall</description>
        </rule>

        <rule id="100012" level="1">
                <if_sid>100011</if_sid>
                <field name="level">alert</field>
                <description>Fortigate alert</description>
        </rule>

</group>
```

Logtest output:
```
root@lopezziur:/var/ossec# bin/ossec-logtest 
2020/03/02 12:33:19 ossec-testrule: INFO: Started (pid: 14477).
ossec-testrule: Type one log per line.

date=2018-05-31 time=08:58:56 devname="BA-RSYS-FW" devid="FG600C3912803212" logid="0211008192" type="utm" subtype="virus" level="alert" vd="BA-EXORA" eventtime=1527737336 tz="1245643" msg="File is infected." action="blocked" service="HTTP" sessionid=377413095 srcip=172.24.12.52 dstip=164.100.80.203 srcport=64982 dstport=80 srcintf="port5" srcintfrole="undefined" dstintf="port3" dstintfrole="wan" policyid=108 proto=6 direction="incoming" filename="FrontPageImgHandler.ashx" quarskip="File-was-not-quarantined." virus="Malware_Generic.P0" dtype="Virus" ref="http://www.fortinet.com/ve?vn=Malware_Generic.P0" virusid=7024603 url="http://www.karsec.gov.in/FrontPageImgHandler.ashx?id=12" profile="Web-Browsing" agent="Chrome/66.0.3359.181" analyticscksum="a9165dbae34e6e2952270536e95a2bb154dff0cfcdf41315f0796ee14b36123b" analyticssubmit="false" crscore=50 crlevel="critical"


**Phase 1: Completed pre-decoding.
       full event: 'date=2018-05-31 time=08:58:56 devname="BA-RSYS-FW" devid="FG600C3912803212" logid="0211008192" type="utm" subtype="virus" level="alert" vd="BA-EXORA" eventtime=1527737336 tz="1245643" msg="File is infected." action="blocked" service="HTTP" sessionid=377413095 srcip=172.24.12.52 dstip=164.100.80.203 srcport=64982 dstport=80 srcintf="port5" srcintfrole="undefined" dstintf="port3" dstintfrole="wan" policyid=108 proto=6 direction="incoming" filename="FrontPageImgHandler.ashx" quarskip="File-was-not-quarantined." virus="Malware_Generic.P0" dtype="Virus" ref="http://www.fortinet.com/ve?vn=Malware_Generic.P0" virusid=7024603 url="http://www.karsec.gov.in/FrontPageImgHandler.ashx?id=12" profile="Web-Browsing" agent="Chrome/66.0.3359.181" analyticscksum="a9165dbae34e6e2952270536e95a2bb154dff0cfcdf41315f0796ee14b36123b" analyticssubmit="false" crscore=50 crlevel="critical"'
       timestamp: '(null)'
       hostname: 'lopezziur'
       program_name: '(null)'
       log: 'date=2018-05-31 time=08:58:56 devname="BA-RSYS-FW" devid="FG600C3912803212" logid="0211008192" type="utm" subtype="virus" level="alert" vd="BA-EXORA" eventtime=1527737336 tz="1245643" msg="File is infected." action="blocked" service="HTTP" sessionid=377413095 srcip=172.24.12.52 dstip=164.100.80.203 srcport=64982 dstport=80 srcintf="port5" srcintfrole="undefined" dstintf="port3" dstintfrole="wan" policyid=108 proto=6 direction="incoming" filename="FrontPageImgHandler.ashx" quarskip="File-was-not-quarantined." virus="Malware_Generic.P0" dtype="Virus" ref="http://www.fortinet.com/ve?vn=Malware_Generic.P0" virusid=7024603 url="http://www.karsec.gov.in/FrontPageImgHandler.ashx?id=12" profile="Web-Browsing" agent="Chrome/66.0.3359.181" analyticscksum="a9165dbae34e6e2952270536e95a2bb154dff0cfcdf41315f0796ee14b36123b" analyticssubmit="false" crscore=50 crlevel="critical"'

**Phase 2: Completed decoding.
       decoder: 'fortigate-firewall-v6'
       type: '"utm"'
       subtype: '"virus"'
       level: '"alert"'
       vd: '"BA-EXORA"'
       eventtime: '1527737336'
       tz: '1245643'

**Phase 3: Completed filtering (rules).
       Rule id: '100012'
       Level: '1'
       Description: 'Fortigate alert'
```

**Comment by coopjab** [comment]
thanks a alot it was really helpful ..
can i know which is default alert level ??

**Comment by Lopuiz** [comment]
Hello @coopjab 

Rules with a level higher than two will generate alerts. Is that what you mean?

Regarding your comment, you should download those files and replace them to Fortigate rules and decoders files found in `/var/ossec/ruleset`.

Best regards,
Eva

**Comment by coopjab** [comment]
can u provide donwload link it seems that is not working ..
i just copied text and pasted in the ruleset folder with name 0100- fortigate decoders

**Comment by Lopuiz** [comment]
You should download branch `3.11-fortigate_ruleset_update` and move the Fortigate rules and decoders files to `/var/ossec/ruleset`
