### ISSUE TITLE
Problem with Windows rules

### ISSUE THREAD

**Issue by John33000** [wazuh/wazuh-ruleset#567]
Hi, 
I have Wazuh 3.10.2 and Elasticsearch 7.4 and Filebeat 7.4 too.

The Rules 60109 of Windows "User account was created or Enabled" detect if Local account was created in the server. I installed Wazuh Agent in DC, and when we created Active Directory account (no local account) I receive alert from wazuh who said : A user account was created or Enabled... But is not a Local account. And in the windows log we don't see difference between domain account or local account. 

Best Regards

**Comment by FernandoCP** [comment]
Hi @John33000!

The information that our system takes out is directly taken from the events provided by Microsoft. And according to the information they give this event generates on domain controllers, member servers, and workstations.

I attach the documentation that Microsoft gives about the events of this rule.

https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4722
https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4720

I hope this helps you.
Best regards, Fernando.

**Comment by John33000** [comment]
Hi, Thank you for your reply.

Best Regards
