### ISSUE TITLE
can't see web traffic in wazuh from fortigate firewall 

### ISSUE THREAD

**Issue by coopjab** [wazuh/wazuh-ruleset#568]
i tried decoders and all but still I'm not able to see web traffic between the connected machine to my firewall but i can see web traffic in tcpdump command please help me

**Comment by Lopuiz** [comment]
Hello,

You can enable [logall](https://documentation.wazuh.com/3.11/user-manual/reference/ossec-conf/global.html#logall) option to check Wazuh receives logs.
This option lets Analysisd writes in `/var/ossec/logs/archives/archives.log` all logs it processes.

If you don't see any Fortigate logs there, Wazuh doesn't receive Fortigate logs. Otherwise, the rules and decoders don't work.

I hope it helps you. To further questions you can join our [community](https://wazuh.com/community/).

Best regards,
Eva

**Comment by coopjab** [comment]
I see logs i see traffic logs ...
how can i see that cli logs in wazuh GUI ????
and my decoders are correct they are default decoder

**Comment by Lopuiz** [comment]
Hello @coopjab 

Could you send us a log example? It's possible the default decoders don't match the format of your logs.

On your previous issue, I send you decoders examples:
```xml
<decoder name="fortigate-firewall-v6">
        <prematch>date=\S+ time=\S+ devname="\S+" devid="FG\w+" logid="\S+"</prematch>
</decoder>

<decoder name="fortigate-firewall-v6-logs">
        <parent>fortigate-firewall-v6</parent>
        <regex>type=(\S+) subtype=(\S+) level=(\S+) vd=(\S+) eventtime=(\d+) tz="(\d+)"</regex>
        <order>type, subtype, level, vd, eventtime, tz</order>
</decoder>
```

But decoders only decode some useful information. To generate alerts you have to create rules.
A rule which works with previous decoders could be as follow:

```xml
<group name="fortigate-firewall-v6">

        <rule id="100011" level="3">
                <decoded_as>fortigate-firewall-v6</decoded_as>
                <description>Fortigate firewall log</description>
        </rule>

</group>
```
You can use following log to check it:

> date=2018-05-31 time=08:58:56 devname="BA-RSYS-FW" devid="FG600C3912803212" logid="0211008192" type="utm" subtype="virus" level="alert" vd="BA-EXORA" eventtime=1527737336 tz="1245643" msg="File is infected." action="blocked" service="HTTP" sessionid=377413095 srcip=172.24.12.52 dstip=164.100.80.203 srcport=64982 dstport=80 srcintf="port5" srcintfrole="undefined" dstintf="port3" dstintfrole="wan" policyid=108 proto=6 direction="incoming" filename="FrontPageImgHandler.ashx" quarskip="File-was-not-quarantined." virus="Malware_Generic.P0" dtype="Virus" ref="http://www.fortinet.com/ve?vn=Malware_Generic.P0" virusid=7024603 url="http://www.karsec.gov.in/FrontPageImgHandler.ashx?id=12" profile="Web-Browsing" agent="Chrome/66.0.3359.181" analyticscksum="a9165dbae34e6e2952270536e95a2bb154dff0cfcdf41315f0796ee14b36123b" analyticssubmit="false" crscore=50 crlevel="critical"

The Logtest output is:

```
root@lopezziur:/var/ossec# bin/ossec-logtest 
2020/03/05 08:51:16 ossec-testrule: INFO: Started (pid: 8124).
ossec-testrule: Type one log per line.

date=2018-05-31 time=08:58:56 devname="BA-RSYS-FW" devid="FG600C3912803212" logid="0211008192" type="utm" subtype="virus" level="alert" vd="BA-EXORA" eventtime=1527737336 tz="1245643" msg="File is infected." action="blocked" service="HTTP" sessionid=377413095 srcip=172.24.12.52 dstip=164.100.80.203 srcport=64982 dstport=80 srcintf="port5" srcintfrole="undefined" dstintf="port3" dstintfrole="wan" policyid=108 proto=6 direction="incoming" filename="FrontPageImgHandler.ashx" quarskip="File-was-not-quarantined." virus="Malware_Generic.P0" dtype="Virus" ref="http://www.fortinet.com/ve?vn=Malware_Generic.P0" virusid=7024603 url="http://www.karsec.gov.in/FrontPageImgHandler.ashx?id=12" profile="Web-Browsing" agent="Chrome/66.0.3359.181" analyticscksum="a9165dbae34e6e2952270536e95a2bb154dff0cfcdf41315f0796ee14b36123b" analyticssubmit="false" crscore=50 crlevel="critical"


**Phase 1: Completed pre-decoding.
       full event: 'date=2018-05-31 time=08:58:56 devname="BA-RSYS-FW" devid="FG600C3912803212" logid="0211008192" type="utm" subtype="virus" level="alert" vd="BA-EXORA" eventtime=1527737336 tz="1245643" msg="File is infected." action="blocked" service="HTTP" sessionid=377413095 srcip=172.24.12.52 dstip=164.100.80.203 srcport=64982 dstport=80 srcintf="port5" srcintfrole="undefined" dstintf="port3" dstintfrole="wan" policyid=108 proto=6 direction="incoming" filename="FrontPageImgHandler.ashx" quarskip="File-was-not-quarantined." virus="Malware_Generic.P0" dtype="Virus" ref="http://www.fortinet.com/ve?vn=Malware_Generic.P0" virusid=7024603 url="http://www.karsec.gov.in/FrontPageImgHandler.ashx?id=12" profile="Web-Browsing" agent="Chrome/66.0.3359.181" analyticscksum="a9165dbae34e6e2952270536e95a2bb154dff0cfcdf41315f0796ee14b36123b" analyticssubmit="false" crscore=50 crlevel="critical"'
       timestamp: '(null)'
       hostname: 'lopezziur'
       program_name: '(null)'
       log: 'date=2018-05-31 time=08:58:56 devname="BA-RSYS-FW" devid="FG600C3912803212" logid="0211008192" type="utm" subtype="virus" level="alert" vd="BA-EXORA" eventtime=1527737336 tz="1245643" msg="File is infected." action="blocked" service="HTTP" sessionid=377413095 srcip=172.24.12.52 dstip=164.100.80.203 srcport=64982 dstport=80 srcintf="port5" srcintfrole="undefined" dstintf="port3" dstintfrole="wan" policyid=108 proto=6 direction="incoming" filename="FrontPageImgHandler.ashx" quarskip="File-was-not-quarantined." virus="Malware_Generic.P0" dtype="Virus" ref="http://www.fortinet.com/ve?vn=Malware_Generic.P0" virusid=7024603 url="http://www.karsec.gov.in/FrontPageImgHandler.ashx?id=12" profile="Web-Browsing" agent="Chrome/66.0.3359.181" analyticscksum="a9165dbae34e6e2952270536e95a2bb154dff0cfcdf41315f0796ee14b36123b" analyticssubmit="false" crscore=50 crlevel="critical"'

**Phase 2: Completed decoding.
       decoder: 'fortigate-firewall-v6'
       type: '"utm"'
       subtype: '"virus"'
       level: '"alert"'
       vd: '"BA-EXORA"'
       eventtime: '1527737336'
       tz: '1245643'

**Phase 3: Completed filtering (rules).
       Rule id: '100011'
       Level: '3'
       Description: 'Fortigate firewall log'
**Alert to be generated.
```

Note only rules with levels higher than 2 generate alerts.

We have a lot of rules and decoders but sometimes users need to create their own ruleset for their environment. You can read how to create custom rules and decoders in our documentation:
[Custom rules and decoders](https://documentation.wazuh.com/3.11/user-manual/ruleset/custom.html)

Regards,
Eva

**Comment by coopjab** [comment]
@Lopuiz 

this is my log 


date=2020-03-05 time=15:50:47 d                                                                                                             evname="FGT60FTK19000513" devid="FGT60FTK19000513" logid="0000000011" type="traf                                                                                                             fic" subtype="forward" level="warning" vd="root" eventtime=1583403648351975781 t                                                                                                             z="+0530" srcip= srcport= srcintf="internal" srcintfrole="lan"                                                                                                              dstip=8.8.8.8 dstport=53 dstintf="wan2" dstintfrole="wan" sessionid=3544923 prot                                                                                                             o=17 action="dns" policyid=1 policytype="policy" poluuid="fdaa0826-3d23-51ea-3bc                                                                                                             0-ae5019db7ca5" service="DNS" dstcountry="United States" srccountry="Reserved" a                                                                                                             ppcat="unscanned" crscore=5 craction=262144 crlevel="low"................

**Comment by coopjab** [comment]
> date=2018-05-31 time=08:58:56 devname="BA-RSYS-FW" devid="FG600C3912803212" logid="0211008192" type="utm" subtype="virus" level="alert" vd="BA-EXORA" eventtime=1527737336 tz="1245643" msg="File is infected." action="blocked" service="HTTP" sessionid=377413095 srcip=172.24.12.52 dstip=164.100.80.203 srcport=64982 dstport=80 srcintf="port5" srcintfrole="undefined" dstintf="port3" dstintfrole="wan" policyid=108 proto=6 direction="incoming" filename="FrontPageImgHandler.ashx" quarskip="File-was-not-quarantined." virus="Malware_Generic.P0" dtype="Virus" ref="http://www.fortinet.com/ve?vn=Malware_Generic.P0" virusid=7024603 url="http://www.karsec.gov.in/FrontPageImgHandler.ashx?id=12" profile="Web-Browsing" agent="Chrome/66.0.3359.181" analyticscksum="a9165dbae34e6e2952270536e95a2bb154dff0cfcdf41315f0796ee14b36123b" analyticssubmit="false" crscore=50 crlevel="critical"

@Lopuiz 

yeah i tested ur sample log also ...in that "alert generated is not showing find the attachment below

![Screenshot (86)](https://user-images.githubusercontent.com/36020960/75972743-f21bd780-5ef9-11ea-8113-4e56f5c3102d.png)

**Comment by Lopuiz** [comment]
Hi @coopjab 

To generate alert change the rule level to 3.

Regards,
Eva

**Comment by Lopuiz** [comment]
Hello,

The following `ossec.conf` options let Wazuh generate an alert when a rule has a level higher than two:
```xml
  <alerts>
    <log_alert_level>3</log_alert_level>
    <email_alert_level>12</email_alert_level>
  </alerts>
```
If you modify it, you should change rule levels too.

You can read more about these options in our [documentation](https://documentation.wazuh.com/3.11/user-manual/reference/ossec-conf/alerts.html)

Best regards,
Eva

**Comment by coopjab** [comment]
@Lopuiz 

thanks a lot for replying and sorting out my issue  👍 
thanks a lot .. now I'm able to see my firewall traffic 

cheers.

**Comment by Lopuiz** [comment]
Hi!

You are welcome!

I am glad I was useful.
As the issue has already solved, I am going to close it.

Regards,
Eva
