### ISSUE TITLE
Custom SCA

### ISSUE THREAD

**Issue by ljdsr** [wazuh/wazuh-ruleset#594]
Hey guys  i would like ask a little help here...

I'm trying to make a custom YAML based on the sca_win_audit.yml but it wont even load. 

2020/04/03 12:09:46 ossec-agent: WARNING: Failed to load YAML document in C:\Program Files (x86)\ossec-agent\ruleset\sca\sca_win_audit.yml:0
2020/04/03 12:09:46 sca: WARNING: Error found while parsing file: 'C:\Program Files (x86)\ossec-agent\ruleset\sca\sca_win_audit.yml'. Skipping it.

First question, can i customize  it? 
 
If yes, its there anything wrong with this code attached?
[sca_win_2012_audit.yml.txt](https://github.com/wazuh/wazuh-ruleset/files/4428240/sca_win_2012_audit.yml.txt)

Thanks

**Comment by danimegar** [comment]
Hi @ljdsr 
According to the [documentation](https://documentation.wazuh.com/3.12/user-manual/capabilities/sec-config-assessment/creating_custom_policies.html#sca-policy-file-variables-section), it is possible to create a custom YAML file. You can find more information there. 

I realized that the check IDs are identical to the sca_win_audit.yml when fields id from policy and checks must be unique across policy files. Maybe that is the problem. Nevertheless, I will try to reproduce this case.

Regards,
Daniel

**Comment by ljdsr** [comment]
@danimegar i tried changing the check IDs but i dont think that its the problem here.
i tried changing itens in sca_win_audit to see if it would work.
Basically i just altered the rule that a item was checking and title and it indeed worked but when i try to make a new one it wont even load.... only gonna log that: Error found while parsing file

**Comment by ljdsr** [comment]
Thanks for your time, @danimegar 
i tried few stuffs and worked.

Things that i changed was check IDs and description, for some kinda reason if description inst put in it wont work.

**Comment by danimegar** [comment]
Thanks for sharing your answer!
I am glad you found the solution. 
Please do not hesitate to contact us if you have more questions to share.
Regards,
Daniel
