### ISSUE TITLE
False positive on "Trojaned version of file '/bin/grep' detected."

### ISSUE THREAD

**Issue by kdslkdsaldsal** [wazuh/wazuh-ruleset#60]
Currently seeing this against Debian stretch:

```
Rule: 510 fired (level 7) -> "Host-based anomaly detection event (rootcheck)."
Portion of the log(s):

Trojaned version of file '/bin/grep' detected. Signature used: 'bash|givemer|/dev/' (Generic).
title: Trojaned version of file detected.
file: /bin/grep
```

Same was fixed a few weeks ago in the OSSEC ruleset: https://github.com/ossec/ossec-hids/issues/994, https://github.com/ossec/ossec-hids/pull/1225

**Comment by kdslkdsaldsal** [comment]
Fixed in https://github.com/wazuh/wazuh-ruleset/commit/dddcc7839e9237fd514f969136a364976fe76276

**Comment by amitn322** [comment]
I Managed to get wazuh agent installed on an alpine container, however I got a bunch of trojaned version of executables detected for a large number of binaries. Some examples below : 

Trojaned version of file '/bin/grep' detected. Signature used: 'bash|givemer' (Generic)
Trojaned version of file '/usr/bin/top' detected. Signature used: '/dev/[^npi3st%]|proc\.h|/prof/' (Generic).
Trojaned version of file '/bin/kill' detected. Signature used: '/dev/[ab,d-k,m-z]|/dev/[F-Z]|/dev/[A-D]|/dev/[0-9]|proc\.h|bash|tmp' (Generic).

**Comment by shahzebgithub** [comment]
> I Managed to get wazuh agent installed on an alpine container, however I got a bunch of trojaned version of executables detected for a large number of binaries. Some examples below :
> Trojaned version of file '/bin/grep' detected. Signature used: 'bash|givemer' (Generic)
> Trojaned version of file '/usr/bin/top' detected. Signature used: '/dev/[^npi3st%]|proc\.h|/prof/' (Generic).
> Trojaned version of file '/bin/kill' detected. Signature used: '/dev/[ab,d-k,m-z]|/dev/[F-Z]|/dev/[A-D]|/dev/[0-9]|proc\.h|bash|tmp' (Generic).

is it trojan or just false positive? should we consider it in alarms?

**Comment by darkmac78** [comment]
Is this still a false positive on openSUSE 15.6, or I should dig deeper?

Trojaned version of file '/usr/bin/kill' detected. Signature used: '/dev/[ab,d-k,m-z]|/dev/[F-Z]|/dev/[A-D]|/dev/[0-9]|proc\.h|bash|tmp' (Generic).
