### ISSUE TITLE
sshd rule: Bad protocol version identification missing srcip

### ISSUE THREAD

**Issue by kdslkdsaldsal** [wazuh/wazuh-ruleset#61]
Just noticed the following today on a OpenSSH server running on Debian Stretch:

```
Wazuh Notification.
2017 Sep 01 17:42:58

Received From: foo->/var/log/auth.log
Rule: 5701 fired (level 8) -> "sshd: Possible attack on the ssh server (or version gathering)."
Portion of the log(s):

Sep  1 17:42:56 foo sshd[32010]: Bad protocol version identification '\003' from 192.168.178.1 port 857



 --END OF NOTIFICATION
```

Seems this alert is missing the srcip because of an additional ``$`` in the decoder:

```
<decoder name="ssh-scan2">
  <parent>sshd</parent>
  <prematch>^Did not receive identification|^Bad protocol version</prematch>
  <regex offset="after_prematch"> from (\S+)$</regex>
  <order>srcip</order>
</decoder>
```

Might be possible that something similar to https://github.com/wazuh/wazuh-ruleset/commit/d6d36e6dc1e99a167c48f7edbbce44b96af242b5 needs to be done here.

**Comment by jesuslinares** [comment]
Fixed: https://github.com/wazuh/wazuh-ruleset/commit/c5e351aaa9da1fe1ce6574dd43f9769ee3cf4b78

Thanks!
