### ISSUE TITLE
Exim Decoder won't pickup the failed login if no user is passed

### ISSUE THREAD

**Issue by JGRFenix** [wazuh/wazuh-ruleset#626]
In the Exim decoders 
https://github.com/wazuh/wazuh-ruleset/blob/3.12/decoders/0445-exim_decoders.xml#L20
It won't decode out anything if  no user is passed.
An example log would be: 
```2020-04-29 11:59:31 dovecot_login authenticator failed for ([141.98.80.32]) [141.98.80.32]:5222: 535 Incorrect authentication data```

to fix this is my ruleset I've added the below decoder above the one linked above

```
<decoder name="exim-authfailed-nouser">
  <parent>windows-date-format</parent>
  <prematch offset="after_parent">dovecot_login authenticator failed for </prematch>
  <regex offset="after_prematch">\(\.+\) [(\S+)]:\d+: \d+ Incorrect authentication data$</regex>
  <order>srcip</order>
</decoder>

```

Figured I'd share the fix with others in case they are getting the same issue

**Comment by Lopuiz** [comment]
Hello,

Thanks for sharing with us your decoder!
This issue will help to improve this decoder. Also, you are free to open PR with the new decoders. But, remember new decoders must decode the two logs:
`2020-04-29 11:59:31 dovecot_login authenticator failed for ([141.98.80.32]) [141.98.80.32]:5222: 535 Incorrect authentication data`
and
`2017-01-23 03:44:14 dovecot_login authenticator failed for (hydra) [10.101.1.18]:35686: 535 Incorrect authentication data (set_id=user)`

Best regards,
Eva

**Comment by JGRFenix** [comment]
Cool I'll do some further testing to ensure I am not breaking anything and will create the PR,

Thanks!

**Comment by JGRFenix** [comment]
Hiya Eva,

I've created that pull request for you now, 

Thanks,

JR

**Comment by Lopuiz** [comment]
Thanks to you!
