### ISSUE TITLE
Development of SCA policies for Windows Sever 2016

### ISSUE THREAD

**Issue by mikykeane** [wazuh/wazuh-ruleset#639]
Hello team.
Working on the development of SCA policies for Windows Server 2016

**Comment by K-Embee** [comment]
Added Section 9 checks

**Comment by eliasgrana** [comment]
Added section 18.1 - 18.8 checks

**Comment by K-Embee** [comment]
Added section 2.3.8 - 2.3.17 checks

**Comment by mikykeane** [comment]
merged development branches with compliances. Pending review of IDs and it is finished

**Comment by 72nomada** [comment]
Closing issue as it is solved by PR: 

Adding SCA policies for Windows Server 2016 RTM #733
