### ISSUE TITLE
Development of SCA policies for Windows 10 Release 1903

### ISSUE THREAD

**Issue by mikykeane** [wazuh/wazuh-ruleset#647]
Hello team.
Working on the development of SCA policies for Windows Enterprise 10 Release 1903

**Comment by mikykeane** [comment]
Reviewed all changes from previous CIS benchmark for Release 1803

**Comment by mikykeane** [comment]
Added all changes from Release 1903 and merged compliances from different branches.

**Comment by 72nomada** [comment]
Closing this issue as it is solved by PR: 

Adding SCA policies for Windows 10 Enterprise #734
