### ISSUE TITLE
Debian SCAP/OVAL content

### ISSUE THREAD

**Issue by hex2a** [wazuh/wazuh-ruleset#65]
the `scap_content/cve-debian-oval.xml` file is outdated, and seems to be an old version of the `oval-definitions-2016.xml` definitions file.

For some time, the Debian OVAL files are released "per-release" (`oval-definitions-jessie.xml`) instead of "per-year" (`oval-definitions-2016.xml`)

*see https://www.debian.org/security/oval/*

Since these files are updated daily or even multiple times per day, there might a better update process than this git repository. (maybe add options to update_ruleset.py to fetch it over HTTPS?)

**Comment by hex2a** [comment]
IMHO it is not a good idea to add them to the development branch, as they are currently about 127MB combined and would stay in the git history forever, taking up bandwidth/space/..

**Comment by erseco** [comment]
Hi again,

We know that is a lot of space, but many users of wazuh have securitized installations without internet access so we must provide the oval files with the source.

Maybe will be a good idea gzipping the .xml files for reducing the space.

Although we are planning a system to upgrade the oval and ssg files, thank you for your suggestion.

Best regards!
