### ISSUE TITLE
Error updating wazuh rules 3.12

### ISSUE THREAD

**Issue by JoelleNader** [wazuh/wazuh-ruleset#655]
I'm trying to update wazuh rules using the command "/var/ossec/bin/update_ruleset"

i'm getting the following error:

DEBUG: Arguments: {'source': 'download', 'restart': 'ask', 'backups': False, 'force': False, 'debug': True, 'json': False, 'branch-name': False, 'url': False}
### Wazuh ruleset ###
DEBUG: Downloading ruleset from https://github.com/wazuh/wazuh-ruleset/archive/stable.zip.
ERROR: Unknown: 'ConnectionError' object has no attribute 'reason'.
Exiting.

appreciate your help on this

**Comment by Lopuiz** [comment]
Hello!

Could you tell us your Wazuh version and the parameters used to execute the script?

Regards,
Eva

**Comment by JoelleNader** [comment]
Hello
my Wazuh version is 3.12.2 and im not using any parameters with the funciton only this command:
/var/ossec/bin/update_ruleset

and getting the above error

**Comment by Lopuiz** [comment]
Exist an issue en line 268 of `update_ruleset.py` script.

![imagen](https://user-images.githubusercontent.com/17710550/82549066-a2de5e00-9b5c-11ea-9d5b-51606823ca57.png)

Could you remove 'reason' from the code as following? Then, execute the script again.

```python
        # Download
        try:
            f_url = requests.get(url_ruleset)
        except requests.exceptions.RequestException as e:
            exit(2, "\tDownload Error:{0}.\nExit.".format(e))
```

You can find it in `/var/ossec/framework/scripts/update_ruleset.py`

**Comment by JoelleNader** [comment]
Done
now the error I get is the following

DEBUG: Arguments: {'source': 'download', 'restart': 'ask', 'backups': False, 'force': False, 'debug': True, 'json': False, 'branch-name': False, 'url': False}
### Wazuh ruleset ###
DEBUG: Downloading ruleset from https://github.com/wazuh/wazuh-ruleset/archive/stable.zip.
ERROR: Unknown: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')).
Exiting.

could there be a problem on the firewall or something not allowing the machine to fetch updates, but it is connected to the internet so Im not sure what would the issue be

**Comment by Lopuiz** [comment]
Yes, it can be an issue with the firewall. Check the firewall doesn't block https://github.com/wazuh/wazuh-ruleset/archive/stable.zip or zip download.

Please, review the firewall logs. Additionally, you can use the following script to check you can download zips.

```python
import requests

#url = 'https://github.com/wazuh/wazuh-ruleset/archive/stable.zip'
url = 'https://github.com/wazuh/wazuh-documentation/archive/stable.zip'
download_zip = "download.zip"

try:
	f_url = requests.get(url)
	with open(download_zip, 'wb') as fd:
		for chunk in f_url.iter_content(chunk_size=128):
			fd.write(chunk)

except requests.exceptions.RequestException as e:
	print(e)
```

**Comment by Lopuiz** [comment]
Hello,

I hope you have solved your issue. I close it for inactivity. If you have further questions, subscribe our mailing list or join our Slack channel.
[Wazuh Community](https://wazuh.com/community/)


Regards
Eva
