### ISSUE TITLE
Development of SCA policies for Windows Server 2019

### ISSUE THREAD

**Issue by mikykeane** [wazuh/wazuh-ruleset#656]
Hello team.
Working on the development of SCA policies for Windows Server 2019

It has been developed, strictly following the official CIS guidelines, using their latest official benchmark as reference: **CIS Microsoft Windows Server 2019 RTM (Release 1809) Benchmark v1.0.1 - 11-22-2019**

**Comment by mikykeane** [comment]
Finishes section 9 and 18.8

**Comment by 72nomada** [comment]
Closing issue as it is solved by PR:

Adding SCA policies for Windows Server 2019 RTM #732
