### ISSUE TITLE
Spaces in CSV lists of rule groups causes anomaly in Wazuh display of groups

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh-ruleset#659]
The following 5 rule group section header lines in the Wazuh ruleset have the group names separated by a comma and a space instead of the norm which is only by a comma.  

```
# grep "group name=" /var/ossec/ruleset/rules/* | grep ", "
/var/ossec/ruleset/rules/0020-syslog_rules.xml:<group name="syslog, su,">
/var/ossec/ruleset/rules/0565-ms_ipsec_rules.xml:<group name="windows, ipsec,">
/var/ossec/ruleset/rules/0580-win-security_rules.xml:<group name="windows, windows_security,">
/var/ossec/ruleset/rules/0580-win-security_rules.xml:<group name="windows, windows_security, ipsec,">
/var/ossec/ruleset/rules/0590-win-system_rules.xml:<group name="windows, windows_system">
```

This causes group names that appear in the legends of visualizations in Wazuh dashboards, to be anomalously intended because the name is being extracted with the leading space.  Notice that "windows_security" is indented.
![image](https://user-images.githubusercontent.com/13170654/81956977-fd664000-95d9-11ea-8776-89ab3d2cd803.png)

It is possible other more important facilities in Wazuh may also be extracting and not trimming off the leading space in group names like this, which could affect the actual analysis of events.

Please remove the unwanted spaces in the lines I cited above.

Kevin Branch

**Comment by danimegar** [comment]
Thanks @branchnetconsulting 

We will fix it as soon as possible. I am going to create a Pull Request.

Regards,
Daniel
