### ISSUE TITLE
Development of SCA policies for Debian 7

### ISSUE THREAD

**Issue by mikykeane** [wazuh/wazuh-ruleset#668]
Hello team.
Working on the development of SCA policies for Debian 7

Testing of Debian 7 policies  in the following vagrant boxes:

- [x] bento/debian-7

- [x] blburns/debian-7-amd64

- [x] bento/debian-7.11

**Comment by mikykeane** [comment]
Finished section 1. Working on section 2.

**Comment by eliasgrana** [comment]
Finished section 4,5 and 9.

**Comment by K-Embee** [comment]
Finished sections 6-8 and 12-13

**Comment by eliasgrana** [comment]
Finished sections 10 and 11

**Comment by mikykeane** [comment]
Finished development and testing of SCA policy for Debian 7.

**Comment by 72nomada** [comment]
Closing issue as it is solved by PR:

Adding SCA policies for Debian 7 #723
