### ISSUE TITLE
Development of SCA policies for Debian 8

### ISSUE THREAD

**Issue by K-Embee** [wazuh/wazuh-ruleset#671]
Hello team.
Working on the development of SCA policies for Debian 8 based on CIS. 

**Testing of Debian 8 policies in the following vagrant boxes:**

- [x] debian/jessie64

- [x] bento/debian-8

- [x] generic/debian8

**Comment by K-Embee** [comment]
Added sections 1-3

**Comment by mikykeane** [comment]
Finished Development and testing of Debian 8

**Comment by 72nomada** [comment]
Closing issue as it is solved by PR: 

Adding SCA policies for Debian 8 #724
