### ISSUE TITLE
Amazon WAF rules

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-ruleset#686]
Hello team,

The rules file `0350-amazon_rules.xml` is missing the rules for Amazon WAF.

Wazuh AWS WAF documentation: https://documentation.wazuh.com/3.12/amazon/services/supported-services/waf.html

WAF events format: https://docs.aws.amazon.com/waf/latest/developerguide/logging.html

**Comment by MiguelCasaresRobles** [comment]
Solved here: https://github.com/wazuh/wazuh-ruleset/pull/687
