### ISSUE TITLE
Rule ID error description

### ISSUE THREAD

**Issue by borbelyau** [wazuh/wazuh-ruleset#69]
Wazuh-
Audit Fail - rule id = 4723
Windows-
An attempt was made to change an account's password - rule id = 4723

https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventID=4723

**Comment by SitoRBJ** [comment]
Hello Borbelyau,

Sorry for the late response. 

Could you give us the rule id that is triggered by the windows event with id 4723?

Testing a similar example we get that the alert that is triggered is the one corresponding to the rule id 18105, and we would like to know if it is the same case.

Thanks for everything.

**Comment by SitoRBJ** [comment]
Hello Borbelyau,

It's been more than a month since the last response to this issue. We'll proceed to close it, but don't hesitate to open a new issue if you still have questions or problems with Wazuh.

Regards
