### ISSUE TITLE
Unable to trigger rdp brute force attack alert

### ISSUE THREAD

**Issue by mansan951** [wazuh/wazuh-ruleset#700]
In wazuh server i unable to trigger rdp brute force attack alert in email. Any one have reason and solution.

**Comment by Lopuiz** [comment]
Hello!

To can help you, we would like to know how do you capture the events (using eventlog or eventchannel).

Additionally, we would like to know if you see these alerts in kibana (and it is maild issue), or you can see the event in the event viewer, but you don't see the alert in kibana (it's rules issue).

I wait for your answer.

Best regards,
Eva

**Comment by mansan951** [comment]
issue has been resolved and thank for comment
