### ISSUE TITLE
sendmail-reject decoders extracting right square bracket as part of srcip field

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh-ruleset#72]
These two child decoders in /var/ossec/ruleset/decoders/0275-sendmail_decoders.xml do not extract the IP correctly.  
```
<decoder name="sendmail-reject-nodns">
  <parent>sendmail-reject</parent>
  <prematch>relay=[</prematch>
  <regex offset="after_prematch">^(\S+)]</regex>
  <order>srcip</order>
</decoder>

<decoder name="sendmail-reject-dns">
  <parent>sendmail-reject</parent>
  <prematch>relay=\S+ [</prematch>
  <regex offset="after_prematch">^(\S+)]</regex>
  <order>srcip</order>
</decoder>
```
at least from sendmail log lines like this:
```
Sep 29 17:11:02 ramp sendmail[21549]: v8TLB2x7021549: from=<vonfal@ramp.org>, size=909, class=0, nrcpts=1, msgid=<201709292111.v8TLB1Nj021545@ramp.org>, proto=ESMTP, daemon=MTA, relay=localhost.localdomain [127.0.0.1]
Sep 29 17:11:02 ramp sendmail[21549]: v8TLB2x7021549: from=<vonfal@ramp.org>, size=909, class=0, nrcpts=1, msgid=<201709292111.v8TLB1Nj021545@ramp.org>, proto=ESMTP, daemon=MTA, relay=[127.0.0.1]
```
In both cases the srcip field is extracted as "127.0.0.1]".  The right square bracket should not be there.  This creates many error messages in logstash when it tries to do a geoip lookup on the srcip field.
```
[2017-09-29T00:05:03,613][ERROR][logstash.filters.geoip   ] IP Field contained invalid IP address or hostname {:exception=>java.net.UnknownHostException: 127.0.0.1], :field=>"srcip".....
```
I changed the regex in the decoders like this:
```
<decoder name="sendmail-reject-nodns">
  <parent>sendmail-reject</parent>
  <prematch>relay=[</prematch>
  <regex offset="after_prematch">^(\d+.\d+.\d+.\d+)]</regex>
  <order>srcip</order>
</decoder>

<decoder name="sendmail-reject-dns">
  <parent>sendmail-reject</parent>
  <prematch>relay=\S+ [</prematch>
  <regex offset="after_prematch">^(\d+.\d+.\d+.\d+)]</regex>
  <order>srcip</order>
</decoder>
```
which appears to fix the problem for my examples, but I presume this would totally break extraction of an IPv6 relay address from sendmail logs.  I suppose these two child decoders could become four:  sendmail-reject-nodns-ipv4, sendmail-reject-dns-ipv4,sendmail-reject-nodns-ipv6, sendmail-reject-dns-ipv6.  In that case then how do we fix the ipv6 versions of these child decoders so they do not pick up the closing right square bracket as part of the srcip field?  Does anyone have any sendmail log examples they would be willing to share where the "relay=" part of the log includes an IPv6 address?

**Comment by jesuslinares** [comment]
Hi @branchnetconsulting,

Thanks for the feedback. It is fixed: https://github.com/wazuh/wazuh-ruleset/pull/113.

Regards,
Jesus.
