### ISSUE TITLE
OpenVPN logs not getting decoded

### ISSUE THREAD

**Issue by antonisnyc94** [wazuh/wazuh-ruleset#721]
Hello,

The current openvpn decoder doesnt work the way my server generates logs. I've been trying for the whole day to change the regex for the decoder to be able and decode the logs without any luck. Can anyone help please? I am using 0190-openvpn_decoders.xml

Example log:
2020-07-09T12:20:28-0400 [stdout#info] [OVPN 0] OUT: 'Thu Jul  9 16:20:28 2020 204.38.238.148:61719 [michael] Peer Connection Initiated with [AF_INET]204.38.238.148:61719'

Thanks,
Tony

**Comment by danimegar** [comment]
Hello @antonisnyc94 

It seems the openvpn decoder needs the log in syslog format. I tried this custom decoder to catch the log and it works:
```xml
 <decoder name="openvpn">
  <prematch>^\d\d\d\d-\d\d-\d\d\S\d\d:\d\d:\d\d-\d\d\d\d </prematch>
</decoder>
```
I think you can do is to change that decoder as explained in the [docu](https://documentation.wazuh.com/3.13/user-manual/ruleset/custom.html#changing-an-existing-decoder). Only you need to change the decoder `openvpn` for the decoder I wrote above.

Regards,
Daniel

**Comment by antonisnyc94** [comment]
Hey Daniel,

I already tried that. I dont believe it's so simple, because the decoder cannot detect that the log is coming from openvpn due to the program name not being picked.

I strongly believe that i need to solve that to be able and make it work. I currently have the below parameters under the program name but it still doesnt pick it up, do you know what i should do?
<program_name>OVPN|openvpn|ovpn-server</program_name>

 I came to that conclusion by doing a logtest with the below logs.
May 14 17:49:12 auth openvpn: Sun May 14 17:49:12 2017 200.200.200.200:17777 [chapolin] Peer Connection Initiated with [AF_INET]200.200.200.200:53230 (**SUCCESFUL**)

May 14 17:49:12  [stdout#info] [OVPN 0]: Sun May 14 17:49:12 2017 200.200.200.200:17777 [chapolin] Peer Connection Initiated with [AF_INET]200.200.200.200:53230 (**FAILURE**)

Thanks,
Tony

**Comment by danimegar** [comment]
Hi @antonisnyc94 

I checked this log `May 14 17:49:12 [stdout#info] [OVPN 0]: Sun May 14 17:49:12 2017 200.200.200.200:17777 [chapolin] Peer Connection Initiated with [AF_INET]200.200.200.200:53230` with /var/ossec/bin/ossec-logtest:

```
**Phase 1: Completed pre-decoding.
       full event: 'May 14 17:49:12 [stdout#info] [OVPN 0]: Sun May 14 17:49:12 2017 200.200.200.200:17777 [chapolin] Peer Connection Initiated with [AF_INET]200.200.200.200:53230'
       timestamp: 'May 14 17:49:12'
       hostname: 'host'
       program_name: '(null)'
       log: '[stdout#info] [OVPN 0]: Sun May 14 17:49:12 2017 200.200.200.200:17777 [chapolin] Peer Connection Initiated with [AF_INET]200.200.200.200:53230'

```
The program_name is not correctly read/loaded, so it is possible that the solution `<program_name>OVPN|openvpn|ovpn-server</program_name>` is not enough. 


This log `2020-07-09T12:20:28-0400 [stdout#info] [OVPN 0] OUT: 'Thu Jul 9 16:20:28 2020 204.38.238.148:61719 [michael] Peer Connection Initiated with [AF_INET]204.38.238.148:61719'` doesn't work either:

```
**Phase 1: Completed pre-decoding.
       full event: '2020-07-09T12:20:28-0400 [stdout#info] [OVPN 0] OUT: 'Thu Jul 9 16:20:28 2020 204.38.238.148:61719 [michael] Peer Connection Initiated with [AF_INET]204.38.238.148:61719''
       timestamp: '(null)'
       hostname: 'host'
       program_name: '(null)'
       log: '2020-07-09T12:20:28-0400 [stdout#info] [OVPN 0] OUT: 'Thu Jul 9 16:20:28 2020 204.38.238.148:61719 [michael] Peer Connection Initiated with [AF_INET]204.38.238.148:61719''
```
But it works when I use modify the decoder for:
```xml
 <decoder name="openvpn">
  <prematch>^\d\d\d\d-\d\d-\d\d\S\d\d:\d\d:\d\d-\d\d\d\d </prematch>
</decoder>
```
```
**Phase 1: Completed pre-decoding.
       full event: '2020-07-09T12:20:28-0400 [stdout#info] [OVPN 0] OUT: 'Thu Jul 9 16:20:28 2020 204.38.238.148:61719 [michael] Peer Connection Initiated with [AF_INET]204.38.238.148:61719''
       timestamp: '(null)'
       hostname: 'host'
       program_name: '(null)'
       log: '2020-07-09T12:20:28-0400 [stdout#info] [OVPN 0] OUT: 'Thu Jul 9 16:20:28 2020 204.38.238.148:61719 [michael] Peer Connection Initiated with [AF_INET]204.38.238.148:61719''

**Phase 2: Completed decoding.
       decoder: 'openvpn'
       srcip: '204.38.238.148'
       srcport: '61719'
       srcuser: 'michael'

**Phase 3: Completed filtering (rules).
       Rule id: '81801'
       Level: '3'
       Description: 'OpenVPN: User logged in'
**Alert to be generated.
```

So, if the events that you receive are like `2020-07-09T12:20:28-0400 [stdout#info] [OVPN 0] OUT: 'Thu Jul 9 16:20:28 2020 204.38.238.148:61719 [michael] Peer Connection Initiated with [AF_INET]204.38.238.148:61719'` I think you can use this solution. However, if there are events with another format, I can think of another alternative. Only I need the other logs.


Regards,
Daniel

**Comment by danimegar** [comment]
### Another idea

You can active the archives.log so that you can see in the Manager host the events that are sent from the agent. For that open /var/ossec/etc/ossec.conf (Manager) and set <logall> to yes: <logall>yes</logall> in global section. Then, restart the service and you will see the events in /var/ossec/logs/archives/archives.log. In that way, I can check those logs using `/var/ossec/bin/ossec-logtest` and know if the decoder works or does not. 

Regards,
Daniel

**Comment by antonisnyc94** [comment]
Thanks Daniel, I just removed the
 <program_name>OVPN|openvpn|ovpn-server</program_name> 

and added your prematch parameters and now it works fine. I didnt realize i could do that at the openvpn decoder level. Thanks again.

Best regards,
Tony
