### ISSUE TITLE
how can i disable PCI-DSS, GDPR, HIPAA & TSC 

### ISSUE THREAD

**Issue by kzubairi28** [wazuh/wazuh-ruleset#722]
I would like to remove rule.gdpr rule.gpg13 rule.hipaa rule.pci_dss & rule.tsc from the wazuh. is there a possible way to achieve this ?

**Comment by Lopuiz** [comment]
Hello!

You should remove all references of these specifications from rules.

I recomend you create a script that reads all file from `/var/ossec/ruleset/rules` and if the tag `group` of a rule contains `pci_dss_x`,  `gpgX`,  `gdpr_X`, `nist_x`, `tsc_x`, `tsc_x`, `tsc_x` or `tsc_x`, remove it.

Note, if you update ruleset, these specifications will appear again. You have to apply the script again.

Regards,
Eva

**Comment by Lopuiz** [comment]
I close this issue for inactivity. Please, for further questions join our Slack channel or subscribe to our mailing list.
[Wazuh community](https://wazuh.com/community/)

Regards,
Eva
