### ISSUE TITLE
cis Windows Server 2019 Standard

### ISSUE THREAD

**Issue by maxicloud** [wazuh/wazuh-ruleset#742]
Hello,

Do you have cis windows server 2019?

@mikykeane

**Comment by Lopuiz** [comment]
Hello,

The PR number [732](https://github.com/wazuh/wazuh-ruleset/pull/732) contains SCA policies for it. I read you have problems loading this policy to the configuration.

To know how to configure SCA in `agent.conf` follow this [link](https://documentation.wazuh.com/3.13/user-manual/capabilities/sec-config-assessment/how_to_configure.html#how-to-share-policy-files-and-configuration-with-the-wazuh-agents)

I hope it helps you. For further questions, please subscribe to our mailing list or join our slack channel.
[Wazuh community](https://wazuh.com/community/)

Best regards,
Eva

**Comment by Lopuiz** [comment]
I close this issue for inactivity
