### ISSUE TITLE
Issues with decoding non-standard syslog-events; can the syslog-decoder be adjusted or is it built in?

### ISSUE THREAD

**Issue by MagnusMWW** [wazuh/wazuh-ruleset#752]
We have a situation where some agents have a rsyslog-template applied, making the local syslog-produced-files contain:

```
Sep 21 15:02:53 <authpriv.info> host1 sshd[20036]: Accepted publickey for user from 10.10.0.10 port 56092 ssh2
```
instead of the standard:
```
Sep 21 15:02:53 host1 sshd[20036]: Accepted publickey for user from 10.10.0.10 port 56092 ssh2
```

Because of this, the fields "hostname" and "program_name" remains unpopulated in most cases, which in turn makes a lot of the rules in the standard ruleset useless. My first idea was to create a local decoder that takes this into account so that both of these formats would be accepted in our environment. However, it seems that the decoder for syslog is hard-coded or something, because I could not find a decoder that actually extracts these fields. I tried to work around it by making a decoder that catches our weird format, but of course that didn't automatically make them work with the already defined rules. Is there any way to change the syslog-decoder in this way, or is it hard-coded?

**Comment by Lopuiz** [comment]
Hello @MagnusMWW 

As you mention, the preprocessing phase can't obtain the hostname and program name:

```
**Phase 1: Completed pre-decoding.
       full event: 'Sep 21 15:02:53 <authpriv.info> host1 sshd[20036]: Accepted publickey for user from 10.10.0.10 port 56092 ssh2'
       timestamp: 'Sep 21 15:02:53'
       hostname: 'lopezziur'
       program_name: '(null)'
       log: '<authpriv.info> host1 sshd[20036]: Accepted publickey for user from 10.10.0.10 port 56092 ssh2'
```

As do with the second log:

```
**Phase 1: Completed pre-decoding.
       full event: 'Sep 21 15:02:53 host1 sshd[20036]: Accepted publickey for user from 10.10.0.10 port 56092 ssh2'
       timestamp: 'Sep 21 15:02:53'
       hostname: 'host1'
       program_name: 'sshd'
       log: 'Accepted publickey for user from 10.10.0.10 port 56092 ssh2'
```

I recommend you add this decoder below `sshd` decoder in file `var/ossec/ruleset/decoders/0310-ssh_decoders.xml`:

```xml
<decoder name="sshd">
  <prematch>\S+> \S+ sshd[\d+]:</prematch>
</decoder>
```
And add `offset="after_parent` or remove `^` symbol from `<match>` and `<prematch>` tags of rules and decoders which depends on it to fire.  For example, I modify the following rule and decoder to generate alert from the log you sent:

Decoder:

```xml
<decoder name="sshd-success">
  <parent>sshd</parent>
  <prematch offset="after_parent">^Accepted</prematch>
  <regex offset="after_prematch">^ \S+ for (\S+) from (\S+) port </regex>
  <order>user, srcip</order>
  <fts>name, user, location</fts>
</decoder>
```

Rule:

```xml
  <rule id="5715" level="3">
    <if_sid>5700</if_sid>
    <match>Accepted|authenticated.$</match>
    <description>sshd: authentication success.</description>
    <mitre>
      <id>T1078</id>
      <id>T1021</id>
    </mitre>
    <group>authentication_success,pci_dss_10.2.5,gpg13_7.1,gpg13_7.2,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,</group>
  </rule>
```

It should work:

```
2020/09/23 12:11:03 ossec-testrule: INFO: Started (pid: 22942).
ossec-testrule: Type one log per line.

Sep 21 15:02:53 <authpriv.info> host1 sshd[20036]: Accepted publickey for user from 10.10.0.10 port 56092 ssh2


**Phase 1: Completed pre-decoding.
       full event: 'Sep 21 15:02:53 <authpriv.info> host1 sshd[20036]: Accepted publickey for user from 10.10.0.10 port 56092 ssh2'
       timestamp: 'Sep 21 15:02:53'
       hostname: '(null)'
       program_name: '(null)'
       log: '<authpriv.info> host1 sshd[20036]: Accepted publickey for user from 10.10.0.10 port 56092 ssh2'

**Phase 2: Completed decoding.
       decoder: 'sshd'
       dstuser: 'user'
       srcip: '10.10.0.10'

**Phase 3: Completed filtering (rules).
       Rule id: '40101'
       Level: '12'
       Description: 'System user successfully logged to the system.'
**Alert to be generated.
```

Note if you update Wazuh ruleset using the `update_ruleset` script, you will lose these modifications, and you must add it again.

I hope it helps you. If you have further questions, lets us know.

Best regards,
Eva

**Comment by MagnusMWW** [comment]
Thank you @Lopuiz . I was afraid that I was going to have to go down this road, and this confirms it. Maybe it's a bit easier if I can do it for the decoders I actually want and I won't have to create too many local versions. I'll do some more tests and probably will be ending up doing what you suggest.
