### ISSUE TITLE
Escape < (&gt;) and > (&lt;) - XML Decoders

### ISSUE THREAD

**Issue by kyparisisg** [wazuh/wazuh-ruleset#757]
Hello,

I have been trying to escape the following characters on my custom decoder for a regex but Wazuh sees the (<, >) as an XML error instead.
Here is an example for the regex use when I include a "<" sign inside my **<regex> something <(\S+)> something else </regex>**
The error returned is: 
**ERROR: (1226): Error reading XML file 'ruleset/decoders/local_decoders.xml': XMLERR: Element '(\S+)' not closed. (line 26).
CRITICAL: (1202): Configuration error at 'ruleset/decoders/local_decoders.xml'.**

Is there a way to escape the greater than and less than sign inside the <regex></regex> of a decoder?

Thank you very much for your help in advance!

**Comment by Lopuiz** [comment]
Hello,

You can escape the character using `\`. In our [documentation](https://documentation.wazuh.com/3.13/user-manual/ruleset/ruleset-xml-syntax/regex.html#regex-os-regex-syntax) you will find more about Wazuh regex syntax.

Example:
```xml
<!--  Dec 19 17:20:08 ubuntu test[12345]: <Test> escaping character -->
<decoder name="test_decoder">
  <program_name>test</program_name>
  <regex>\<(\S+)> escaping character</regex>
  <order>test</order>
</decoder>
```

Regards,
Eva

**Comment by Lopuiz** [comment]
I close this issue for inactivity

**Comment by kyparisisg** [comment]
Awesome, you have to escape only the first \<
That's my bad, must have misread the documentation. 
Thank you very much!
