### ISSUE TITLE
Rule: 18107 (level 3) -> 'Windows Logon Success

### ISSUE THREAD

**Issue by keith-mo** [wazuh/wazuh-ruleset#77]
Hi,

Currently migrating from wazuh 1.1 to 2.1

We have a number of rules custom rules that work off rule 18107 in 0220-msauth_rules.xml.

`<rule id="18107" level="3">
    <if_sid>18104</if_sid>
    <id>^528$|^540$|^673$|^4624$|^4769$</id>
    <description>Windows Logon Success.</description>
    <group>authentication_success,pci_dss_10.2.5,</group>
  </rule>`

We no longer get alerts when we specify individual users in the **user** syntax

`<rule id="100005" level="3">
    <if_sid>18107</if_sid>
    <id>^4624$</id>
    <match>Logon Type:   10</match>
    <hostname>server1|server2</hostname>
    <user>^user1|^user2</user>
    <description>logon alert for serversx</description>
  </rule>`

example of log from alert log

** Alert 1507730218.1797861: - windows,authentication_success,pci_dss_10.2.5,
2017 Oct 11 14:56:58 (server1) xx.xx.xx.xx->WinEvtLog
Rule: 18107 (level 3) -> 'Windows Logon Success.'
Src IP: xx.xx.xx.xx
**User: (no user)**
2017 Oct 11 14:56:57 WinEvtLog: Security: AUDIT_SUCCESS(4624): Microsoft-Windows-Security-Auditing: **(no user)**: no domain: server1.testdomain.com: An account was successfully logged on.    Subject:   Security ID:  S-1-5-18   Account Name:  server1$   Account Domain:  testdomain   Logon ID:  0x    Logon Type:   10    Impersonation Level:  Impersonation    New Logon:   Security ID:  S-1-5-21-   Account Name:  user1   Account Domain:  server1   Logon ID:  0x   Logon GUID:  {00000000-0000-0000-0000-000000000000}    Process Information:   Process ID:  0x   Process Name:  C:\Windows\System32\winlogon.exe    Network Information:   Workstation Name: server1   Source Network Address: xx.xx.xx.xx   Source Port:  0    Detailed Authentication Information:   Logon Process:  User32    Authentication Package: Negotiate   Transited Services: -   Package Name (NTLM only): -   Key Length:  0    This event is generated when a logon session is created. It is generated on the computer that was accessed.    The subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Ser
type: Security
subject.security_id: S-1-5-18
subject.account_name: server1$
subject.account_domain: testdomain
subject.logon_id: 0x
security_id: 
account_name: user1
account_domain: server1
logon_type: 10

I've noticed in wazuh 2.1 that no matter what user you logon with the log reports the user as **User: (no user)** this doesnt happen in 1.1 its populate with the actual logged on user.

i think this might be the causing the alert not to generate...

**Comment by jlruizmlg** [comment]
Hello

Wazuh 2.0 introduce a new feature with Dynamic Fields, this option give us
more flexibility to extract information (we are not longer limit to 12
fields like in previous version.)

** Alert 1507730218.1797861: - windows,authentication_success,pci_dss_10.2.5,
2017 Oct 11 14:56:58 (server1) xx.xx.xx.xx->WinEvtLog
Rule: 18107 (level 3) -> 'Windows Logon Success.'
Src IP: xx.xx.xx.xx
User: (no user)
2017 Oct 11 14:56:57 WinEvtLog: Security: AUDIT_SUCCESS(4624):
Microsoft-Windows-Security-Auditing: (no user): no domain:
server1.testdomain.com: An account was successfully logged on.
Subject: Security ID: S-1-5-18 Account Name: server1$ Account Domain:
testdomain Logon ID: 0x Logon Type: 10 Impersonation Level:
Impersonation New Logon: Security ID: S-1-5-21- Account Name: user1
Account Domain: server1 Logon ID: 0x Logon GUID:
{00000000-0000-0000-0000-000000000000} Process Information: Process
ID: 0x Process Name: C:\Windows\System32\winlogon.exe Network
Information: Workstation Name: server1 Source Network Address:
xx.xx.xx.xx Source Port: 0 Detailed Authentication Information: Logon
Process: User32 Authentication Package: Negotiate Transited Services:
- Package Name (NTLM only): - Key Length: 0 This event is generated
when a logon session is created. It is generated on the computer that
was accessed. The subject fields indicate the account on the local
system which requested the logon. This is most commonly a service such
as the Server service, or a local process such as Winlogon.exe or Ser
type: Security
subject.security_id: S-1-5-18
subject.account_name: server1$
subject.account_domain: testdomain
subject.logon_id: 0x
security_id:
account_name: user1
account_domain: server1
logon_type: 10

If you see in your previous logtest now the account name is called
“account_name”, so try to modify your rule with something like:

<rule id="100005" level="3">
   <if_sid>18107</if_sid>
   <id>^4624$</id>
   <hostname>server1|server2</hostname>
   <match>Logon Type: 10</match>
   <field name="account_name">^user1|^user2</field>
   <description>logon alert for serversx</description>
</rule>

**Phase 1: Completed pre-decoding.
       full event: '2017 Oct 11 14:56:57 WinEvtLog: Security:
AUDIT_SUCCESS(4624): Microsoft-Windows-Security-Auditing: (no user):
no domain: server1.testdomain.com: An account was successfully logged
on. Subject: Security ID: S-1-5-18 Account Name: server1$ Account
Domain: testdomain Logon ID: 0x Logon Type: 10 Impersonation Level:
Impersonation New Logon: Security ID: S-1-5-21- Account Name: user1
Account Domain: server1 Logon ID: 0x Logon GUID:
{00000000-0000-0000-0000-000000000000} Process Information: Process
ID: 0x Process Name: C:\Windows\System32\winlogon.exe Network
Information: Workstation Name: server1 Source Network Address:
xx.xx.xx.xx Source Port: 0 Detailed Authentication Information: Logon
Process: User32 Authentication Package: Negotiate Transited Services:
- Package Name (NTLM only): - Key Length: 0 This event is generated
when a logon session is created. It is generated on the computer that
was accessed. The subject fields indicate the account on the local
system which requested the logon. This is most commonly a service such
as the Server service, or a local process such as Winlogon.exe or Ser'
       hostname: 'centos7'
       program_name: 'WinEvtLog'
       log: 'Security: AUDIT_SUCCESS(4624):
Microsoft-Windows-Security-Auditing: (no user): no domain:
server1.testdomain.com: An account was successfully logged on.
Subject: Security ID: S-1-5-18 Account Name: server1$ Account Domain:
testdomain Logon ID: 0x Logon Type: 10 Impersonation Level:
Impersonation New Logon: Security ID: S-1-5-21- Account Name: user1
Account Domain: server1 Logon ID: 0x Logon GUID:
{00000000-0000-0000-0000-000000000000} Process Information: Process
ID: 0x Process Name: C:\Windows\System32\winlogon.exe Network
Information: Workstation Name: server1 Source Network Address:
xx.xx.xx.xx Source Port: 0 Detailed Authentication Information: Logon
Process: User32 Authentication Package: Negotiate Transited Services:
- Package Name (NTLM only): - Key Length: 0 This event is generated
when a logon session is created. It is generated on the computer that
was accessed. The subject fields indicate the account on the local
system which requested the logon. This is most commonly a service such
as the Server service, or a local process such as Winlogon.exe or Ser'

**Phase 2: Completed decoding.
       decoder: 'windows'
       type: 'Security'
       status: 'AUDIT_SUCCESS'
       id: '4624'
       extra_data: 'Microsoft-Windows-Security-Auditing'
       dstuser: '(no user)'
       system_name: 'server1.testdomain.com'
       subject.security_id: 'S-1-5-18'
       subject.account_name: 'server1$'
       subject.account_domain: 'testdomain'
       subject.logon_id: '0x'
       security_id: 'S-1-5-21-'
       account_name: 'user1'
       account_domain: 'server1'
       logon_type: '10'
       srcip: 'xx.xx.xx.xx'

**Phase 3: Completed filtering (rules).
       Rule id: '100005'
       Level: '3'
       Description: 'logon alert for serversx'
**Alert to be generated.


You can find more information about the dynamic fields in the following
link:

https://documentation.wazuh.com/current/user-manual/ruleset/dynamic-fields.html

i hope it helps.



Regards
————————
José Luis Ruiz.
Wazuh Inc.
jose@wazuh.com


On October 11, 2017 at 10:13:00 AM, keith-mo (notifications@github.com)
wrote:

2017 Oct 11 14:56:57 <http://airmail.calendar/2017-10-11 14:56:57 EDT>
WinEvtLog:
Security: AUDIT_SUCCESS(4624): Microsoft-Windows-Security-Auditing: (no
user): no domain: server1.testdomain.com: An account was successfully
logged on. Subject: Security ID: S-1-5-18 Account Name: server1$ Account
Domain: testdomain Logon ID: 0x Logon Type: 10 Impersonation Level:
Impersonation New Logon: Security ID: S-1-5-21- Account Name: user1 Account
Domain: server1 Logon ID: 0x Logon GUID:
{00000000-0000-0000-0000-000000000000} Process Information: Process ID: 0x
Process Name: C:\Windows\System32\winlogon.exe Network Information:
Workstation Name: server1 Source Network Address: xx.xx.xx.xx Source Port:
0 Detailed Authentication Information: Logon Process: User32 Authentication
Package: Negotiate Transited Services: - Package Name (NTLM only): - Key
Length: 0 This event is generated when a logon session is created. It is
generated on the computer that was accessed. The subject fields indicate
the account on the local system which requested the logon. This is most
commonly a service such as the Server service, or a local process such as
Winlogon.exe or Ser

**Comment by jlruizmlg** [comment]
Hello

Wazuh 2.0 introduce a new feature with Dynamic Fields, this option give us more flexibility to extract information (we are not longer limit to 12 fields like in previous version.)

```
** Alert 1507730218.1797861: - windows,authentication_success,pci_dss_10.2.5,
2017 Oct 11 14:56:58 (server1) xx.xx.xx.xx->WinEvtLog
Rule: 18107 (level 3) -> 'Windows Logon Success.'
Src IP: xx.xx.xx.xx
User: (no user)
2017 Oct 11 14:56:57 WinEvtLog: Security: AUDIT_SUCCESS(4624): Microsoft-Windows-Security-Auditing: (no user): no domain: server1.testdomain.com: An account was successfully logged on. Subject: Security ID: S-1-5-18 Account Name: server1$ Account Domain: testdomain Logon ID: 0x Logon Type: 10 Impersonation Level: Impersonation New Logon: Security ID: S-1-5-21- Account Name: user1 Account Domain: server1 Logon ID: 0x Logon GUID: {00000000-0000-0000-0000-000000000000} Process Information: Process ID: 0x Process Name: C:\Windows\System32\winlogon.exe Network Information: Workstation Name: server1 Source Network Address: xx.xx.xx.xx Source Port: 0 Detailed Authentication Information: Logon Process: User32 Authentication Package: Negotiate Transited Services: - Package Name (NTLM only): - Key Length: 0 This event is generated when a logon session is created. It is generated on the computer that was accessed. The subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Ser
type: Security
subject.security_id: S-1-5-18
subject.account_name: server1$
subject.account_domain: testdomain
subject.logon_id: 0x
security_id:
account_name: user1
account_domain: server1
logon_type: 10
```

If you see in your previous logtest now the account name is called “account_name”, so try to modify your rule with something like:

```
<rule id="100005" level="3">
   <if_sid>18107</if_sid>
   <id>^4624$</id>
   <hostname>server1|server2</hostname>
   <match>Logon Type: 10</match>
   <field name="account_name">^user1|^user2</field>
   <description>logon alert for serversx</description>
</rule>
```
```
**Phase 1: Completed pre-decoding.
       full event: '2017 Oct 11 14:56:57 WinEvtLog: Security: AUDIT_SUCCESS(4624): Microsoft-Windows-Security-Auditing: (no user): no domain: server1.testdomain.com: An account was successfully logged on. Subject: Security ID: S-1-5-18 Account Name: server1$ Account Domain: testdomain Logon ID: 0x Logon Type: 10 Impersonation Level: Impersonation New Logon: Security ID: S-1-5-21- Account Name: user1 Account Domain: server1 Logon ID: 0x Logon GUID: {00000000-0000-0000-0000-000000000000} Process Information: Process ID: 0x Process Name: C:\Windows\System32\winlogon.exe Network Information: Workstation Name: server1 Source Network Address: xx.xx.xx.xx Source Port: 0 Detailed Authentication Information: Logon Process: User32 Authentication Package: Negotiate Transited Services: - Package Name (NTLM only): - Key Length: 0 This event is generated when a logon session is created. It is generated on the computer that was accessed. The subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Ser'
       hostname: 'centos7'
       program_name: 'WinEvtLog'
       log: 'Security: AUDIT_SUCCESS(4624): Microsoft-Windows-Security-Auditing: (no user): no domain: server1.testdomain.com: An account was successfully logged on. Subject: Security ID: S-1-5-18 Account Name: server1$ Account Domain: testdomain Logon ID: 0x Logon Type: 10 Impersonation Level: Impersonation New Logon: Security ID: S-1-5-21- Account Name: user1 Account Domain: server1 Logon ID: 0x Logon GUID: {00000000-0000-0000-0000-000000000000} Process Information: Process ID: 0x Process Name: C:\Windows\System32\winlogon.exe Network Information: Workstation Name: server1 Source Network Address: xx.xx.xx.xx Source Port: 0 Detailed Authentication Information: Logon Process: User32 Authentication Package: Negotiate Transited Services: - Package Name (NTLM only): - Key Length: 0 This event is generated when a logon session is created. It is generated on the computer that was accessed. The subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Ser'

**Phase 2: Completed decoding.
       decoder: 'windows'
       type: 'Security'
       status: 'AUDIT_SUCCESS'
       id: '4624'
       extra_data: 'Microsoft-Windows-Security-Auditing'
       dstuser: '(no user)'
       system_name: 'server1.testdomain.com'
       subject.security_id: 'S-1-5-18'
       subject.account_name: 'server1$'
       subject.account_domain: 'testdomain'
       subject.logon_id: '0x'
       security_id: 'S-1-5-21-'
       account_name: 'user1'
       account_domain: 'server1'
       logon_type: '10'
       srcip: 'xx.xx.xx.xx'

**Phase 3: Completed filtering (rules).
       Rule id: '100005'
       Level: '3'
       Description: 'logon alert for serversx'
**Alert to be generated.
```

You can find more information about the dynamic fields in the following link:

https://documentation.wazuh.com/current/user-manual/ruleset/dynamic-fields.html

i hope it helps.

**Comment by keith-mo** [comment]
Thanks - that's done the trick.
