### ISSUE TITLE
False positives with CIS benchmarks

### ISSUE THREAD

**Issue by whizoun** [wazuh/wazuh-ruleset#78]
Hi,

We are receiving some false positives when performing CIS benchmarsk against SLES11 servers. For instance, 9.2.8 Disable SSH Root Login is reporting insecure configuration, when it is set like this on the configuration file:

#PermitRootLogin yes
PermitRootLogin no

I've had a look at the content of the rule and I wonder if it could be because the regex doesn't seem to match:

_f:/etc/ssh/sshd_config -> r:^#\s*PermitRootLogin;_

Shouldn't it be with a $ sign after "PermitRootLogin"?, like this:

_f:/etc/ssh/sshd_config -> r:^#\s*PermitRootLogin$;_

thank you
regards

**Comment by jesuslinares** [comment]
Hi @whizoun,

We updated the SLES11 rootchecks in order to fix the false positives: https://github.com/wazuh/wazuh-ruleset/pull/114.

Thanks for the feedback.
