### ISSUE TITLE
question about Dynamic fields

### ISSUE THREAD

**Issue by jingnanj** [wazuh/wazuh-ruleset#780]
I'm trying to create a rule about audit rule. My problem is how to make a rule for dynamic fields.

For example:
audit.type: CONFIG_CHANGE
audit.id: 20
audit.auid: 0
audit.session: 6
audit.op: add rule
audit.key: audit
audit.list: 4
audit.res: 1
audit.scrip: 127.0.0.1

I'm trying to make a rule that sends alerts when audit. scrip not equal to 127.0.0.1.
But <scrip>!127.0.0.1 </scrip> is not work for audit.scrip and there is no <aduit.scrip> element for audit.scrip

**Comment by jingnanj** [comment]
Here is an additional question, is that possible to make a rule that can check 2 logs.
For example
chmod -r 777 1.txt
vim 1.txt

which is same as 
chmod some bash script
then run it with sh

**Comment by Lopuiz** [comment]
Hello jingnanj,

For dynamic fields, you should use the tag `<field>`, it can't accept negation. We have just implemented this feature, and it is in the master branch. You can know more about developments in the following issues:
* Allow negation in rules [#141](https://github.com/wazuh/wazuh/issues/141)
* Feature proposal: support for libpcre (Perl-compatible) regular expressions [#205](https://github.com/wazuh/wazuh/issues/205)

It'll be on the next release, but I don't know the date of release.

Regarding your second question, you can use `|` to add two regexes on a match/regex tag. If you share further information (output which Analysisd process, the way you collect these logs, etc.) I'll try to help you to create rules for it.

To know more about rule syntax I attach some reference to our documentation:
* [Rule Syntax](https://documentation.wazuh.com/4.0/user-manual/ruleset/ruleset-xml-syntax/rules.html)
* [Regular Expression Syntax](https://documentation.wazuh.com/4.0/user-manual/ruleset/ruleset-xml-syntax/regex.html)

I hope it helps you.

Regards,
Eva

**Comment by jingnanj** [comment]
> Hello jingnanj,
> 
> For dynamic fields, you should use the tag `<field>`, it can't accept negation. We have just implemented this feature, and it is in the master branch. You can know more about developments in the following issues:
> 
> * Allow negation in rules [#141](https://github.com/wazuh/wazuh/issues/141)
> * Feature proposal: support for libpcre (Perl-compatible) regular expressions [#205](https://github.com/wazuh/wazuh/issues/205)
> 
> It'll be on the next release, but I don't know the date of release.
> 
> Regarding your second question, you can use `|` to add two regexes on a match/regex tag. If you share further information (output which Analysisd process, the way you collect these logs, etc.) I'll try to help you to create rules for it.
> 
> To know more about rule syntax I attach some reference to our documentation:
> 
> * [Rule Syntax](https://documentation.wazuh.com/4.0/user-manual/ruleset/ruleset-xml-syntax/rules.html)
> * [Regular Expression Syntax](https://documentation.wazuh.com/4.0/user-manual/ruleset/ruleset-xml-syntax/regex.html)
> 
> I hope it helps you.
> 
> Regards,
> Eva

Hi Eva,
Thanks for your help that will be helpful. 
My second question is need to use one rule to check two logs. 
For now when I use 
chmod 777 test.sh give test.sh permission
then use sh test.sh to run permission
auditd will create two log contents for those two actions. 
I want to create a rule that can detect someone run bash file after give it permission, not just detect change file permission or run a bash file. that already works with current rules.

**Comment by Lopuiz** [comment]
Yes, you could create custom rules and decoder for auditd using the accumulator option.
This [link](https://edgeofsanity.net/article/2012/11/26/ossec-hids-accumulator.html) explains very well how to configure it.

Note you should modify the existing rules and decoders.
You can found it in `ruleset/rules/0365-auditd_rules.xml` and `ruleset/decoders/0040-auditd_decoders.xml`.

**Comment by jingnanj** [comment]
Thanks!
