### ISSUE TITLE
Exploratory testing after changing ossec with wazuh

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh-ruleset#793]
### Description

As part of the epic #784, the word `ossec` should be replaced with `wazuh` in all the wazuh-ruleset repository. This represents many changes not only in the rules and decoders but also in the ruleset tests and update scripts.

Considering this, exploratory testing should be performed over the ruleset in order to identify any possible issue introduced as part of this epic.

**Comment by palaciosjeremias** [comment]
**Issue found**:
The ruleset update, using the **update_ruleset** script and during a manager upgrade, doesn't eliminate the renamed decoders and rules.
Both scenarios must handle this deletion using the **deprecated** list that they has.

**Comment by pereyra-m** [comment]
### Exploratory testing

#### Description

The following testing scenario was created:

- Wazuh Manager Only (branch _dev-wstack-rules_ )
- Rules updated from ruleset repository: branch _dev-wstack-rules_
- Agents:
  - CentOS 7 v3.13.2
  - Ubuntu 20.04 v4.0.3
  - Ubuntu 20.04 v4.1.0 (_dev-wstack-rules_)

#### Tests results

All tests were run with the three agents. In all cases, the expected alerts were generated, and any error/warning message was found:

- Agent connected/started: rules 501/503
- Agent disconnected: rule 504
- Agent removed: rule 505
- Server started: 502
- Log rotated: rule 591

These tests cover the legacy version of the log messages and those with the new Wazuh standard.

**Comment by DProvinciani** [comment]
## Exploratory testing

### Description
The following testing environment was created: Wazuh Cluster

- Master node Centos 8 (branch dev-wstack-rules)
    - Agent Debian 10 (branch dev-wstack-rules)
    - Agent Debian 9 - 4.0.3
- Worker node Centos 7 (branch dev-wstack-rules)
    - Agent Ubuntu 20.04 (branch dev-wstack-rules)
    - Agent Ubuntu 18.04 - 4.0.3

Rules updated from ruleset repository: branch dev-wstack-rules

### Test results
All tests were run with the four agents. In all cases, the expected alerts were generated, and any error/warning message was found:

Agent connected/started: rules 501/503
Agent disconnected: rule 504
Agent removed: rule 505
Server started: 502
Log rotated: rule 591

These tests cover the legacy version of the log messages and those with the new Wazuh standard.
