### ISSUE TITLE
Add renamed rules and decoders to deprecated lists of update_ruleset 

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh-ruleset#806]
### Description
As part of the epic #784, the word ossec should be replaced with wazuh in all the wazuh-ruleset repository. This leads to the renaming of some rules and decoders.
During exploratory testing #793 it was found that these rules and decoders were not deleted when **update_ruleset** script was executed.

**update_ruleset** has two lists for rules and decoders that are deprecated and must be deleted during an update of the ruleset.
**0200-ossec_decoders.xml**, **0015-ossec_rules.xml**, **0016-wazuh_rules.xml** must be added to these lists to guarantee the correct updates of the ruleset.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh-ruleset/pull/807 was merged.
