### ISSUE TITLE
Adding more unit tests to the rules and decoders updated during the Wazuh normalization process

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh-ruleset#808]
#### Description

As part of the epic #784, the rules and decoders were adapted and the OSSEC references were removed.
These changes introduced need to be tested completely, to be sure that all the rules work as expected with the previous and current log messages.

The **wazuh.ini** file will be updated with the new tests.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh-ruleset/pull/809 was merged.
