### ISSUE TITLE
Weekly automatic Report for specific rules id

### ISSUE THREAD

**Issue by lucio2047** [wazuh/wazuh-ruleset#819]
Hi everyone. 

I have a doubt. I need to generate a weekly report when rules id 60109,60111,60110,60141,60142,60144,60145 appear in my environment (users management). I read one possibility is to configure the following section inside ossec.conf:

<reports>
  <rule>60109,60111,60110,60141,60142,60144,60145</rule>
  <title>ABM de usuarios</title>
  <email_to>xxxx@xxxx.com</email_to>
  <showlogs>yes</showlogs>
</reports>

But I would like to know if it's possible to generate this report  by Kibana from GUI. If I configure by ossec.conf there is no possibility to indicate a period of time.

Thank you in advance.

**Comment by jnasselle** [comment]
HI @lucio2047 !

Unfortunately automatic email reports generated by Wazuh are only on daily basis. Currently there's an issue wazuh/wazuh-kibana-app#1492 to enhance this mechanism and make it posible.

You can follow the progress of the issue there.

Regards,
Nico
