### ISSUE TITLE
cis_rhel8_linux_rcl

### ISSUE THREAD

**Issue by meisamhm** [wazuh/wazuh-ruleset#820]
Hi,
Thanks for your contribution and useful project,
Actually, I faced a new project and I have to make a compliance report as well as RHEL8 CIS benchmark,
Would you tell me, are you going to develop RHEL8 CIS ruleset?

BR

**Comment by Lopuiz** [comment]
Hello,

Can these be the policies you are looking for?
[cis_rhel8_linux.yml](https://github.com/wazuh/wazuh/blob/master/ruleset/sca/rhel/8/cis_rhel8_linux.yml)
They are added to the Master Branch so they should releaset soon.

Regards,
Eva

**Comment by meisamhm** [comment]
Thanks a lot Lopuiz, I do appreciate it
