### ISSUE TITLE
sca/debian/cis_debian10.yml has a typo in rule 2551

### ISSUE THREAD

**Issue by edwardgjohns3** [wazuh/wazuh-ruleset#825]
Line 891 should read:
```
      - 'c:systemctl is-enabled systemd-timesyncd -> enabled'
```

Instead, it reads:
```
      - 'c:systemctl is-enabled systemd-timescynd -> enabled'
```

**Comment by 72nomada** [comment]
hi @edwardgjohns3, we are moving all ruleset, including SCA, related issues to repository wazuh/wazuh.

If you don't mind, can you please close this one and open it on wazuh/wazuh repo? 

thanks a lot

**Comment by edwardgjohns3** [comment]
Sure.  No problem.  Thanks.
