### ISSUE TITLE
MJ12bot listed as known malicious user agent?

### ISSUE THREAD

**Issue by kdslkdsaldsal** [wazuh/wazuh-ruleset#84]
The following commit to ossec-hids (which seems to be only about nginx as well) https://github.com/ossec/ossec-hids/commit/559af98a4001a922e9ac31988399d3961ac8bfd6#diff-d07df015283394cd19b1d54f94e11af0 has added the MJ12bot to the list of "known malicious user agents".

IMHO this is wrong and the rule there is not the place for such bots. Reason:

MJ12bot is a spider / crawler which is even obeying the robots.txt with the "Disallow" and the "Crawl-Delay" settings in there.

If some one wants to get rid of this MJ12bot the right place for this would be the robots.txt.

Cross-ref: https://github.com/ossec/ossec-hids/issues/1317

**Comment by kdslkdsaldsal** [comment]
Could it be possible that this rule tried to block the fake Agent described here:

https://nurikabe.blog/2008/01/16/mj12bot-virus-robot/

**Comment by chemamartinez** [comment]
Hi @kdslkdsaldsal ,

You are right and we have removed this user from the list of malicious agent users.
Commit: https://github.com/wazuh/wazuh-ruleset/commit/72839f141f74635b29b35d9832c86d9aaaf30d84

Thanks for the contribution.

**Comment by kdslkdsaldsal** [comment]
Thanks so i think we can close this one. 👍
