### ISSUE TITLE
Rule 80006 Puppet Master: not run - address in use - Level 15?

### ISSUE THREAD

**Issue by jjrbg** [wazuh/wazuh-ruleset#86]
Level 15 for puppet having address in use error is perhaps a bit excessive? Would it not be better suited to a 12 or 13?

```
<rule id="80006" level="15">
        <if_sid>80000</if_sid>
        <match>^Could not run: Address already in use</match>
        <description>Puppet Master: not run - address in use</description>
</rule>
```

"No chances of false positives" for Level 15 - but it seems it can easily happen if someone tries running puppet master if it's already running... https://ask.puppet.com/question/13876/error-could-not-run-address-already-in-use-bind2/

(I'm aware I can locally overwrite the level in local_rules.xml)

jjrbg

**Comment by PSanchezR** [comment]
Hello Jjrbg,

You're right, level 15 is too much for this alert, we've changed it to level 7 in https://github.com/wazuh/wazuh-ruleset/commit/6dee066f2dbf9a6c36b1cd1841cae29e9df6a943 .

Thanks for your feedback.

Best regards.

Pablo Sánchez.
