### ISSUE TITLE
update_ruleset.py doesn't install scap_content

### ISSUE THREAD

**Issue by grant-traynor** [wazuh/wazuh-ruleset#89]
This is probably intentional, but the update_ruleset.py script doens't install scap_content, so OpenSCAP has no rules to parse. Warning, I'm a NOOB at this stuff.

**Comment by PSanchezR** [comment]
Hi grant-traynor,

Sorry for the late response. The OpenScap content is downloaded during the installation process and stored in `/var/ossec/wodles/oscap/content` .

If you have performed an installation from packages you can find several files related to your distribution and derivated:

![packages](https://user-images.githubusercontent.com/5520813/34668154-5670e568-f46c-11e7-8e42-208bbb0f3773.png)

In case you have installed from sources you only find one file for your exact distro:

![sources](https://user-images.githubusercontent.com/5520813/34668164-654ff4ca-f46c-11e7-8fa4-c3a28ebc2677.png).

Currently "update_ruleset" does not update OpenScap content, it only updates rootcheck content, rules and decoders that can be found in the [wazuh-ruleset ](https://github.com/wazuh/wazuh-ruleset)repository.

If you have any other related question, I will be happy to answer it.

Pablo Sánchez.
