### ISSUE TITLE
update_ruleset script name doesn't match with Wazuh 3.1.0

### ISSUE THREAD

**Issue by mpucholblasco** [wazuh/wazuh-ruleset#93]
Wazuh 3.1.0 script to update ruleset is: `/var/ossec/bin/update_ruleset`, however script present on branch 3.1 is `update_ruleset.py`. This effect makes that, once first `update_ruleset` is executed, another `update_ruleset.py` appears on `/var/ossec/bin/`.

Expected behaviour:
* Keep original name `update_ruleset` (by removing suffix `.py`)

**Comment by aknauss** [comment]
hi,
on ubuntu 12.04, I don't have this script : update_ruleset...

How can I do to update?

Franck

**Comment by alberpilot** [comment]
Hello @aknauss 

  Sorry for the late response. You can download the script from here:

`https://raw.githubusercontent.com/wazuh/wazuh-ruleset/3.2/update_ruleset`

and place it into /var/ossec/bin/ with root as owner, root as group and 750 permissions. Edit it and replace the line 301 which is

`copy("{0}/update_ruleset".format(update_ruleset), ossec_update_script, 0o750)`

with this one

`copy("{0}/update_ruleset".format(update_ruleset.py), ossec_update_script, 0o750)`

and now you can try to update as follow:

`/var/ossec/bin/update_ruleset -n 3.1`

All this in case you are still having 3.1 version. We have an incompatibility with this script, solved in 3.2 versions. 

Hope it helps. 
Best regards, 
Alberto R.
