### ISSUE TITLE
updating ruleset wazuh 2.1.0

### ISSUE THREAD

**Issue by pierluigiconti** [wazuh/wazuh-ruleset#97]
Hi there,
I've a wazuh installation, version 2.1.0.
I'm doing regular updates of ruleset as documented:
@weekly cd /var/ossec/bin && ./update_ruleset.py -r

It has update ruleset to 3.1.0 but this ruleset has generated the following iusse:
2018/01/23 17:39:15 ossec-testrule: CRITICAL: (1202): Configuration error at 'ruleset/decoders/0006-json_decoders.xml'. Exiting.

I solved this just re-downloading the old 2.1.0 ruleset.

To prevent same issue in the future should I disable the update_ruleset?

Thank you

**Comment by mgmacias95** [comment]
Hello,

Last week, the stable version of the ruleset was set to 3.0. Updating the ruleset in older installations will fail (as commented in #88 ).

You can disable the update or update your installation to Wazuh v3.1.

Best regards,
Marta

**Comment by pierluigiconti** [comment]
Hi,

ok but for the future, if I'm not minded into follow (and do) every wazuh's version upgrade, is better to completly disable the ruleset upgrade process?
Because if you release new version and I'm not with the last one of wazuh it should stop working.

**Comment by mgmacias95** [comment]
Hello @pierluigiconti ,

There has been a problem with the `update_ruleset.py` script with updates from 2.x to 3.x. The script has been fixed to prevent this problem to happen again in the future. The script is now restricting updates between minors but not between majors.

Download the latest version of the script from https://github.com/wazuh/wazuh-ruleset/raw/master/update_ruleset to get the fixed version. You can still use it without any problem.

Best regards,
Marta

**Comment by pierluigiconti** [comment]
Ok,

in the mean time I've upgraded wazuh to 3.1.0 :)

Thank you a lot,

**Comment by mgmacias95** [comment]
Hello @pierluigiconti,

I'm glad you finally upgraded 😄 ! Let me close this issue. Don't hesitate to create a new one if you have more questions or issues.

Best regards,
Marta
